<a href="https://colab.research.google.com/github/AntonDozhdikov/demogtaphy_stability/blob/main/REGIONAL_RESILIENCE_ML_v5_6_FINAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Региональные траектории социально-экономической и демографической устойчивости России

## V5.6 FINAL FULL PIPELINE — итоговый воспроизводимый эксперимент

### Концепция исследования

**Предмет:** региональные траектории социально-экономической и демографической устойчивости России.

**Эмпирическая база:** официальная региональная статистика Росстата. Основное ядро — приложение к сборнику
«Регионы России. Социально-экономические показатели». Дополнительные официальные источники используются
только если они реально доступны и успешно разбираются конвейером. Недоступность отдельных выпусков
фиксируется в аудите, но не блокирует исследование при достаточности основной панели.

**Временной дизайн:** 2017–2019 гг. — предшоковая база; 2020 г. — внешнее возмущение;
2020–2023 гг. — постшоковая динамика.

**Ключевой принцип:** устойчивость не задаётся искусственным интегральным индексом с произвольными весами.
Она описывается формой постшоковой траектории: глубиной отклонения, восстановлением, новым уровнем и
динамикой демографических, доходных, трудовых и экономических параметров.

### Финальная научная логика V5.6

1. С нуля загружаются только доступные по проверенной схеме V5.4/V5.5 официальные таблицы.
2. После парсинга формируется панель «регион × год × показатель» и обязательный DATA_GATE.
3. Outcome-пространство: **демография, доходы, рынок труда, экономика**.
4. **Социальная поддержка** — предшоковый ресурс/механизм адаптации, а не часть outcome.
5. Неблагоприятные показатели (бедность, безработица, смертность) инвертируются до агрегирования.
6. Дискретная кластеризация сохраняется только как диагностическая гипотеза. Основной результат —
   воспроизводимое **многомерное непрерывное пространство** и четыре блочные оси адаптации.
7. Предшоковыми факторами одинаково тестируются **PC1, PC2 и четыре блочные оси**.
8. Для каждой цели сначала выполняются repeated CV, Ridge baseline и LOYO. Только цели с положительным
   первичным сигналом переходят к bootstrap и negative control.
9. **SHAP, permutation importance и факторная абляция рассчитываются и интерпретируются только для целей,
   прошедших строгий научный gate.**
10. Отрицательный результат по любой цели сохраняется как научный результат, а не превращается в ошибку pipeline.
11. Причинные выводы не делаются: результаты трактуются как воспроизводимые ассоциации.

### Итоговые файлы

Ноутбук сохраняет только компактный комплект для повторения эксперимента и написания статьи:
основной Excel результатов, таблицы для статьи, научный аудит, редактируемые данные рисунков,
машиночитаемые CSV, конфигурацию/requirements и небольшой reproducibility ZIP. Сырые скачанные архивы,
распакованные таблицы и полные panel parquet в итоговый ZIP **не включаются**.

## Дизайн исследования и официальные источники

**Основное окно:** 2017–2023 гг.  
**Предшоковая база:** 2017–2019 гг.  
**Шок:** 2020 г.  
**Постшоковое окно:** 2020–2023 гг.

Основной источник — официальное приложение Росстата к изданию **«Регионы России. Социально-экономические показатели»** (`Pril_Region_Pokaz_2025.rar`).

Дополнительные официальные контуры V5.6:
1. **ВНДН 2018–2024** — только итоговые таблицы по субъектам Российской Федерации; год наблюдения используется как источник данных за предшествующий календарный год, если год не указан непосредственно в заголовке таблицы.
2. **Естественное движение населения Российской Федерации** — ежегодные выпуски.
3. **Численность и миграция населения Российской Федерации** — ежегодные выпуски.
4. **Уровень жизни** — официальные региональные таблицы доходов, бедности и связанных показателей.
5. **Демографический ежегодник России** — электронные приложения по субъектам Российской Федерации.
6. **Социальное положение и уровень жизни населения России** — электронные приложения по субъектам Российской Федерации.
7. **Демография** — дополнительные официальные таблицы Росстата.

Научный принцип: специализированные источники не должны автоматически увеличивать вес одного и того же показателя. Полные данные сохраняются в `PANEL_CLEAN`, а точные дубли рядов исключаются только из аналитической `PANEL` и обязательно фиксируются в аудите.


### V5.6 — расширенная источниковая база

Помимо основного приложения к сборнику «Регионы России. Социально-экономические показатели»,
контур данных пытается получить региональные приложения и результаты Росстата по рынку труда,
уровню жизни, демографии, миграции, малому и среднему предпринимательству, ВНДН, КОУЖ и КДУ.
Все распознанные данные сохраняются в `PANEL_CLEAN`; в основную модель допускаются только
заранее разрешённые источники сопоставимой межрегиональной статистики. После блока 2A
исследование останавливается до решения пользователя.

### V5.6 — контроль выполнения, ETA и тайминги

Эта сборка сохраняет методологию V5.6, но добавляет явный контроль длительных операций: поиск и загрузка источников, распаковку, проверку дублей, разбор таблиц, построение типологии, проверки устойчивости, кросс-валидацию, bootstrap, отрицательный контроль, SHAP и экспорт. `tqdm` показывает elapsed/ETA, а таблица `RUN_TIMINGS` сохраняет фактическое время этапов. Медленные файлы парсера и источники фиксируются в аудитах.

### Научная логика V5.6

Первичное представление устойчивости — медианная траектория каждого содержательного блока по годам 2020–2023 после нормирования относительно 2017–2019 гг. Это уменьшает зависимость результата от одного конкретного показателя. Дискретные типы принимаются только при одновременной разделимости и устойчивости к содержательным возмущениям набора индикаторов. При невыполнении внутренних критериев фиксируется отсутствие воспроизводимой дискретной типологии, а объясняющий анализ проводится для непрерывных компонент пространства траекторий.


### V5.6 — финальная научная логика

Источниковая база заморожена: дальнейшее расширение возможно главным образом через
территориальные сайты Росстата и не является условием основной 85×7 панели.
`social_support` рассматривается как объясняющий фактор/ресурс реакции, а не как
компонент результата устойчивости. Outcome-пространство строится по демографии,
доходам, рынку труда и экономической динамике.

Неблагоприятно направленные показатели (например, бедность, безработица, смертность)
инвертируются до агрегирования, чтобы внутри блока не происходило механического
взаимного погашения разнонаправленных индикаторов.

Если дискретная типология не проходит критерии воспроизводимости, проверяется уже
не ARI кластеров, а устойчивость непрерывной геометрии регионов по корреляции
попарных расстояний. Если и глобальная геометрия неустойчива, исследование не
форсирует единую шкалу и переходит к многомерным блочным траекториям.

In [1]:
# 0. Среда, конфигурация и общие функции
import os,re,io,json,time,math,shutil,zipfile,tarfile,hashlib,warnings,subprocess,sys
from pathlib import Path
from functools import lru_cache
from contextlib import contextmanager
from urllib.parse import urljoin,urlparse,unquote
warnings.filterwarnings("ignore")

_setup_t0=time.perf_counter()
print("0/5 ПОДГОТОВКА СРЕДЫ: проверка/установка библиотек…",flush=True)
_cp=subprocess.run([sys.executable,"-m","pip","install","-q","pandas>=2.2","numpy","requests","beautifulsoup4","lxml","openpyxl","xlrd","xlsxwriter","pyarrow","python-calamine","tqdm","scikit-learn","catboost","matplotlib","joblib"],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
if _cp.returncode!=0:
    print(_cp.stdout[-4000:]); raise RuntimeError("Не удалось подготовить Python-среду")
print(f"✓ Среда: {time.perf_counter()-_setup_t0:.1f} с",flush=True)

import numpy as np,pandas as pd,requests,matplotlib.pyplot as plt,joblib
from bs4 import BeautifulSoup
from tqdm.auto import tqdm
from IPython.display import display
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression,Ridge
from sklearn.cluster import KMeans,AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score,f1_score,balanced_accuracy_score,adjusted_rand_score,r2_score,mean_absolute_error
from sklearn.model_selection import StratifiedKFold,RepeatedStratifiedKFold,KFold,RepeatedKFold
from sklearn.inspection import permutation_importance
from scipy.spatial.distance import pdist
from scipy.stats import spearmanr
from catboost import CatBoostClassifier,CatBoostRegressor,Pool

# Единый формат прогресс-баров: процент, счетчик, elapsed, ETA, скорость и postfix.
PBAR_FORMAT="{desc}: {percentage:3.0f}%|{bar:28}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}{postfix}]"
STAGE_TIMINGS=[]
RUN_T0=time.perf_counter()
SLOW_PARSE_WARN_SEC=20.0

def fmt_sec(sec):
    sec=float(sec or 0)
    if sec<60:return f"{sec:.1f} с"
    m,s=divmod(int(round(sec)),60)
    if m<60:return f"{m} мин {s:02d} с"
    h,m=divmod(m,60)
    return f"{h} ч {m:02d} мин {s:02d} с"

def pbar(iterable=None,total=None,desc="",unit="it",leave=True,position=None):
    kw=dict(desc=desc,unit=unit,leave=leave,dynamic_ncols=True,mininterval=.5,smoothing=.12,bar_format=PBAR_FORMAT)
    # После создания общего progress все локальные бары закрепляются второй строкой.
    if position is None and "PIPELINE_PROGRESS" in globals():
        position=1
    if position is not None:
        kw["position"]=position
    return tqdm(iterable,total=total,**kw) if iterable is not None else tqdm(total=total,**kw)

def timing_start(stage):
    print(f"\n▶ {stage}",flush=True)
    return time.perf_counter()

def timing_end(stage,t0,detail="",**metrics):
    sec=time.perf_counter()-t0
    global STAGE_TIMINGS
    STAGE_TIMINGS=[r for r in STAGE_TIMINGS if r.get("stage")!=stage]
    row={"stage":stage,"seconds":round(sec,3),"elapsed":fmt_sec(sec),"detail":detail}
    row.update(metrics);STAGE_TIMINGS.append(row)
    print(f"✓ {stage}: {fmt_sec(sec)}"+(f" | {detail}" if detail else ""),flush=True)
    return sec

def timing_frame():
    cols=["stage","seconds","elapsed","detail"]
    if not STAGE_TIMINGS:return pd.DataFrame(columns=cols)
    return pd.DataFrame(STAGE_TIMINGS).sort_values("seconds",ascending=False).reset_index(drop=True)


# Единый верхнеуровневый прогресс всего V5.6.
# Веса приблизительно отражают фактическое время предыдущих прогонов.
PIPELINE_WEIGHTS={
    "environment":2,
    "sources":18,
    "parser":28,
    "data_gate":2,
    "trajectories":5,
    "model_validation":30,
    "interpretability":10,
    "exports":5,
}
PIPELINE_PROGRESS=pbar(total=sum(PIPELINE_WEIGHTS.values()),desc="V5.6 ОБЩИЙ ЦИКЛ",unit="%",leave=True,position=0)
PIPELINE_DONE=set()

def pipeline_done(stage,detail=""):
    if stage in PIPELINE_DONE:
        return
    if stage not in PIPELINE_WEIGHTS:
        raise KeyError(f"Неизвестный этап общего progress bar: {stage}")
    PIPELINE_PROGRESS.update(PIPELINE_WEIGHTS[stage])
    PIPELINE_DONE.add(stage)
    PIPELINE_PROGRESS.set_postfix_str((detail or stage)[:90],refresh=True)

def pipeline_close():
    missing=[k for k in PIPELINE_WEIGHTS if k not in PIPELINE_DONE]
    if not missing:
        PIPELINE_PROGRESS.close()

SEED=42; SHOCK_YEAR=2020; PRE_YEARS=[2017,2018,2019]; POST_YEARS=[2020,2021,2022,2023]; ANALYSIS_YEARS=PRE_YEARS+POST_YEARS
BOOT_N=100; REPEATED_CV_REPEATS=5; NEGATIVE_N_FINAL=100
FORCE_DOWNLOAD=False; FORCE_PARSE=True; AUTO_DOWNLOAD=False
# Контроль продолжения вынесен в отдельную ячейку после аудита данных.
ROOT=Path("/content/MONOGRAPH_CH3_V5_6"); RAW=ROOT/"raw"; EXTRACT=ROOT/"extracted"; PROCESSED=ROOT/"processed"; RESULTS=ROOT/"results"; FIG=RESULTS/"figures"; MODELS=RESULTS/"models"; DOCS=ROOT/"docs"; TOOLS=ROOT/"tools"
for p in (ROOT,RAW,EXTRACT,PROCESSED,RESULTS,FIG,MODELS,DOCS,TOOLS): p.mkdir(parents=True,exist_ok=True)
UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/153 Safari/537.36"; HEADERS={"User-Agent":UA,"Accept":"*/*","Accept-Language":"ru-RU,ru;q=0.9,en;q=0.4"}; SESSION=requests.Session(); SESSION.headers.update(HEADERS)

PRIMARY_URL="https://rosstat.gov.ru/storage/mediabank/Pril_Region_Pokaz_2025.rar"

@lru_cache(maxsize=200000)
def norm(s):
    q=str(s).replace("ё","е").replace("Ё","Е").replace("–","-").replace("—","-").replace("\xa0"," ")
    q=re.sub(r"[\*¹²³⁴⁵⁶⁷⁸⁹]+"," ",q)
    return re.sub(r"\s+"," ",q).strip(" .;:").lower()


def _vndn_roots(y):
    # У ВНДН нет полностью стабильной схемы URL. После ВПН-2020 часть выпусков
    # опубликована/пересмотрена в ветках *_VPN-2020. Держим проверенные и
    # совместимые резервные варианты; специализированный навигатор ниже все равно
    # забирает только региональные итоговые таблицы, а не микроданные.
    roots=[
        f"https://rosstat.gov.ru/free_doc/new_site/VNDN-{y}/",
        f"https://rosstat.gov.ru/free_doc/new_site/vndn-{y}/",
        f"https://www.rosstat.gov.ru/free_doc/new_site/VNDN-{y}/",
    ]
    if y in {2020,2021,2022}:
        roots += [
            f"https://rosstat.gov.ru/free_doc/new_site/VNDN-{y}_VPN-2020/",
            f"https://www.rosstat.gov.ru/free_doc/new_site/VNDN-{y}_VPN-2020/",
        ]
    # Удаляем дубли с сохранением порядка.
    return list(dict.fromkeys(roots))

SOURCES={
 "regions_app":{"kind":"direct","urls":[PRIMARY_URL],"keys":[],"page_keys":[],"max_pages":1,"max_assets":1,"role":"primary"},
 # ВНДН: отдельный специализированный навигатор; не заходим в ветки микроданных.
 **{
   f"vndn_{y}":{
       "kind":"vndn","urls":_vndn_roots(y),
       "keys":["доход","социальн","пособ","бедност","субъект","таблиц"],
       "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
       "max_pages":12,"max_assets":40,"allow_html_table":True,
       "default_year":y-1,"role":"survey"
   } for y in range(2018,2025)
 },
 "natural_movement":{"kind":"page","urls":["https://rosstat.gov.ru/compendium/document/13269"],
     "keys":["2023","2022","2021","2020","2019","2018","2017","рождаем","смерт"],"page_keys":[],"max_pages":1,"max_assets":100,"role":"specialized"},
 "migration":{"kind":"page","urls":["https://rosstat.gov.ru/folder/11110/document/13283","https://rosstat.gov.ru/compendium/document/13283"],
     "keys":["2023","2022","2021","2020","2019","2018","2017","миграц"],"page_keys":[],"max_pages":1,"max_assets":100,"role":"specialized"},
 "living":{"kind":"page","urls":["https://rosstat.gov.ru/folder/13397"],
     "keys":["среднедушев","реальн","доход","бедност","джини","пенс","прожиточ","социальн"],"page_keys":[],"max_pages":1,"max_assets":140,"role":"specialized"},
 "social_position":{"kind":"page","urls":["https://rosstat.gov.ru/folder/210/document/13212"],
     "keys":["приложение","субъект","2025","2023","2021","2019","2017","уровень жизни","доход"],"page_keys":[],"max_pages":1,"max_assets":40,"role":"compendium"},
 "demographic_yearbook":{"kind":"page","urls":["https://rosstat.gov.ru/folder/210/document/13207"],
     "keys":["приложение","субъект","2023","2021","2019","2017","демограф"],"page_keys":[],"max_pages":1,"max_assets":40,"role":"compendium"},
 "demography":{"kind":"page","urls":["https://rosstat.gov.ru/folder/12781"],
     "keys":["рождаем","смерт","естествен","продолжительность жизни","миграц","численност населения"],"page_keys":[],"max_pages":1,"max_assets":140,"role":"supplementary"},
}

# V5.6: дополнительные официальные источники Росстата.
# Они сохраняются в полном массиве; часть источников используется только как
# дополнительная эмпирика и не допускается в основную модель автоматически.
SOURCES.update({
    "workforce_compendium":{
        "kind":"page","urls":["https://rosstat.gov.ru/folder/210/document/13211"],
        "keys":["приложение","субъект","2018","2020","2022","2024","рабочая сила","занятость","безработица"],
        "page_keys":[],"max_pages":2,"max_assets":80,"role":"compendium"
    },
    "labour_compendium":{
        "kind":"page","urls":["https://rosstat.gov.ru/folder/210/document/13210"],
        "keys":["приложение","субъект","2017","2019","2021","2023","труд","занятость","безработица","заработная плата"],
        "page_keys":[],"max_pages":2,"max_assets":80,"role":"compendium"
    },
    "sme_compendium":{
        "kind":"page","urls":["https://rosstat.gov.ru/folder/210/document/13223"],
        "keys":["приложение","субъект","2017","2019","2022","2024","малое","среднее","предпринимательство"],
        "page_keys":[],"max_pages":2,"max_assets":80,"role":"compendium"
    },
    "kouzh_2018":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2018/","https://www.rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2018/"],
        "keys":["условия жизни","доход","занятость","социальн","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2018,"role":"survey"
    },
    "kouzh_2020":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2020/","https://www.rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2020/"],
        "keys":["условия жизни","доход","занятость","социальн","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2020,"role":"survey"
    },
    "kouzh_2022":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2022/","https://www.rosstat.gov.ru/free_doc/new/site/GKS_KOUZH_2022/","https://www.rosstat.gov.ru/free_doc/new_site/GKS_KOUZH_2022/"],
        "keys":["условия жизни","доход","занятость","социальн","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2022,"role":"survey"
    },
    "kdu_2017":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/KDU_2017/","https://www.rosstat.gov.ru/free_doc/new_site/KDU_2017/"],
        "keys":["доход","социальн","программ","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2017,"role":"survey"
    },
    "kdu_2019":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/KDU_2019/","https://www.rosstat.gov.ru/free_doc/new_site/KDU_2019/"],
        "keys":["доход","социальн","программ","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2019,"role":"survey"
    },
    "kdu_2021":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/KDU_2021/","https://www.rosstat.gov.ru/free_doc/new_site/KDU_2021/"],
        "keys":["доход","социальн","программ","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2021,"role":"survey"
    },
    "kdu_2023":{
        "kind":"vndn","urls":["https://rosstat.gov.ru/free_doc/new_site/KDU_2023/","https://www.rosstat.gov.ru/free_doc/new_site/KDU_2023/"],
        "keys":["доход","социальн","программ","субъект","таблиц"],
        "page_keys":["итоги наблюдения","статистические таблицы","субъекты российской федерации"],
        "max_pages":14,"max_assets":60,"allow_html_table":True,"default_year":2023,"role":"survey"
    },
})

# Основная модель использует только источники, пригодные для устойчивого
# межрегионального сопоставления. Дополнительные обследования сохраняются в CLEAN.
MODEL_ELIGIBLE_SOURCES={
    "regions_app","natural_movement","migration","living","social_position",
    "demographic_yearbook","workforce_compendium","labour_compendium","sme_compendium",
    *{f"vndn_{y}" for y in range(2018,2025)}
}
SOURCE_CATALOG=pd.DataFrame([
    {"source":k,"role":v.get("role",""),"kind":v.get("kind",""),
     "model_eligible":k in MODEL_ELIGIBLE_SOURCES,
     "urls":"; ".join(v.get("urls",[]))}
    for k,v in SOURCES.items()
]).sort_values(["model_eligible","source"],ascending=[False,True]).reset_index(drop=True)

SOURCE_DEFAULT_YEAR={k:v.get("default_year") for k,v in SOURCES.items()}
FILE_EXT={".csv",".xlsx",".xls",".zip",".rar"}
HTML_EXT={".html",".htm"}
TABLE_EXT=FILE_EXT|HTML_EXT


def safe(s): return re.sub(r"[^0-9A-Za-zА-Яа-яЁё._-]+","_",str(s)).strip("_")[:180]
def sha256(p,chunk=1024*1024):
    h=hashlib.sha256()
    with open(p,"rb") as f:
        while True:
            b=f.read(chunk)
            if not b: break
            h.update(b)
    return h.hexdigest()
def official(u):
    h=(urlparse(u).hostname or "").lower(); return h=="rosstat.gov.ru" or h=="www.rosstat.gov.ru" or h.endswith(".rosstat.gov.ru")
def htmlish(b): return b"<html" in b[:2000].lower() or b"<!doctype" in b[:2000].lower()
def variants(u):
    out=[u]
    if "://rosstat.gov.ru/" in u: out.append(u.replace("://rosstat.gov.ru/","://www.rosstat.gov.ru/",1))
    if "://www.rosstat.gov.ru/" in u: out.append(u.replace("://www.rosstat.gov.ru/","://rosstat.gov.ru/",1))
    return list(dict.fromkeys(out))
def fetch(u,html_ok=False,referer=None,timeout=120):
    hh=dict(HEADERS); hh.update({"Referer":referer} if referer else {}); errs=[]
    for q in variants(u):
        for verify in (True,False):
            try:
                r=SESSION.get(q,headers=hh,timeout=(15,timeout),allow_redirects=True,verify=verify)
                if r.status_code==200 and len(r.content)>50 and (html_ok or not htmlish(r.content)): return r.content,dict(r.headers),r.url,f"requests/{verify}"
                errs.append(f"HTTP {r.status_code}:{q}")
            except Exception as e: errs.append(f"{type(e).__name__}:{str(e)[:100]}")
    tmp=ROOT/"_curl.tmp"; tmp.unlink(missing_ok=True)
    cmd=["curl","-k","--http1.1","--compressed","-L","--retry","4","--retry-all-errors","--connect-timeout","15","--max-time",str(timeout),"-A",UA,"-sS","-o",str(tmp)]
    if referer: cmd += ["-e",referer]
    cp=subprocess.run(cmd+[u],stdout=subprocess.DEVNULL,stderr=subprocess.PIPE,text=True)
    if cp.returncode==0 and tmp.exists() and tmp.stat().st_size>50:
        b=tmp.read_bytes(); tmp.unlink(missing_ok=True)
        if html_ok or not htmlish(b): return b,{},u,"curl"
    raise RuntimeError(" | ".join(errs[-8:])+(" | curl:"+cp.stderr[-120:] if cp.stderr else ""))

def magic_kind(b,u="",h=None):
    path=urlparse(u).path.lower(); h=h or {}; cd=str(h.get("content-disposition",h.get("Content-Disposition",""))).lower()
    if b.startswith(b"Rar!\x1a\x07"): return "rar"
    if b[:8]==bytes.fromhex("D0CF11E0A1B11AE1"): return "xls"
    if b[:4]==b"PK\x03\x04": return "xlsx" if (".xlsx" in path or ".xlsx" in cd) else "zip"
    if htmlish(b): return "html"
    if path.endswith(".csv") or b";" in b[:2500] or b"," in b[:2500]: return "csv"
    return "bin"
def ext_for_kind(k): return {"rar":".rar","zip":".zip","xlsx":".xlsx","xls":".xls","csv":".csv","html":".html"}.get(k,".bin")
def valid_table_file(p):
    if not p.exists() or p.stat().st_size<20: return False
    with open(p,"rb") as f: b=f.read(4096)
    s=p.suffix.lower()
    if s==".xlsx": return b.startswith((b"PK\x03\x04",b"PK\x05\x06",b"PK\x07\x08"))
    if s==".xls": return b.startswith(bytes.fromhex("D0CF11E0A1B11AE1"))
    if s==".csv": return True
    if s in HTML_EXT: return b"<table" in b.lower() or b"<html" in b.lower()
    return False

timing_end("00_environment",_setup_t0,detail=str(ROOT))
print("Среда готова:",ROOT)

# V5.6: внутренние критерии воспроизводимости (не являются универсальными статистическими порогами).
TYPOLOGY_MIN_SILHOUETTE=0.10
TYPOLOGY_MIN_INDICATOR_ARI=0.60
TYPOLOGY_MIN_NORMALIZATION_ARI=0.60
TYPOLOGY_MIN_CONSENSUS_ARI=0.60
TYPOLOGY_MIN_CONSENSUS_GAP=0.20
# V5.6: критерии воспроизводимости НЕПРЕРЫВНОГО пространства.
# Это не тест «существует ли кластер», а проверка устойчивости геометрии регионов.
CONTINUUM_MIN_NORM_DISTANCE_RHO=0.50
CONTINUUM_MIN_INDICATOR_DISTANCE_RHO=0.60
CONTINUUM_MIN_LOO_DISTANCE_RHO=0.70
CONTINUUM_MIN_LOB_DISTANCE_RHO=0.40
REPEATED_CV_REPEATS=5

pipeline_done("environment","среда и конфигурация готовы")

0/5 ПОДГОТОВКА СРЕДЫ: проверка/установка библиотек…
✓ Среда: 16.0 с

V5.6 ОБЩИЙ ЦИКЛ:   0%|                            | 0/100 [00:00<?, ?%/s]

✓ 00_environment: 23.4 с | /content/MONOGRAPH_CH3_V5_6
Среда готова: /content/MONOGRAPH_CH3_V5_6

In [2]:
# 1. Расширенный поиск, загрузка и ВЕРИФИЦИРОВАННАЯ распаковка официальных источников Росстата

def page_text(b):
    for enc in ("utf-8","cp1251"):
        try:return b.decode(enc)
        except:pass
    return b.decode("utf-8",errors="ignore")

def norm_path(u):
    return unquote(urlparse(u).path).lower().rstrip("/")+"/"

def in_tree(u,prefix=None):
    if not official(u): return False
    return True if not prefix else norm_path(u).startswith(unquote(prefix).lower().rstrip("/")+"/")

def page_score(ctx,page_keys):
    c=ctx.lower()
    return sum(12 for k in page_keys if k.lower() in c)+sum(2 for y in map(str,ANALYSIS_YEARS) if y in c)

def asset_score(ctx,keys,ext,u):
    c=ctx.lower()
    s=sum(8 for k in keys if k.lower() in c)+sum(3 for y in map(str,ANALYSIS_YEARS) if y in c)
    if ext in FILE_EXT:s+=5
    if "/storage/mediabank/" in u.lower():s+=4
    if any(x in c for x in ("субъект","регион")):s+=6
    # Современные файлы вне исследовательского окна не запрещаем, но понижаем в ранге.
    years=[int(x) for x in re.findall(r"(?<!\d)(20\d{2})(?!\d)",c)]
    if years and not any(y in ANALYSIS_YEARS for y in years):s-=4
    return s

def _collect_file_links(soup,base,keys,allow_html_table=False):
    out=[]; seen=set()
    for a in soup.find_all("a",href=True):
        href=str(a.get("href","")).strip()
        if not href or href.lower().startswith(("javascript:","mailto:","tel:")):continue
        v=urljoin(base,href).split("#",1)[0]
        if not official(v):continue
        txt=" ".join(a.stripped_strings)
        parent=" ".join(a.parent.stripped_strings) if a.parent else txt
        ctx=unquote(txt+" "+parent+" "+v).lower()
        ext=Path(urlparse(v).path).suffix.lower()
        is_file=ext in FILE_EXT
        is_html_table=allow_html_table and ext in HTML_EXT and ("таблиц" in ctx or "table" in ctx)
        if is_file or is_html_table:
            sc=asset_score(ctx,keys,ext,v)
            if v not in seen:
                out.append((max(sc,1),v,txt,base));seen.add(v)
    return out

def discover_vndn_assets(spec,src):
    """ВНДН: идём только Общее -> Итоги -> Статистические таблицы -> Субъекты РФ."""
    nav_terms=("итоги наблюдения","статистические таблицы","субъекты российской федерации")
    roots=spec.get("urls",[])
    q=[(999,u,None,"seed") for u in roots]
    seen=set(); assets=[]; seen_assets=set(); page_rows=[]
    pages_dir=RAW/"_pages"/src; pages_dir.mkdir(parents=True,exist_ok=True)
    _max_pages=int(spec.get("max_pages",12)); _pb=pbar(total=_max_pages,desc=f"  страницы {src}",unit="стр",leave=False,position=1)
    while q and len(seen)<_max_pages:
        q.sort(key=lambda z:z[0],reverse=True)
        _,u,ref,why=q.pop(0); canonical=u.split("#",1)[0]
        if canonical in seen or not official(canonical):continue
        try:
            b,hh,fu,method=fetch(canonical,html_ok=True,referer=ref,timeout=100)
            html=page_text(b); seen.add(canonical)
            (pages_dir/f"{len(seen):02d}_{safe(urlparse(fu).path or 'index')}.html").write_text(html,encoding="utf-8")
            soup=BeautifulSoup(html,"lxml")
            page_text_norm=norm(" ".join(soup.stripped_strings))
            is_subject=("субъекты российской федерации" in page_text_norm or
                        "субъекты%20российской" in fu.lower() or "%d1%81%d1%83%d0%b1%d1%8a%d0%b5%d0%ba%d1%82" in fu.lower())
            found_a=0;found_p=0
            if is_subject:
                for item in _collect_file_links(soup,fu,spec.get("keys",[]),allow_html_table=bool(spec.get("allow_html_table"))):
                    sc,v,txt,base=item
                    if v not in seen_assets:
                        assets.append(item);seen_assets.add(v);found_a+=1
            for a in soup.find_all("a",href=True):
                txt=norm(" ".join(a.stripped_strings))
                parent=norm(" ".join(a.parent.stripped_strings) if a.parent else txt)
                ctx=txt+" "+parent
                if not any(term in ctx for term in nav_terms):continue
                v=urljoin(fu,str(a.get("href",""))).split("#",1)[0]
                if not official(v) or v in seen:continue
                q.append((50+sum(term in ctx for term in nav_terms)*10,v,fu,txt[:120]));found_p+=1
            # Некоторые старые страницы содержат прямые пути в JS/HTML.
            if is_subject:
                for mm in re.findall(r'["\\\']([^"\\\']+\\.(?:csv|xlsx?|zip|rar)(?:\\?[^"\\\']*)?)["\\\']',html,re.I):
                    v=urljoin(fu,mm).split("#",1)[0]
                    if official(v) and v not in seen_assets:
                        ext=Path(urlparse(v).path).suffix.lower()
                        sc=asset_score(unquote(v),spec.get("keys",[]),ext,v)
                        assets.append((max(sc,5),v,Path(urlparse(v).path).name,fu));seen_assets.add(v);found_a+=1
            page_rows.append({"source":src,"page":fu,"method":method,"seed_reason":why,
                              "assets_found":found_a,"child_pages_added":found_p,"ok":True,"note":""})
            _pb.update(1); _pb.set_postfix(files=len(assets),queue=len(q))
        except Exception as e:
            seen.add(canonical)
            page_rows.append({"source":src,"page":canonical,"method":"","seed_reason":why,
                              "assets_found":0,"child_pages_added":0,"ok":False,
                              "note":f"{type(e).__name__}: {str(e)[:220]}"})
            _pb.update(1); _pb.set_postfix(files=len(assets),queue=len(q))
    _pb.total=max(_pb.n,1); _pb.refresh(); _pb.close()
    assets=sorted(assets,key=lambda x:(x[0],x[1]),reverse=True)[:int(spec.get("max_assets",40))]
    return [(u,t,ref,score) for score,u,t,ref in assets],page_rows

def discover_assets(spec,src):
    if spec.get("kind")=="vndn":
        return discover_vndn_assets(spec,src)
    roots=spec.get("urls",[]);keys=spec.get("keys",[]);pkeys=spec.get("page_keys",[])
    prefix=spec.get("tree_prefix");max_pages=int(spec.get("max_pages",1));max_assets=int(spec.get("max_assets",20))
    kind=spec.get("kind","page")
    q=[(999,u,None,"seed") for u in roots];seen_pages=set();assets=[];seen_assets=set();page_rows=[]
    pages_dir=RAW/"_pages"/src;pages_dir.mkdir(parents=True,exist_ok=True)
    _pb=pbar(total=max_pages,desc=f"  страницы {src}",unit="стр",leave=False,position=1)
    while q and len(seen_pages)<max_pages:
        q.sort(key=lambda x:x[0],reverse=True);_,u,ref,why=q.pop(0);canonical=u.split("#",1)[0]
        if canonical in seen_pages or not official(canonical):continue
        if kind=="crawl" and prefix and not in_tree(canonical,prefix):continue
        try:
            b,hh,fu,method=fetch(canonical,html_ok=True,referer=ref,timeout=100)
            html=page_text(b);seen_pages.add(canonical)
            (pages_dir/f"{len(seen_pages):02d}_{safe(urlparse(fu).path or 'index')}.html").write_text(html,encoding="utf-8")
            soup=BeautifulSoup(html,"lxml");found_a=0;found_p=0
            for sc,v,txt,base in _collect_file_links(soup,fu,keys,allow_html_table=False):
                if v not in seen_assets:
                    assets.append((sc,v,txt,base));seen_assets.add(v);found_a+=1
            if kind=="crawl":
                for a in soup.find_all("a",href=True):
                    href=str(a.get("href","")).strip()
                    if not href:continue
                    v=urljoin(fu,href).split("#",1)[0]
                    if not official(v) or not in_tree(v,prefix):continue
                    txt=" ".join(a.stripped_strings);parent=" ".join(a.parent.stripped_strings) if a.parent else txt
                    ctx=unquote(txt+" "+parent+" "+v).lower();ext=Path(urlparse(v).path).suffix.lower()
                    html_candidate=(ext in {"",".html",".htm"} or v.endswith("/"));psc=page_score(ctx,pkeys)
                    if html_candidate and psc>0 and v not in seen_pages:
                        q.append((psc,v,fu,txt[:120]));found_p+=1
            for mm in re.findall(r'["\\\']([^"\\\']+\\.(?:csv|xlsx?|zip|rar)(?:\\?[^"\\\']*)?)["\\\']',html,re.I):
                v=urljoin(fu,mm).split("#",1)[0]
                if official(v) and v not in seen_assets:
                    ext=Path(urlparse(v).path).suffix.lower();sc=asset_score(unquote(v),keys,ext,v)
                    assets.append((max(sc,5),v,Path(urlparse(v).path).name,fu));seen_assets.add(v);found_a+=1
            page_rows.append({"source":src,"page":fu,"method":method,"seed_reason":why,
                              "assets_found":found_a,"child_pages_added":found_p,"ok":True,"note":""})
            _pb.update(1); _pb.set_postfix(files=len(assets),queue=len(q))
        except Exception as e:
            seen_pages.add(canonical)
            page_rows.append({"source":src,"page":canonical,"method":"","seed_reason":why,
                              "assets_found":0,"child_pages_added":0,"ok":False,
                              "note":f"{type(e).__name__}: {str(e)[:220]}"})
            _pb.update(1); _pb.set_postfix(files=len(assets),queue=len(q))
    _pb.total=max(_pb.n,1); _pb.refresh(); _pb.close()
    assets=sorted(assets,key=lambda x:(x[0],x[1]),reverse=True)[:max_assets]
    return [(u,t,ref,score) for score,u,t,ref in assets],page_rows

def ensure_modern_unrar(test_archive=None):
    tool=TOOLS/"rarlab"/"unrar"; candidates=[str(tool),shutil.which("unrar")]
    for c in candidates:
        if c and Path(c).exists() and (test_archive is None or subprocess.run([c,"t","-idq",str(test_archive)],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL).returncode==0): return c
    html=SESSION.get("https://www.rarlab.com/download.htm",headers=HEADERS,timeout=60).text
    m=re.search(r'href=["\']([^"\']*rarlinux-x64-\d+\.tar\.gz)["\']',html,re.I)
    url=urljoin("https://www.rarlab.com/download.htm",m.group(1)) if m else "https://www.rarlab.com/rar/rarlinux-x64-723.tar.gz"
    pkg=TOOLS/"rarlinux.tar.gz"; b,_,_,_=fetch(url,timeout=120); pkg.write_bytes(b); out=TOOLS/"rarlab"; shutil.rmtree(out,ignore_errors=True); out.mkdir(parents=True)
    with tarfile.open(pkg,"r:gz") as tf: tf.extractall(out)
    found=list(out.rglob("unrar"))
    if not found: raise RuntimeError("Официальный пакет RARLAB загружен, но unrar не найден")
    src=found[0]; tool.write_bytes(src.read_bytes()); tool.chmod(0o755)
    if test_archive is not None:
        cp=subprocess.run([str(tool),"t","-idq",str(test_archive)],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
        if cp.returncode!=0: raise RuntimeError("Современный unrar не читает архив: "+cp.stdout[-500:])
    return str(tool)

def extract_archive(p,d):
    shutil.rmtree(d,ignore_errors=True); d.mkdir(parents=True,exist_ok=True)
    if p.suffix.lower()==".zip":
        with zipfile.ZipFile(p) as z:z.extractall(d)
    elif p.suffix.lower()==".rar":
        unrar=ensure_modern_unrar(p); cp=subprocess.run([unrar,"x","-o+","-idq",str(p),str(d)+"/"],stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True)
        if cp.returncode!=0: raise RuntimeError("RAR extraction failed: "+cp.stdout[-500:])


def download_one(src,u,ref=None,idx=0,allow_html=False):
    b,h,fu,method=fetch(u,html_ok=allow_html,referer=ref,timeout=240)
    kind=magic_kind(b,fu,h)
    allowed={"rar","zip","xlsx","xls","csv"}|({"html"} if allow_html else set())
    if kind not in allowed:raise RuntimeError(f"не табличный ответ ({kind})")
    name=Path(unquote(urlparse(fu).path)).stem or f"asset_{idx}"
    p=RAW/src/f"{idx:03d}_{safe(name)}{ext_for_kind(kind)}";p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes(b)
    return p,fu,method,kind

SOURCE_ROWS=[];DOWNLOAD_ROWS=[];DISCOVERY_ROWS=[]
_STAGE1_T0=timing_start("01_sources_download_extract")
_srcbar=pbar(list(SOURCES.items()),desc="1/5 ИСТОЧНИКИ",unit="ист",leave=True,position=0)
for src,spec in _srcbar:
    _src_t0=time.perf_counter(); _disc_sec=_down_sec=_ext_sec=0.0
    _srcbar.set_postfix(source=src)
    rd=RAW/src;xd=EXTRACT/src;rd.mkdir(parents=True,exist_ok=True);xd.mkdir(parents=True,exist_ok=True)
    cached=[p for p in rd.glob("*") if p.is_file() and p.suffix.lower() in TABLE_EXT]
    try:
        if FORCE_DOWNLOAD or not cached:
            shutil.rmtree(rd,ignore_errors=True);shutil.rmtree(xd,ignore_errors=True);rd.mkdir(parents=True);xd.mkdir(parents=True)
            _td=time.perf_counter()
            if spec["kind"]=="direct":
                assets=[(spec["urls"][0],src,spec["urls"][0],999)];page_rows=[]
            else:
                assets,page_rows=discover_assets(spec,src)
            _disc_sec=time.perf_counter()-_td
            DISCOVERY_ROWS.extend(page_rows);saved=[];errs=[]
            if not assets:errs.append("по релевантным страницам не найдено ссылок на табличные файлы")
            for i,(u,t,ref,score) in enumerate(pbar(assets,desc=f"  загрузка {src}",unit="файл",leave=False,position=1)):
                try:
                    _tdl=time.perf_counter(); p,fu,method,kind=download_one(src,u,ref,i,allow_html=bool(spec.get("allow_html_table"))); _down_sec+=time.perf_counter()-_tdl
                    saved.append(p)
                    DOWNLOAD_ROWS.append({"source":src,"file":str(p),"url":fu,"referer":ref,"label":t,
                                          "method":method,"kind":kind,"size_mb":round(p.stat().st_size/1024**2,3),
                                          "score":score,"default_year":spec.get("default_year")})
                except Exception as e:
                    errs.append(f"{type(e).__name__}:{str(e)[:180]}")
        else:
            saved=cached;errs=[]
        _te=time.perf_counter()
        for p in pbar(saved,desc=f"  распаковка {src}",unit="файл",leave=False,position=1):
            if p.suffix.lower() in {".rar",".zip"}:
                target=xd/p.stem
                if FORCE_DOWNLOAD or not target.exists() or not any(valid_table_file(x) for x in target.rglob("*") if x.is_file()):
                    extract_archive(p,target)
            else:
                q=xd/p.name
                if not q.exists():shutil.copy2(p,q)
        _ext_sec=time.perf_counter()-_te
        tables=[p for p in xd.rglob("*") if p.is_file() and p.suffix.lower() in TABLE_EXT and valid_table_file(p)]
        source_pages=sum(1 for x in DISCOVERY_ROWS if x["source"]==src and x["ok"])
        SOURCE_ROWS.append({"source":src,"role":spec.get("role",""),"expected_data_year":spec.get("default_year"),
                            "ok":bool(saved) and bool(tables),"pages_scanned":source_pages,
                            "downloaded_files":len(saved),"valid_tables":len(tables),
                            "raw_mb":round(sum(p.stat().st_size for p in saved)/1024**2,2),
                            "discovery_sec":round(_disc_sec,2),"download_sec":round(_down_sec,2),"extract_sec":round(_ext_sec,2),
                            "source_sec":round(time.perf_counter()-_src_t0,2),
                            "note":"OK" if tables else (" | ".join(errs[-4:]) or "нет валидных таблиц")})
        _srcbar.set_postfix(source=src,tables=len(tables),sec=f"{time.perf_counter()-_src_t0:.1f}")
    except Exception as e:
        SOURCE_ROWS.append({"source":src,"role":spec.get("role",""),"expected_data_year":spec.get("default_year"),
                            "ok":False,"pages_scanned":sum(1 for x in DISCOVERY_ROWS if x["source"]==src and x["ok"]),
                            "downloaded_files":len(cached),"valid_tables":0,
                            "raw_mb":round(sum(p.stat().st_size for p in cached)/1024**2,2) if cached else 0,
                            "discovery_sec":round(_disc_sec,2),"download_sec":round(_down_sec,2),"extract_sec":round(_ext_sec,2),
                            "source_sec":round(time.perf_counter()-_src_t0,2),
                            "note":f"{type(e).__name__}: {str(e)[:350]}"})
        _srcbar.set_postfix(source=src,error=type(e).__name__)
_srcbar.close()

SOURCE_AUDIT=pd.DataFrame(SOURCE_ROWS);DOWNLOAD_INDEX=pd.DataFrame(DOWNLOAD_ROWS);DISCOVERY_AUDIT=pd.DataFrame(DISCOVERY_ROWS)
if DOWNLOAD_INDEX.empty and (PROCESSED/"download_index.csv").exists():DOWNLOAD_INDEX=pd.read_csv(PROCESSED/"download_index.csv")
primary=SOURCE_AUDIT.set_index("source").loc["regions_app"]
if not bool(primary.ok):raise RuntimeError("Основной архив «Регионы России» не прошёл загрузку/распаковку: "+str(primary.note))
primary_files=[p for p in (EXTRACT/"regions_app").rglob("*") if p.is_file() and p.suffix.lower() in TABLE_EXT and valid_table_file(p)]
if len(primary_files)<10:raise RuntimeError(f"После корректной распаковки найдено только {len(primary_files)} валидных таблиц regions_app.")
SOURCE_AUDIT.to_csv(PROCESSED/"source_audit.csv",index=False)
DOWNLOAD_INDEX.to_csv(PROCESSED/"download_index.csv",index=False)
DISCOVERY_AUDIT.to_csv(PROCESSED/"discovery_audit.csv",index=False)
timing_end("01_sources_download_extract",_STAGE1_T0,detail=f"sources={len(SOURCE_AUDIT)}, ok={int(SOURCE_AUDIT.ok.sum())}, valid_tables={int(SOURCE_AUDIT.valid_tables.sum())}")
display(SOURCE_AUDIT)

pipeline_done("sources","источники загружены/зафиксированы")

▶ 01_sources_download_extract

1/5 ИСТОЧНИКИ:   0%|                            | 0/24 [00:00<?, ?ист/s]

  загрузка regions_app:   0%|                            | 0/1 [00:00<?, ?файл/s]

  распаковка regions_app:   0%|                            | 0/1 [00:00<?, ?файл/s]

  страницы vndn_2018:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2018:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка vndn_2018:   0%|                            | 0/0 [00:00<?, ?файл/s]

  страницы vndn_2019:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2019:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка vndn_2019:   0%|                            | 0/0 [00:00<?, ?файл/s]

  страницы vndn_2020:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2020:   0%|                            | 0/12 [00:00<?, ?файл/s]

  распаковка vndn_2020:   0%|                            | 0/12 [00:00<?, ?файл/s]

  страницы vndn_2021:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2021:   0%|                            | 0/12 [00:00<?, ?файл/s]

  распаковка vndn_2021:   0%|                            | 0/12 [00:00<?, ?файл/s]

  страницы vndn_2022:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2022:   0%|                            | 0/12 [00:00<?, ?файл/s]

  распаковка vndn_2022:   0%|                            | 0/12 [00:00<?, ?файл/s]

  страницы vndn_2023:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2023:   0%|                            | 0/18 [00:00<?, ?файл/s]

  распаковка vndn_2023:   0%|                            | 0/18 [00:00<?, ?файл/s]

  страницы vndn_2024:   0%|                            | 0/12 [00:00<?, ?стр/s]

  загрузка vndn_2024:   0%|                            | 0/18 [00:00<?, ?файл/s]

  распаковка vndn_2024:   0%|                            | 0/18 [00:00<?, ?файл/s]

  страницы natural_movement:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка natural_movement:   0%|                            | 0/16 [00:00<?, ?файл/s]

  распаковка natural_movement:   0%|                            | 0/16 [00:00<?, ?файл/s]

  страницы migration:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка migration:   0%|                            | 0/16 [00:00<?, ?файл/s]

  распаковка migration:   0%|                            | 0/16 [00:00<?, ?файл/s]

  страницы living:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка living:   0%|                            | 0/118 [00:00<?, ?файл/s]

  распаковка living:   0%|                            | 0/118 [00:00<?, ?файл/s]

  страницы social_position:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка social_position:   0%|                            | 0/23 [00:00<?, ?файл/s]

  распаковка social_position:   0%|                            | 0/23 [00:00<?, ?файл/s]

  страницы demographic_yearbook:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка demographic_yearbook:   0%|                            | 0/17 [00:00<?, ?файл/s]

  распаковка demographic_yearbook:   0%|                            | 0/17 [00:00<?, ?файл/s]

  страницы demography:   0%|                            | 0/1 [00:00<?, ?стр/s]

  загрузка demography:   0%|                            | 0/62 [00:00<?, ?файл/s]

  распаковка demography:   0%|                            | 0/62 [00:00<?, ?файл/s]

  страницы workforce_compendium:   0%|                            | 0/2 [00:00<?, ?стр/s]

  загрузка workforce_compendium:   0%|                            | 0/16 [00:00<?, ?файл/s]

  распаковка workforce_compendium:   0%|                            | 0/16 [00:00<?, ?файл/s]

  страницы labour_compendium:   0%|                            | 0/2 [00:00<?, ?стр/s]

  загрузка labour_compendium:   0%|                            | 0/17 [00:00<?, ?файл/s]

  распаковка labour_compendium:   0%|                            | 0/17 [00:00<?, ?файл/s]

  страницы sme_compendium:   0%|                            | 0/2 [00:00<?, ?стр/s]

  загрузка sme_compendium:   0%|                            | 0/20 [00:00<?, ?файл/s]

  распаковка sme_compendium:   0%|                            | 0/20 [00:00<?, ?файл/s]

  страницы kouzh_2018:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kouzh_2018:   0%|                            | 0/60 [00:00<?, ?файл/s]

  распаковка kouzh_2018:   0%|                            | 0/60 [00:00<?, ?файл/s]

  страницы kouzh_2020:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kouzh_2020:   0%|                            | 0/36 [00:00<?, ?файл/s]

  распаковка kouzh_2020:   0%|                            | 0/36 [00:00<?, ?файл/s]

  страницы kouzh_2022:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kouzh_2022:   0%|                            | 0/36 [00:00<?, ?файл/s]

  распаковка kouzh_2022:   0%|                            | 0/36 [00:00<?, ?файл/s]

  страницы kdu_2017:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kdu_2017:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка kdu_2017:   0%|                            | 0/0 [00:00<?, ?файл/s]

  страницы kdu_2019:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kdu_2019:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка kdu_2019:   0%|                            | 0/0 [00:00<?, ?файл/s]

  страницы kdu_2021:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kdu_2021:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка kdu_2021:   0%|                            | 0/0 [00:00<?, ?файл/s]

  страницы kdu_2023:   0%|                            | 0/14 [00:00<?, ?стр/s]

  загрузка kdu_2023:   0%|                            | 0/0 [00:00<?, ?файл/s]

  распаковка kdu_2023:   0%|                            | 0/0 [00:00<?, ?файл/s]

✓ 01_sources_download_extract: 13 мин 22 с | sources=24, ok=18, valid_tables=1675

,source,role,expected_data_year,ok,pages_scanned,downloaded_files,valid_tables,raw_mb,discovery_sec,download_sec,extract_sec,source_sec,note
0,regions_app,primary,NaN,True,0,1,22,8.86,0.00,4.12,0.40,4.56,OK
1,vndn_2018,survey,2017.0,False,3,0,0,0.00,8.72,0.00,0.08,8.87,по релевантным страницам не найдено ссылок на ...
2,vndn_2019,survey,2018.0,False,3,0,0,0.00,5.47,0.00,0.02,5.54,по релевантным страницам не найдено ссылок на ...
3,vndn_2020,survey,2019.0,True,11,12,12,0.24,10.45,9.30,0.03,19.82,OK
4,vndn_2021,survey,2020.0,True,11,12,12,0.27,9.51,8.23,0.01,17.78,OK
5,vndn_2022,survey,2021.0,True,11,12,12,0.25,10.25,8.49,0.02,18.78,OK
6,vndn_2023,survey,2022.0,True,12,18,18,0.42,6.48,12.22,0.02,18.75,OK
7,vndn_2024,survey,2023.0,True,12,18,18,0.38,7.24,11.90,0.02,19.20,OK
8,natural_movement,specialized,NaN,True,1,16,32,4.09,1.37,24.21,0.17,25.79,OK
9,migration,specialized,NaN,True,1,16,402,13.87,1.39,23.47,0.74,25.65,OK
10,living,specialized,NaN,True,1,118,228,42.50,2.60,191.95,0.91,195.60,OK
11,social_position,compendium,NaN,True,1,23,55,41.49,2.21,62.93,1.60,66.78,OK
12,demographic_yearbook,compendium,NaN,True,1,17,439,28.88,1.56,35.11,1.17,37.91,OK
13,demography,supplementary,NaN,True,1,62,66,16.99,2.07,89.63,0.11,91.88,OK
14,workforce_compendium,compendium,NaN,True,1,16,36,15.17,1.55,29.21,0.64,31.44,OK
15,labour_compendium,compendium,NaN,True,1,17,56,28.50,1.20,53.57,1.81,56.62,OK
16,sme_compendium,compendium,NaN,True,1,20,135,20.20,1.65,36.32,0.93,38.94,OK
17,kouzh_2018,survey,2018.0,True,8,60,60,1.41,5.83,38.48,0.04,44.42,OK
18,kouzh_2020,survey,2020.0,True,8,36,36,0.81,4.28,23.80,0.03,28.15,OK
19,kouzh_2022,survey,2022.0,True,9,36,36,0.86,6.59,23.64,0.02,30.29,OK
20,kdu_2017,survey,2017.0,False,2,0,0,0.00,4.08,0.00,0.02,4.12,по релевантным страницам не найдено ссылок на ...
21,kdu_2019,survey,2019.0,False,2,0,0,0.00,3.54,0.00,0.01,3.57,по релевантным страницам не найдено ссылок на ...
22,kdu_2021,survey,2021.0,False,2,0,0,0.00,3.51,0.00,0.02,3.54,по релевантным страницам не найдено ссылок на ...
23,kdu_2023,survey,2023.0,False,2,0,0,0.00,3.54,0.00,0.02,3.58,по релевантным страницам не найдено ссылок на ...

In [3]:
# 2. Полный разбор таблиц Росстата → RAW / CLEAN / аналитическая панель
_STAGE2_T0=timing_start("02_full_table_parser")
REGIONS=["Республика Адыгея","Республика Алтай","Республика Башкортостан","Республика Бурятия","Республика Дагестан","Республика Ингушетия","Кабардино-Балкарская Республика","Республика Калмыкия","Карачаево-Черкесская Республика","Республика Карелия","Республика Коми","Республика Марий Эл","Республика Мордовия","Республика Саха (Якутия)","Республика Северная Осетия - Алания","Республика Татарстан","Республика Тыва","Удмуртская Республика","Республика Хакасия","Чеченская Республика","Чувашская Республика","Алтайский край","Забайкальский край","Камчатский край","Краснодарский край","Красноярский край","Пермский край","Приморский край","Ставропольский край","Хабаровский край","Амурская область","Архангельская область","Астраханская область","Белгородская область","Брянская область","Владимирская область","Волгоградская область","Вологодская область","Воронежская область","Ивановская область","Иркутская область","Калининградская область","Калужская область","Кемеровская область","Кировская область","Костромская область","Курганская область","Курская область","Ленинградская область","Липецкая область","Магаданская область","Московская область","Мурманская область","Нижегородская область","Новгородская область","Новосибирская область","Омская область","Оренбургская область","Орловская область","Пензенская область","Псковская область","Ростовская область","Рязанская область","Самарская область","Саратовская область","Сахалинская область","Свердловская область","Смоленская область","Тамбовская область","Тверская область","Томская область","Тульская область","Тюменская область","Ульяновская область","Челябинская область","Ярославская область","г. Москва","г. Санкт-Петербург","Еврейская автономная область","Ненецкий автономный округ","Ханты-Мансийский автономный округ - Югра","Чукотский автономный округ","Ямало-Ненецкий автономный округ","Республика Крым","г. Севастополь"]
ALIASES={"кемеровская область - кузбасс":"Кемеровская область","кемеровская область-кузбасс":"Кемеровская область",
"ханты-мансийский автономный округ":"Ханты-Мансийский автономный округ - Югра","ханты-мансийский автономный округ - югра":"Ханты-Мансийский автономный округ - Югра",
"ханты-мансийский ао - югра":"Ханты-Мансийский автономный округ - Югра","хмао - югра":"Ханты-Мансийский автономный округ - Югра",
"ямало-ненецкий ао":"Ямало-Ненецкий автономный округ","ненецкий ао":"Ненецкий автономный округ","чукотский ао":"Чукотский автономный округ",
"чувашская республика - чувашия":"Чувашская Республика","республика северная осетия-алания":"Республика Северная Осетия - Алания",
"республика северная осетия - алания":"Республика Северная Осетия - Алания",
"москва":"г. Москва","г москва":"г. Москва","город москва":"г. Москва",
"санкт-петербург":"г. Санкт-Петербург","г санкт-петербург":"г. Санкт-Петербург","город санкт-петербург":"г. Санкт-Петербург",
"севастополь":"г. Севастополь","г севастополь":"г. Севастополь"}

from functools import lru_cache

@lru_cache(maxsize=250000)
def norm(s):
    q=str(s).replace("ё","е").replace("Ё","Е").replace("–","-").replace("—","-").replace("\xa0"," ")
    q=re.sub(r"[\*¹²³⁴⁵⁶⁷⁸⁹]+"," ",q)
    q=re.sub(r"\bресп\.?\b","республика",q,flags=re.I)
    q=re.sub(r"\bобл\.?\b","область",q,flags=re.I)
    q=re.sub(r"\bавт\.?\s*окр\.?\b|\bао\b","автономный округ",q,flags=re.I)
    q=re.sub(r"\bг\.(?=\s*[А-Яа-я])","г ",q)
    return re.sub(r"\s+"," ",q).strip(" .;:").lower()

RMAP={norm(r):r for r in REGIONS}; RMAP.update({norm(k):v for k,v in ALIASES.items()})
# Для типичных ячеек Росстата сначала точное сопоставление; дорогой поиск подстроки — только для коротких текстов,
# действительно похожих на наименование территории.
REGION_MARKERS=("республика","область","край","округ","москва","петербург","севастополь")
REGION_PATTERNS=[(k,v,re.compile(r"(?<![а-я])"+re.escape(k)+r"(?![а-я])")) for k,v in sorted(RMAP.items(),key=lambda z:len(z[0]),reverse=True) if len(k)>8]

@lru_cache(maxsize=250000)
def region_of(x):
    if x is None:return None
    s=norm(x)
    if not s or len(s)>180:return None
    v=RMAP.get(s)
    if v:return v
    # Большинство числовых/служебных ячеек отсекаются до regex.
    if not any(m in s for m in REGION_MARKERS):return None
    for _,v,pat in REGION_PATTERNS:
        if pat.search(s):return v
    return None

@lru_cache(maxsize=250000)
def year_of(x):
    m=re.search(r"(?<!\d)(19\d{2}|20[0-2]\d)(?!\d)",str(x)); return int(m.group(1)) if m else None

def number(x):
    if pd.isna(x):return np.nan
    if isinstance(x,(int,float,np.integer,np.floating)):
        try:return float(x)
        except:return np.nan
    st=str(x).replace("\xa0","").replace(" ","").replace(",",".").replace("−","-").strip()
    try:return float(st) if re.fullmatch(r"[-+]?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?",st) else np.nan
    except:return np.nan

def semantic_key(s): return re.sub(r"\b(?:19|20)\d{2}\b|\d+|[^а-яa-z]+"," ",norm(s)).strip()[:220]
def good_text(x):
    s=re.sub(r"\s+"," ",str(x)).strip(); letters=len(re.findall(r"[A-Za-zА-Яа-яЁё]",s)); digits=len(re.findall(r"\d",s)); return bool(s) and not region_of(s) and letters>=4 and letters>=digits*.65

# --- Научно контролируемая семантическая классификация ---
# В V3 использовалось простое совпадение слов. Оно давало ложные отнесения:
# «ВРП на душу населения» -> демография; показатели заболеваемости -> демография и т.п.
# V5 сначала учитывает раздел официального сборника, затем — строгие смысловые признаки.

SOCIAL_SUPPORT_KEYS=[
    "социальн поддерж", "социальн помощ", "субсид", "льгот", "пособ",
    "мер социальной поддержки", "материнск капитал"
]
INCOME_KEYS=[
    "реальн доход", "денежн доход", "среднедушев", "заработн плат",
    "назначенн пенс", "бедност", "прожиточн минимум", "джини",
    "потребительск расход", "жилищно-коммунальн"
]
LABOUR_KEYS=[
    "занятост", "безработ", "рабочей силы", "рабочая сила", "рынок труда",
    "среднегодов численност занят", "потребност в работниках"
]
DEMOGRAPHY_KEYS=[
    "численност населения", "естественн прирост", "миграционн прирост",
    "рождаем", "родивш", "смертност", "умерш", "ожидаемая продолжительность жизни",
    "возрастной состав населения", "демографическ нагруз", "брачност", "разводимост",
    "прибывш", "выбывш", "миграц"
]
ECONOMY_KEYS=[
    "валовой региональный продукт", "индекс физического объема", "промышленн производств",
    "индекс производства", "инвестиц", "объем отгруженных товаров", "сельскохозяйственн производств",
    "строительств", "оборот розничной торговли", "грузооборот", "пассажирооборот",
    "обрабатывающ", "добыч полезных ископаемых"
]
EXCLUDE_HEALTH_EDU_CULTURE=[
    "заболеваем", "больничн", "врач", "медицинск персонал", "здравоохран",
    "образован", "обучающ", "студент", "учител", "культур", "музе", "театр",
    "туризм", "спортивн сооруж", "земельн", "угод", "выброс", "сточн вод"
]

def section_of(title,file="",sheet=""):
    q=" | ".join(map(str,[title,Path(file).stem,sheet]))
    m=re.search(r"раздел\s*(\d+)",norm(q))
    return int(m.group(1)) if m else None

def phrase_hit(q,k):
    return all(tok in q for tok in str(k).split())

def has_any(q,keys):
    return any(phrase_hit(q,k) for k in keys)

def block_of(title,source,file="",sheet=""):
    q=norm(" | ".join(map(str,[title,source,Path(file).stem,sheet])))
    sec=section_of(title,file,sheet)

    # Основной сборник: раздел имеет приоритет над случайными словами в названии.
    if source=="regions_app":
        if sec==1: return "demography"
        if sec==2: return "labour"
        if sec==3:
            if has_any(q,SOCIAL_SUPPORT_KEYS): return "social_support"
            if has_any(q,INCOME_KEYS): return "income"
            return "other"
        # Экономико-производственный блок: только содержательно релевантные показатели.
        if sec in {8,9,10,11,12,13,14,15,16} and has_any(q,ECONOMY_KEYS): return "industry"
        # Финансовые расходы на конкретные меры социальной поддержки допускаются отдельно.
        if sec==19 and has_any(q,SOCIAL_SUPPORT_KEYS): return "social_support"
        return "other"

    # Специализированные источники.
    if source in {"natural_movement","migration"}:
        return "demography" if has_any(q,DEMOGRAPHY_KEYS) else "other"
    if source in {"workforce_compendium","labour_compendium"}:
        if has_any(q,LABOUR_KEYS): return "labour"
        if has_any(q,INCOME_KEYS): return "income"
        return "other"
    if source=="sme_compendium":
        return "industry" if has_any(q,tuple(ECONOMY_KEYS) + ("малое","среднее","предприним","оборот","выручк","инвестиц")) else "other"
    if source.startswith(("vndn_","kouzh_","kdu_")) or source in {"living","social_position"}:
        if has_any(q,SOCIAL_SUPPORT_KEYS): return "social_support"
        if has_any(q,LABOUR_KEYS): return "labour"
        if has_any(q,INCOME_KEYS): return "income"
        return "other"
    if source in {"demography","demographic_yearbook"}:
        if has_any(q,EXCLUDE_HEALTH_EDU_CULTURE): return "other"
        return "demography" if has_any(q,DEMOGRAPHY_KEYS) else "other"

    # Последний безопасный слой: никаких общих слов вроде «население» как самостоятельного признака.
    if has_any(q,EXCLUDE_HEALTH_EDU_CULTURE): return "other"
    if has_any(q,SOCIAL_SUPPORT_KEYS): return "social_support"
    if has_any(q,LABOUR_KEYS): return "labour"
    if has_any(q,DEMOGRAPHY_KEYS): return "demography"
    if has_any(q,INCOME_KEYS): return "income"
    if has_any(q,ECONOMY_KEYS): return "industry"
    return "other"

def semantic_reason(title,source,file="",sheet=""):
    sec=section_of(title,file,sheet)
    return f"source={source}; section={sec if sec is not None else 'NA'}; block={block_of(title,source,file,sheet)}"

def title_from_header(a,start,cols,file,sheet):
    texts=[]
    for r in range(max(0,start-15),start):
        for c in sorted(set([0,1,2]+list(cols))):
            if c<a.shape[1] and good_text(a.iat[r,c]):
                s=re.sub(r"\s+"," ",str(a.iat[r,c])).strip()
                if s not in texts:texts.append(s)
    def score(s):
        q=norm(s); return 5*sum(k in q for k in (SOCIAL_SUPPORT_KEYS+INCOME_KEYS+LABOUR_KEYS+DEMOGRAPHY_KEYS+ECONOMY_KEYS))+min(len(re.findall(r"[а-яa-z]",q)),100)/25
    texts=sorted(texts,key=score,reverse=True); base=" | ".join(texts[:4]); context=" | ".join(x for x in [Path(file).stem,str(sheet)] if good_text(x)); return (base+(" | "+context if context else "")).strip(" |")[:800] or context or Path(file).stem

def make_iid(source,title,file,sheet,slot=""):
    f=semantic_key(Path(file).stem); sh=semantic_key(sheet); t=semantic_key(title); return safe(f"{source}_{f}_{sh}_{t}_{slot}")
def consecutive_groups(xs,max_gap=2):
    xs=sorted(xs)
    if not xs:return []
    out=[]; cur=[xs[0]]
    for x in xs[1:]:
        if x-cur[-1]<=max_gap:cur.append(x)
        else:out.append(cur);cur=[x]
    out.append(cur);return out


# ---------------------------------------------------------------------
# V5. Полный, но быстрый парсер: многолетние и годовые матрицы
# ---------------------------------------------------------------------
# Ключевое исправление V5:
# 1) годовая таблица больше не отбрасывается из-за отсутствия 2+ лет внутри файла;
# 2) один и тот же показатель из ежегодных файлов получает стабильный indicator_id,
#    не зависящий от имени файла и года;
# 3) профилирование охватывает весь разумный размер листа, а не только первые 450 строк;
# 4) сохраняются RAW- и CLEAN-панели и подробный аудит неразобранных листов.

PARSE_ROWS=6000
PARSE_COLS=420
PROFILE_ROWS=5000
PROFILE_COLS=300
HEADER_ROWS=180
REGION_SCAN_COLS=40
MIN_REGION_HITS=5
TARGET_YEARS=set(ANALYSIS_YEARS)

GENERIC_TITLES=(
    "социально-экономические показатели по субъектам российской федерации",
    "социально экономические показатели по субъектам российской федерации",
    "субъекты российской федерации",
    "российская федерация",
    "все население",
)

@lru_cache(maxsize=128)
def file_sha_quick(path_str):
    return sha256(Path(path_str))

def _small(df,rows=PARSE_ROWS,cols=PARSE_COLS):
    if df is None or df.empty:
        return pd.DataFrame()
    return df.iloc[:min(len(df),rows),:min(df.shape[1],cols)]

def _clean_title_piece(x):
    s=re.sub(r"\s+"," ",str(x)).strip()
    q=norm(s)
    if not s or not good_text(s): return ""
    if q in GENERIC_TITLES: return ""
    if q.startswith("итоги выборочного наблюдения доходов населения") and len(q)<90: return ""
    if "федеральный округ" in q and len(q)<100: return ""
    return s

def _title_score(s):
    q=norm(s)
    keys=SOCIAL_SUPPORT_KEYS+INCOME_KEYS+LABOUR_KEYS+DEMOGRAPHY_KEYS+ECONOMY_KEYS
    score=8*sum(phrase_hit(q,k) for k in keys)
    score+=3*bool(re.match(r"^\s*\d+(?:\.\d+)+",s))
    score+=min(len(re.findall(r"[а-яa-z]",q)),140)/28
    if q in GENERIC_TITLES: score-=50
    return score

def title_from_header(a,start,cols,file="",sheet=""):
    """Стабильный содержательный заголовок без имени годового файла."""
    texts=[]
    cols0=sorted(set([0,1,2,3]+[c for c in cols if isinstance(c,(int,np.integer)) and c<a.shape[1]]))
    for r in range(max(0,start-24),min(start+1,a.shape[0])):
        for c in cols0:
            if c>=a.shape[1]: continue
            s=_clean_title_piece(a.iat[r,c])
            if s and s not in texts: texts.append(s)
    texts=sorted(texts,key=_title_score,reverse=True)
    base=" | ".join(texts[:5])
    sh=_clean_title_piece(sheet)
    if not base and sh: base=sh
    return base[:900] if base else "Показатель без распознанного заголовка"

def column_header_path(a,start,c,max_up=18,max_left=10):
    """Иерархический заголовок конкретного столбца с восстановлением объединённых ячеек."""
    vals=[]
    for r in range(max(0,start-max_up),start):
        s=_clean_title_piece(a.iat[r,c]) if c<a.shape[1] else ""
        if not s:
            # В Excel подпись объединённой группы физически хранится в левой ячейке.
            for cc in range(c-1,max(-1,c-max_left)-1,-1):
                z=_clean_title_piece(a.iat[r,cc])
                if z:
                    s=z;break
        if s and s not in vals:vals.append(s)
    # Ближайшие к данным уровни заголовка информативнее дальних.
    return " | ".join(vals[-5:])[:800]

def indicator_signature(title):
    q=norm(title)
    q=re.sub(r"\b(?:19|20)\d{2}\b"," ",q)
    q=re.sub(r"\bтаблица\b|\bтабл\.\b"," ",q)
    q=re.sub(r"\s+"," ",q).strip(" |.;:-")
    # Служебные контексты не должны дробить один показатель по годам.
    for g in GENERIC_TITLES:
        q=q.replace(g," ")
    q=re.sub(r"\s+"," ",q).strip()
    return q[:500]

def make_iid(source,title,file="",sheet="",slot=""):
    sig=indicator_signature(title)
    slot_sig=semantic_key(slot)[:80] if slot else ""
    raw=f"{source}|{sig}|{slot_sig}"
    return f"{safe(source)}_{hashlib.sha1(raw.encode('utf-8')).hexdigest()[:16]}"

def is_technical_title(title):
    q=indicator_signature(title)
    if not q or q=="показатель без распознанного заголовка": return True
    letters=len(re.findall(r"[а-яa-z]",q))
    if letters<8:return True
    if q in GENERIC_TITLES:return True
    if q.startswith("социально-экономические показатели по субъектам") and len(q)<110:return True
    return False

def infer_context_year(df,file="",sheet="",source=None,header_rows=None):
    """Год годовой матрицы: только имя/лист и заголовочная зона, без числового тела таблицы."""
    scores={y:0 for y in ANALYSIS_YEARS}
    fs=f"{Path(file).stem} {sheet}"
    for y in ANALYSIS_YEARS:
        if re.search(rf"(?<!\d){y}(?!\d)",fs):scores[y]+=30
    if df is not None and not df.empty:
        stop=min(len(df),header_rows if header_rows is not None else 35)
        a=df.iloc[:max(0,stop),:min(df.shape[1],24)]
        for x in a.to_numpy().ravel():
            if not isinstance(x,str):continue
            sx=str(x)
            for y in ANALYSIS_YEARS:
                if re.search(rf"(?<!\d){y}(?!\d)",sx):
                    scores[y]+=4 if re.search(r"год|г\.",sx,re.I) else 1
    ranked=sorted(scores.items(),key=lambda z:z[1],reverse=True)
    if ranked and ranked[0][1]>0 and (len(ranked)==1 or ranked[0][1]>ranked[1][1]):
        return ranked[0][0]
    dy=SOURCE_DEFAULT_YEAR.get(source) if source else None
    return int(dy) if dy in ANALYSIS_YEARS else None

def is_row_number_vector(vals):
    x=pd.Series(vals).dropna().to_numpy(float)
    if len(x)<6:return False
    r=np.arange(1,len(x)+1,dtype=float)
    return len(x)==len(r) and np.allclose(x,r,rtol=0,atol=1e-9)

def sheet_profile(df):
    """Один дешёвый проход определяет ориентацию; сканирование шире V4."""
    if df is None or df.empty:return {"mode":"skip","reason":"empty","row_col":None,"header_row":None}
    a=df.iloc[:min(len(df),PROFILE_ROWS),:min(df.shape[1],PROFILE_COLS)]
    nr,nc=a.shape
    row_best=(0,None)
    for c in range(min(nc,REGION_SCAN_COLS)):
        n=sum(region_of(x) is not None for x in a.iloc[:,c].tolist())
        if n>row_best[0]:row_best=(n,c)
    col_best=(0,None)
    for r in range(min(nr,HEADER_ROWS)):
        n=sum(region_of(x) is not None for x in a.iloc[r,:].tolist())
        if n>col_best[0]:col_best=(n,r)
    if row_best[0]>=MIN_REGION_HITS and row_best[0]>=col_best[0]:
        return {"mode":"rows","reason":f"region_rows={row_best[0]}","row_col":row_best[1],"header_row":None}
    if col_best[0]>=MIN_REGION_HITS:
        return {"mode":"columns","reason":f"region_cols={col_best[0]}","row_col":None,"header_row":col_best[1]}
    # Последняя попытка: регион может находиться дальше 40-го столбца.
    for c in range(nc):
        n=sum(region_of(x) is not None for x in a.iloc[:,c].tolist())
        if n>=MIN_REGION_HITS:return {"mode":"long","reason":f"long_region={n}","row_col":c,"header_row":None}
    return {"mode":"skip","reason":f"no_regions(max={max(row_best[0],col_best[0])})","row_col":None,"header_row":None}

def _year_columns_from_header(a,st):
    ycols=[]
    head=a.iloc[max(0,st-28):st,:]
    for c in range(a.shape[1]):
        ys=[year_of(x) for x in head.iloc[:,c].tolist()]
        ys=[y for y in ys if y in TARGET_YEARS]
        if ys:ycols.append((c,ys[-1]))
    return ycols

def parse_region_rows(df,source,file,sheet,rc_hint=None):
    a=_small(df); out=[]
    if a.empty:return out
    if rc_hint is None:
        cand=[]
        for c in range(min(a.shape[1],REGION_SCAN_COLS)):
            hits=[r for r,x in enumerate(a.iloc[:,c].tolist()) if region_of(x)]
            if len(hits)>=MIN_REGION_HITS:cand.append((len(hits),c,hits))
        if not cand:return out
        _,rc,hits=max(cand)
    else:
        rc=int(rc_hint); hits=[r for r,x in enumerate(a.iloc[:,rc].tolist()) if region_of(x)]
        if len(hits)<MIN_REGION_HITS:return out

    context_year=None
    for gi,rows0 in enumerate(consecutive_groups(hits,3)):
        if len(rows0)<MIN_REGION_HITS:continue
        st=min(rows0); context_year=infer_context_year(a,file,sheet,source,header_rows=st); ycols=_year_columns_from_header(a,st)

        # A. Настоящая многолетняя таблица.
        byyear={}
        for c,y in ycols: byyear.setdefault(y,[]).append(c)
        if len(byyear)>=2:
            # Разбиваем на локальные последовательности лет/столбцов.
            runs=[];cur=[];last_c=None;last_y=None
            for c,y in sorted(ycols):
                # Новый блок показателя обычно начинается, когда последовательность лет сбрасывается
                # или между колонками возникает заметный разрыв.
                if cur and (c-last_c>4 or (last_y is not None and y<=last_y)):
                    runs.append(cur);cur=[]
                cur.append((c,y));last_c=c;last_y=y
            if cur:runs.append(cur)
            for ri,run in enumerate(runs):
                if len(set(y for _,y in run))<2:continue
                cols=[c for c,_ in run]
                title=title_from_header(a,st,cols,file,sheet)
                iid=make_iid(source,title,slot=f"multi_{ri}")
                for r in rows0:
                    reg=region_of(a.iat[r,rc])
                    if not reg:continue
                    for c,y in run:
                        v=number(a.iat[r,c])
                        if pd.notna(v):out.append((reg,y,v,iid,title,source,file,sheet))
            continue

        # B. Годовая матрица: один файл/лист = один год, столбцы = разные показатели.
        single_year=(next(iter(byyear)) if len(byyear)==1 else context_year)
        if single_year not in TARGET_YEARS:continue
        # В годовой матрице один заголовок года нередко объединён над несколькими колонками.
        # Поэтому проверяем все колонки и отбираем их уже по фактическому числовому покрытию.
        candidate_cols=[c for c in range(a.shape[1]) if c!=rc]
        for c in candidate_cols:
            vals=[number(a.iat[r,c]) for r in rows0]
            valid=[v for v in vals if pd.notna(v)]
            if len(valid)<max(MIN_REGION_HITS,int(.30*len(rows0))):continue
            if is_row_number_vector(valid):continue
            global_title=title_from_header(a,st,[c],file,sheet)
            specific=column_header_path(a,st,c)
            title=(specific+" | "+global_title if specific and specific not in global_title else (specific or global_title))[:900]
            slot=specific if specific else f"col_{c}"
            iid=make_iid(source,title,slot=slot)
            for r,v in zip(rows0,vals):
                reg=region_of(a.iat[r,rc])
                if reg and pd.notna(v):out.append((reg,single_year,float(v),iid,title,source,file,sheet))
    return out

def parse_region_columns(df,source,file,sheet,hr_hint=None):
    a=_small(df); out=[]
    if a.empty:return out
    if hr_hint is None:
        headers=[]
        for r in range(min(a.shape[0],HEADER_ROWS)):
            cols=[c for c,x in enumerate(a.iloc[r,:].tolist()) if region_of(x)]
            if len(cols)>=MIN_REGION_HITS:headers.append((len(cols),r,cols))
        if not headers:return out
        _,hr,cols=max(headers)
    else:
        hr=int(hr_hint); cols=[c for c,x in enumerate(a.iloc[hr,:].tolist()) if region_of(x)]
        if len(cols)<MIN_REGION_HITS:return out

    left=min(14,a.shape[1]); year_rows=[]
    for r in range(hr+1,a.shape[0]):
        ys=[year_of(x) for x in a.iloc[r,:left].tolist()]
        yy=next((y for y in ys if y in TARGET_YEARS),None)
        if yy:year_rows.append((r,yy))

    # A. Несколько лет внутри таблицы.
    if len(set(y for _,y in year_rows))>=2:
        for gi,grp in enumerate(consecutive_groups([r for r,_ in year_rows],2)):
            pairs=[(r,y) for r,y in year_rows if r in grp]
            if len(set(y for _,y in pairs))<2:continue
            title=title_from_header(a,min(grp),list(range(left)),file,sheet)
            iid=make_iid(source,title,slot=f"rowblock_{gi}")
            for r,y in pairs:
                for c in cols:
                    reg=region_of(a.iat[hr,c]); v=number(a.iat[r,c])
                    if reg and pd.notna(v):out.append((reg,y,v,iid,title,source,file,sheet))
        return out

    # B. Годовая матрица: строки = разные показатели, колонки = регионы.
    single_year=(year_rows[0][1] if year_rows else infer_context_year(a,file,sheet,source,header_rows=hr+1))
    if single_year not in TARGET_YEARS:return out
    start=hr+1
    for r in range(start,a.shape[0]):
        vals=[number(a.iat[r,c]) for c in cols]
        valid=[v for v in vals if pd.notna(v)]
        if len(valid)<max(MIN_REGION_HITS,int(.30*len(cols))):continue
        left_texts=[]
        for c in range(min(left,8)):
            s=_clean_title_piece(a.iat[r,c])
            if s:left_texts.append(s)
        if not left_texts:continue
        title=" | ".join(dict.fromkeys(left_texts))[:900]
        iid=make_iid(source,title,slot=title)
        for c,v in zip(cols,vals):
            reg=region_of(a.iat[hr,c])
            if reg and pd.notna(v):out.append((reg,single_year,float(v),iid,title,source,file,sheet))
    return out

def parse_long(df,source,file,sheet,rc_hint=None):
    """Длинный формат. Использует позиции столбцов — устойчив к повторяющимся заголовкам."""
    if df is None or df.empty:return []
    a=_small(df); ncol=a.shape[1]
    if rc_hint is not None and isinstance(rc_hint,(int,np.integer)) and int(rc_hint)<ncol:
        rc_pos=int(rc_hint)
    else:
        scores=[]
        for j in range(ncol):
            s=a.iloc[:,j]
            scores.append((sum(region_of(x) is not None for x in s.tolist()),j))
        rh,rc_pos=max(scores,default=(0,None))
        if rh<MIN_REGION_HITS:return []
    yc_pos=None;yscore=0
    for j in range(ncol):
        if j==rc_pos:continue
        s=a.iloc[:,j]
        n=sum(year_of(x) in TARGET_YEARS for x in s.tolist())
        if n>yscore:yscore,yc_pos=n,j
    # Годовой файл не обязан иметь отдельный столбец года.
    if yscore<MIN_REGION_HITS:yc_pos=None
    context_year=infer_context_year(a,file,sheet,source,header_rows=min(25,len(a)))
    out=[]
    for j in range(ncol):
        if j in {rc_pos,yc_pos}:continue
        ser=a.iloc[:,j]
        vals=pd.to_numeric(ser,errors="coerce")
        if vals.notna().sum()<MIN_REGION_HITS:continue
        label=str(a.columns[j])
        title=label if good_text(label) else title_from_header(a,0,[j],file,sheet)
        label_dups=sum(str(x)==label for x in list(a.columns))
        slot=(f"{label}|col_{j}" if label_dups>1 else label) if good_text(label) else f"col_{j}"
        iid=make_iid(source,title,slot=slot)
        for i,v in vals[vals.notna()].items():
            reg=region_of(a.iat[i,rc_pos])
            y=year_of(a.iat[i,yc_pos]) if yc_pos is not None else context_year
            if reg and y in TARGET_YEARS:out.append((reg,y,float(v),iid,title,source,file,sheet))
    return out

def read_tables(p):
    """Чтение файла один раз: Excel -> CSV -> HTML. CSV не использует несовместимый low_memory с python engine."""
    suf=p.suffix.lower()
    if suf==".csv":
        raw=p.read_bytes()
        for enc in ("utf-8-sig","utf-8","cp1251","latin1"):
            try:
                txt=raw.decode(enc)
                df=pd.read_csv(io.StringIO(txt),sep=None,engine="python",header=None,on_bad_lines="skip")
                if not df.empty:return {"CSV":df}
            except Exception:pass
        return {}
    if suf in {".html",".htm"}:
        try:
            tabs=pd.read_html(str(p),header=None,displayed_only=False)
            return {f"HTML_{i+1}":d for i,d in enumerate(tabs) if d is not None and not d.empty}
        except Exception:return {}
    if suf in {".xlsx",".xls"}:
        try:return pd.read_excel(p,sheet_name=None,header=None,engine="calamine")
        except Exception:
            eng="openpyxl" if suf==".xlsx" else "xlrd"
            return pd.read_excel(p,sheet_name=None,header=None,engine=eng)
    return {}

panel_cache=PROCESSED/"panel_long.parquet"
raw_cache=PROCESSED/"panel_raw.parquet"
parse_cache=PROCESSED/"table_parse_audit.csv"

if panel_cache.exists() and parse_cache.exists() and not FORCE_PARSE:
    PANEL=pd.read_parquet(panel_cache)
    PANEL_RAW=pd.read_parquet(raw_cache) if raw_cache.exists() else PANEL.copy()
    clean_cache=PROCESSED/"panel_clean.parquet"
    PANEL_CLEAN=pd.read_parquet(clean_cache) if clean_cache.exists() else PANEL.copy()
    TABLE_INDEX=pd.read_csv(parse_cache)
    coll_path=PROCESSED/"indicator_id_collision_audit.csv"
    series_path=PROCESSED/"series_dedup_audit.csv"
    META_COLLISIONS=pd.read_csv(coll_path) if coll_path.exists() else pd.DataFrame()
    SERIES_META=pd.read_csv(series_path) if series_path.exists() else pd.DataFrame()
else:
    rows=[]; audit=[]
    all_files=sorted(
        p for p in EXTRACT.rglob("*")
        if p.is_file() and p.suffix.lower() in TABLE_EXT and valid_table_file(p)
    )
    seen_hash={}; files=[]
    for p in pbar(all_files,desc="2A/5 ХЭШИ И ДУБЛИ",unit="файл",leave=True):
        try:h=file_sha_quick(str(p))
        except Exception:h=f"path:{p}"
        if h in seen_hash:
            audit.append({
                "source":p.relative_to(EXTRACT).parts[0],"file":str(p),"parsed_rows":0,"ok":False,
                "mode":"duplicate_file","sheets":0,"parsed_sheets":0,"seconds":0.0,
                "note":f"duplicate_of={seen_hash[h]}"
            })
            continue
        seen_hash[h]=str(p); files.append(p)

    files=sorted(files,key=lambda p:(0 if "regions_app" in p.parts else 1,str(p)))
    bar=pbar(files,desc="2B/5 РАЗБОР ТАБЛИЦ",unit="файл",leave=True)
    for p in bar:
        t0=time.time(); rel=p.relative_to(EXTRACT); src=rel.parts[0]; n0=len(rows)
        _read_sec=0.0; _parse_sec=0.0
        notes=[]; modes=[]; nsh=0; parsed_sheets=0; sheet_details=[]
        try:
            _read_t0=time.perf_counter(); tabs=read_tables(p); _read_sec=time.perf_counter()-_read_t0
            _parse_t0=time.perf_counter()
            for sh,d in tabs.items():
                bar.set_postfix(src=src,sheet=str(sh)[:18],rows=len(rows)-n0)
                nsh+=1
                prof=sheet_profile(d); mode=prof["mode"]; modes.append(mode)
                if mode=="skip":
                    sheet_details.append(f"{sh}:skip:{prof['reason']}")
                    continue
                got=[]
                try:
                    if mode=="rows":
                        got=parse_region_rows(d,src,str(p),str(sh),prof.get("row_col"))
                    elif mode=="columns":
                        got=parse_region_columns(d,src,str(p),str(sh),prof.get("header_row"))
                    else:
                        got=parse_long(d,src,str(p),str(sh),prof.get("row_col"))
                except Exception as e:
                    notes.append(f"{sh}:{type(e).__name__}:{str(e)[:90]}")

                # Универсальный fallback: до пяти вариантов строки заголовка, но без повторного
                # brute-force сканирования всего файла.
                if not got:
                    try:
                        for h in range(min(5,max(0,len(d)-1))):
                            z=d.iloc[h+1:].copy()
                            z.columns=[str(x) for x in d.iloc[h]]
                            q=parse_long(z.reset_index(drop=True),src,str(p),str(sh))
                            if q:
                                got=q; modes.append("long_fallback"); break
                    except Exception as e:
                        notes.append(f"{sh}:fallback:{type(e).__name__}:{str(e)[:70]}")
                if got:
                    parsed_sheets+=1; rows.extend(got)
                    sheet_details.append(f"{sh}:{mode}:{len(got)}")
                else:
                    sheet_details.append(f"{sh}:{mode}:0")
            _parse_sec=time.perf_counter()-_parse_t0; sec=time.time()-t0
            if sec>SLOW_PARSE_WARN_SEC: notes.append(f"SLOW_FILE>{SLOW_PARSE_WARN_SEC:.0f}s")
            audit.append({
                "source":src,"file":str(p),"parsed_rows":len(rows)-n0,"ok":len(rows)>n0,
                "mode":"/".join(sorted(set(modes))),"sheets":nsh,"parsed_sheets":parsed_sheets,
                "read_seconds":round(_read_sec,3),"parse_seconds":round(_parse_sec,3),"seconds":round(sec,3),
                "note":" | ".join((notes+sheet_details)[-8:])
            })
            bar.set_postfix(src=src,sheets=nsh,rows=len(rows)-n0,sec=f"{sec:.1f}")
        except Exception as e:
            sec=time.time()-t0
            audit.append({
                "source":src,"file":str(p),"parsed_rows":0,"ok":False,"mode":"error",
                "sheets":nsh,"parsed_sheets":parsed_sheets,"read_seconds":round(locals().get("_read_sec",0.0),3),
                "parse_seconds":round(max(0.0,sec-locals().get("_read_sec",0.0)),3),"seconds":round(sec,3),
                "note":f"{type(e).__name__}: {str(e)[:250]}"
            })

    bar.close()
    TABLE_INDEX=pd.DataFrame(audit)
    PANEL_RAW=pd.DataFrame(rows,columns=["region","year","value","indicator_id","indicator","source","file","sheet"])
    if PANEL_RAW.empty:raise RuntimeError("Ни одна таблица не преобразована в региональную панель.")

    PANEL_RAW=PANEL_RAW[
        PANEL_RAW["year"].isin(ANALYSIS_YEARS) & PANEL_RAW["region"].isin(REGIONS)
    ].drop_duplicates(["region","year","indicator_id","value","source","file","sheet"])
    PANEL_RAW["block"]=[
        block_of(i,s0,f,sh)
        for i,s0,f,sh in PANEL_RAW[["indicator","source","file","sheet"]].itertuples(index=False,name=None)
    ]
    PANEL_RAW["technical_title"]=PANEL_RAW["indicator"].map(is_technical_title)

    # --- Канонизация метаданных indicator_id ---
    def _canon_title(vals):
        uniq=list(dict.fromkeys(str(x) for x in vals if str(x).strip()))
        if not uniq:return "Показатель без распознанного заголовка"
        def q(s):
            return (_title_score(s), -len(indicator_signature(s)), -len(s))
        return max(uniq,key=q)
    META_COLLISIONS=PANEL_RAW.groupby("indicator_id").agg(
        title_variants=("indicator","nunique"),block_variants=("block","nunique"),
        source_variants=("source","nunique"),rows=("value","size")
    ).reset_index()
    CANON_TITLE=PANEL_RAW.groupby("indicator_id")["indicator"].agg(_canon_title).to_dict()
    CANON_BLOCK=PANEL_RAW.groupby("indicator_id")["block"].agg(lambda s:s.mode().iat[0] if not s.mode().empty else s.iloc[0]).to_dict()
    CANON_SOURCE=PANEL_RAW.groupby("indicator_id")["source"].agg(lambda s:s.mode().iat[0] if not s.mode().empty else s.iloc[0]).to_dict()
    PANEL_RAW["indicator"]=PANEL_RAW["indicator_id"].map(CANON_TITLE)
    PANEL_RAW["block"]=PANEL_RAW["indicator_id"].map(CANON_BLOCK)
    PANEL_RAW["source"]=PANEL_RAW["indicator_id"].map(CANON_SOURCE)
    PANEL_RAW["technical_title"]=PANEL_RAW["indicator"].map(is_technical_title)

    # CLEAN хранит все содержательные показатели, но уже один показатель = один canonical id/title.
    PANEL_CLEAN=PANEL_RAW[~PANEL_RAW["technical_title"]].copy()
    PANEL_CLEAN=PANEL_CLEAN.groupby(
        ["region","year","indicator_id","indicator","block","source"],as_index=False
    ).agg(value=("value","median"))

    # V5.6: полная очищенная база сохраняется целиком, но модель получает только
    # заранее разрешённые источники. Это не удаляет дополнительную эмпирику.
    PANEL_MODEL_SOURCE=PANEL_CLEAN[PANEL_CLEAN["source"].isin(MODEL_ELIGIBLE_SOURCES)].copy()

    # Точные дубли рядов сохраняются в аудите, но в аналитической панели оставляется один представитель.
    def _series_hash_frame(g):
        q=g[["region","year","value"]].sort_values(["region","year"])
        txt="\n".join(f"{r}|{int(y)}|{float(v):.12g}" for r,y,v in q.itertuples(index=False,name=None))
        return hashlib.sha1(txt.encode("utf-8")).hexdigest()
    SERIES_META=PANEL_MODEL_SOURCE.groupby("indicator_id",sort=False).apply(_series_hash_frame).rename("series_hash").reset_index()
    cc=PANEL_MODEL_SOURCE.groupby("indicator_id").agg(
        indicator=("indicator","first"),block=("block","first"),source=("source","first"),
        regions=("region","nunique"),years=("year","nunique"),obs=("value","size")
    ).reset_index()
    SERIES_META=SERIES_META.merge(cc,on="indicator_id",how="left")
    priority={"regions_app":0,"natural_movement":1,"migration":2,"demographic_yearbook":3,
              "workforce_compendium":4,"labour_compendium":5,"living":6,
              "social_position":7,"sme_compendium":8,"demography":20}
    SERIES_META["source_priority"]=SERIES_META["source"].map(
        lambda s:9 if str(s).startswith("vndn_") else priority.get(s,15)
    )
    SERIES_META["title_quality"]=SERIES_META["indicator"].map(_title_score)
    SERIES_META=SERIES_META.sort_values(
        ["series_hash","years","regions","title_quality","source_priority"],
        ascending=[True,False,False,False,True]
    )
    SERIES_META["duplicate_rank"]=SERIES_META.groupby("series_hash").cumcount()
    SERIES_META["keep_for_model"]=SERIES_META["duplicate_rank"].eq(0)
    keep_ids=set(SERIES_META.loc[SERIES_META["keep_for_model"],"indicator_id"])
    PANEL=PANEL_MODEL_SOURCE[PANEL_MODEL_SOURCE["indicator_id"].isin(keep_ids)].copy()

    PANEL_RAW.to_parquet(raw_cache,index=False)
    PANEL_CLEAN.to_parquet(PROCESSED/"panel_clean.parquet",index=False)
    PANEL.to_parquet(panel_cache,index=False)
    META_COLLISIONS.to_csv(PROCESSED/"indicator_id_collision_audit.csv",index=False)
    SERIES_META.to_csv(PROCESSED/"series_dedup_audit.csv",index=False)
    TABLE_INDEX.to_csv(parse_cache,index=False)

# Комплектность рядов
cov=PANEL.groupby(["indicator_id","indicator","block","source"]).agg(
    regions=("region","nunique"),years=("year","nunique"),obs=("value","size"),
    min_year=("year","min"),max_year=("year","max")
).reset_index()
cov["coverage"]=cov["obs"]/(len(REGIONS)*len(ANALYSIS_YEARS))
cov["full_7y"]=cov["years"].eq(len(ANALYSIS_YEARS))
cov["regions_80plus"]=cov["regions"].ge(80)
cov["research_grade"]=cov["full_7y"] & cov["regions_80plus"]
cov.to_csv(PROCESSED/"indicator_coverage.csv",index=False)

SRC_CLEAN=PANEL_CLEAN.groupby("source").agg(
    rows=("value","size"),regions=("region","nunique"),
    indicators=("indicator_id","nunique"),years=("year","nunique")
).reset_index()
SRC=PANEL.groupby("source").agg(
    rows=("value","size"),regions=("region","nunique"),
    indicators=("indicator_id","nunique"),years=("year","nunique")
).reset_index()

BLK=cov.groupby("block").agg(
    indicators=("indicator_id","nunique"),
    max_regions=("regions","max"),
    max_years=("years","max"),
    research_grade=("research_grade","sum")
).reset_index().sort_values(["research_grade","indicators"],ascending=False)

SEMANTIC_AUDIT=PANEL[["indicator_id","indicator","block","source"]].drop_duplicates().copy()
SEMANTIC_AUDIT["section"]=SEMANTIC_AUDIT["indicator"].map(lambda s: section_of(s))
SEMANTIC_AUDIT["reason"]=SEMANTIC_AUDIT.apply(
    lambda r: semantic_reason(r["indicator"],r["source"]),axis=1
)
SEMANTIC_AUDIT.to_csv(PROCESSED/"semantic_classification_audit.csv",index=False)

TECHNICAL_AUDIT=PANEL_RAW[PANEL_RAW["technical_title"]][
    ["indicator_id","indicator","source","file","sheet"]
].drop_duplicates()
TECHNICAL_AUDIT.to_csv(PROCESSED/"technical_title_audit.csv",index=False)

dup_hashes=set(SERIES_META.loc[SERIES_META.groupby("series_hash")["indicator_id"].transform("size").gt(1),"series_hash"]) if not SERIES_META.empty else set()
DUP_SERIES=SERIES_META[SERIES_META["series_hash"].isin(dup_hashes)].copy() if dup_hashes else pd.DataFrame(columns=SERIES_META.columns if not SERIES_META.empty else [])
DUP_SERIES.to_csv(PROCESSED/"duplicate_series_audit.csv",index=False)

timing_end("02_full_table_parser",_STAGE2_T0,detail=f"raw={len(PANEL_RAW):,}; clean={len(PANEL_CLEAN):,}; model={len(PANEL):,}; indicators={PANEL['indicator_id'].nunique()}")
print("Панель CLEAN:",PANEL_CLEAN.shape,"| аналитическая после точных дублей:",PANEL.shape,"| регионы:",PANEL["region"].nunique(),
      "| показатели:",PANEL["indicator_id"].nunique(),"| годы:",PANEL["year"].nunique())
display(SRC)
display(BLK)
display(cov.sort_values(["research_grade","coverage","regions","years"],ascending=False).head(50))
if "seconds" in TABLE_INDEX.columns and (TABLE_INDEX["seconds"]>0).any():
    timed=TABLE_INDEX.loc[TABLE_INDEX["seconds"]>0,"seconds"]
    print("Скорость: медиана",round(timed.median(),2),"с/файл; p95",round(timed.quantile(.95),2),"с/файл")
    display(TABLE_INDEX.sort_values("seconds",ascending=False).head(20))

pipeline_done("parser","таблицы разобраны")

▶ 02_full_table_parser

2A/5 ХЭШИ И ДУБЛИ:   0%|                            | 0/1675 [00:00<?, ?файл/s]

2B/5 РАЗБОР ТАБЛИЦ:   0%|                            | 0/1584 [00:00<?, ?файл/s]

✓ 02_full_table_parser: 20 мин 13 с | raw=2,853,784; clean=973,357; model=876,243; indicators=4596
Панель CLEAN: (973357, 7) | аналитическая после точных дублей: (876243, 7) | регионы: 85 | показатели: 4596 | годы: 7

                  source    rows  regions  indicators  years
0   demographic_yearbook   36535       85         198      7
1      labour_compendium   60855       85         435      7
2                 living   69651       85         515      7
3              migration  138052       85         661      7
4       natural_movement   39582       85         281      7
5            regions_app  238027       85         450      7
6         sme_compendium   55133       85         217      7
7        social_position  169057       85        1100      7
8              vndn_2020    5625       75          75      3
9              vndn_2021    6075       75          81      2
10             vndn_2022    5850       75          78      2
11             vndn_2023    5850       75          78      2
12             vndn_2024    6225       75          83      2
13  workforce_compendium   39726       80         344      7

            block  indicators  max_regions  max_years  research_grade
4           other        1731           85          7             252
2        industry         197           85          7              46
0      demography         996           85          7              34
3          labour         508           85          7              24
1          income         546           85          7              18
5  social_support         618           85          7               7

,indicator_id,indicator,block,source,regions,years,obs,min_year,max_year,coverage,full_7y,regions_80plus,research_grade
77,demographic_yearbook_62a7b37f3b86e054,1.1. Население субъектов Российской Федерации ...,other,demographic_yearbook,85,7,595,2017,2023,1.0,True,True,True
117,demographic_yearbook_98862ab6bf606f0b,1.2. Городское население субъектов Российской ...,other,demographic_yearbook,85,7,595,2017,2023,1.0,True,True,True
1181,migration_094b74da548e4829,1.14. Прирост (убыль) численности участников Г...,other,migration,85,7,595,2017,2023,1.0,True,True,True
2090,regions_app_008d5e21e9f2f505,2.6. УРОВЕНЬ ЗАНЯТОСТИ НАСЕЛЕНИЯ В ТРУДОСПОСОБ...,labour,regions_app,85,7,595,2017,2023,1.0,True,True,True
2095,regions_app_025518509f86871a,20.6. ИНДЕКСЫ ПОТРЕБИТЕЛЬСКИХ ЦЕН (ТАРИФОВ) НА...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2096,regions_app_025eb2c1e5e6eda3,4.3. ОБЕСПЕЧЕННОСТЬ ДЕТЕЙ ДОШКОЛЬНОГО ВОЗРАСТА...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2098,regions_app_02f9371e2c41a551,20.5. ИНДЕКСЫ ПОТРЕБИТЕЛЬСКИХ ЦЕН НА НЕПРОДОВО...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2102,regions_app_03c881300592d504,ЖИЛИЩНОЕ И СОЦИАЛЬНО-КУЛЬТУРНОЕ СТРОИТЕЛЬСТВО ...,industry,regions_app,85,7,595,2017,2023,1.0,True,True,True
2104,regions_app_04b910d43ceef521,11.5. КРЕДИТОРСКАЯ ЗАДОЛЖЕННОСТЬ ОРГАНИЗАЦИЙ1)...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2107,regions_app_075bbc839a2ac70e,16.9. ПЛОТНОСТЬ АВТОМОБИЛЬНЫХ ДОРОГ ОБЩЕГО ПОЛ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2109,regions_app_099e03ab488b4dc8,1.3. УДЕЛЬНЫЙ ВЕС ГОРОДСКОГО НАСЕЛЕНИЯ В ОБЩЕЙ...,demography,regions_app,85,7,595,2017,2023,1.0,True,True,True
2111,regions_app_0afaa8192d7fb483,"4.4. ЧИСЛЕННОСТЬ УЧИТЕЛЕЙ ОРГАНИЗАЦИЙ, ОСУЩЕСТ...",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2112,regions_app_0b5ef2c6ed3fabf1,"3.26.4. Удельный вес семей, получивших жилые п...",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2113,regions_app_0c3353cb53c8d570,"14.1. ОБЪЕМ РАБОТ, ВЫПОЛНЕННЫХ ПО ВИДУ ЭКОНОМИ...",industry,regions_app,85,7,595,2017,2023,1.0,True,True,True
2115,regions_app_0cbe646eaae59ae9,"5.9.3. Болезни крови, кроветворных органов и о...",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2116,regions_app_0ccfcb4f172d7229,16.8. УДЕЛЬНЫЙ ВЕС АВТОМОБИЛЬНЫХ ДОРОГ С УСОВЕ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2120,regions_app_0efb155a5d80f8c8,"7.1.3. Поверхностные воды, включая болота | 7....",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2121,regions_app_1022c6fe3b3e6c1d,3.1. РЕАЛЬНЫЕ ДЕНЕЖНЫЕ ДОХОДЫ | 3.1.3. Реальны...,income,regions_app,85,7,595,2017,2023,1.0,True,True,True
2122,regions_app_103dde9bb511c833,ЖИЛИЩНОЕ И СОЦИАЛЬНО-КУЛЬТУРНОЕ СТРОИТЕЛЬСТВО ...,industry,regions_app,85,7,595,2017,2023,1.0,True,True,True
2124,regions_app_10741e0474ba395c,5.5.1. Численность населения на одного врача1)...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2125,regions_app_11b0e92b67c10385,19.11. ДЕПОЗИТЫ (ВКЛАДЫ) ЮРИДИЧЕСКИХ И ФИЗИЧЕС...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2126,regions_app_11e5cd49365124f2,19.10. ДЕПОЗИТЫ (ВКЛАДЫ) ЮРИДИЧЕСКИХ И ФИЗИЧЕС...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2128,regions_app_14d77c22c6b4dbd2,РАСПРЕДЕЛЕНИЕ ЧИСЛА ВЫБЫВШИХ ПО НАПРАВЛЕНИЯМ П...,demography,regions_app,85,7,595,2017,2023,1.0,True,True,True
2131,regions_app_16bf203c41330b42,11.5. КРЕДИТОРСКАЯ ЗАДОЛЖЕННОСТЬ ОРГАНИЗАЦИЙ1)...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2132,regions_app_179832ef51218e57,3.29. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СОЦИАЛЬНОЙ ПОДД...,social_support,regions_app,85,7,595,2017,2023,1.0,True,True,True
2134,regions_app_197f76fca62f63a4,"5.9.15. Травмы, отравления и некоторые другие ...",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2136,regions_app_1ad7044554d89926,5.9. ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2137,regions_app_1af4fcd96543f50f,ДЕНЕЖНЫЕ ДОХОДЫ НАСЕЛЕНИЯ | 3.8. ЧИСЛЕННОСТЬ З...,income,regions_app,85,7,595,2017,2023,1.0,True,True,True
2138,regions_app_1b1d7a56763c0871,3.24. ЖИЛИЩНЫЙ ФОНД1) | 3.24.1. Всего | (общая...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2142,regions_app_1e3f770f1bae5cca,5.1. ЧИСЛО БОЛЬНИЧНЫХ КОЕК1) | 5.1.2. На 10000...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2146,regions_app_1f61239539e8ac30,3.2. СРЕДНЕДУШЕВЫЕ ДЕНЕЖНЫЕ ДОХОДЫ НАСЕЛЕНИЯ1)...,income,regions_app,85,7,595,2017,2023,1.0,True,True,True
2147,regions_app_2031c9d242739c80,8. ВАЛОВОЙ РЕГИОНАЛЬНЫЙ ПРОДУКТ | 8.4. ФАКТИЧЕ...,industry,regions_app,85,7,595,2017,2023,1.0,True,True,True
2148,regions_app_211ec99badb6e580,8. ВАЛОВОЙ РЕГИОНАЛЬНЫЙ ПРОДУКТ | 8.4. ФАКТИЧЕ...,industry,regions_app,85,7,595,2017,2023,1.0,True,True,True
2152,regions_app_22c0fca769563e22,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.1. ЧИСЛЕННОСТЬ РАБ...,labour,regions_app,85,7,595,2017,2023,1.0,True,True,True
2153,regions_app_22e09914eba27c4a,(по данным выборочного обследования населения ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2158,regions_app_25b86231c66c8216,5.9. ЗАБОЛЕВАЕМОСТЬ на 1000 человек населения ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2159,regions_app_275a4cfd0b7f5c29,17.6. ИСПОЛЬЗОВАНИЕ КОМПЬЮТЕРОВ И СЕТИ ИНТЕРНЕ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2163,regions_app_29b70a12dd623ab1,5.5.2. Численность населения на одного работни...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2165,regions_app_2a60319f2ec689b1,5.6. ЧИСЛЕННОСТЬ СРЕДНЕГО МЕДИЦИНСКОГО ПЕРСОНА...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2170,regions_app_2c3ef88d9f1c805f,1.19. СООТНОШЕНИЕ БРАКОВ И РАЗВОДОВ1) | (на 10...,demography,regions_app,85,7,595,2017,2023,1.0,True,True,True
2172,regions_app_2c64b704beedeaca,3.28. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СУБСИДИЙ НА ОПЛ...,social_support,regions_app,85,7,595,2017,2023,1.0,True,True,True
2177,regions_app_2fb0bd20f1bbe199,РАСПРЕДЕЛЕНИЕ ЧИСЛА ПРИБЫВШИХ ПО НАПРАВЛЕНИЯМ ...,demography,regions_app,85,7,595,2017,2023,1.0,True,True,True
2184,regions_app_33ca7cae564d9ae3,6.7.1. Число коллективных средств размещения |...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2188,regions_app_33f299a8f8d0515a,"3.25. ОБЩАЯ ПЛОЩАДЬ ЖИЛЫХ ПОМЕЩЕНИЙ, ПРИХОДЯЩА...",other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2190,regions_app_34a46cae16e0e6c9,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.8. ЧИСЛЕННОСТЬ ЗАР...,labour,regions_app,85,7,595,2017,2023,1.0,True,True,True
2191,regions_app_34b2f0ab9f17f8f2,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.5. УРОВЕНЬ ЗАНЯТОС...,labour,regions_app,85,7,595,2017,2023,1.0,True,True,True
2192,regions_app_3594daa06faa919e,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.7. ЧИСЛЕННОСТЬ БЕЗ...,labour,regions_app,85,7,595,2017,2023,1.0,True,True,True
2197,regions_app_384454646c169662,1.15. СУММАРНЫЙ КОЭФФИЦИЕНТ РОЖДАЕМОСТИ | (чис...,demography,regions_app,85,7,595,2017,2023,1.0,True,True,True
2201,regions_app_3a15e903fbc1977f,17.3. ИСПОЛЬЗОВАНИЕ ШИРОКОПОЛОСНОГО ДОСТУПА К ...,other,regions_app,85,7,595,2017,2023,1.0,True,True,True
2203,regions_app_3c0f833f0496436e,ЖИЛИЩНОЕ И СОЦИАЛЬНО-КУЛЬТУРНОЕ СТРОИТЕЛЬСТВО ...,industry,regions_app,85,7,595,2017,2023,1.0,True,True,True

Скорость: медиана 0.08 с/файл; p95 1.05 с/файл

,source,file,parsed_rows,ok,mode,sheets,parsed_sheets,seconds,note,read_seconds,parse_seconds
584,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78197,True,long_fallback/rows,9,9,9.113,М_Г+С:rows:8765 | Ж_Г+С:rows:8794 | М+Ж_Г:rows...,1.623,7.491
558,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80202,True,rows,9,9,8.873,М_Г+С:rows:8979 | Ж_Г+С:rows:9019 | М+Ж_Г:rows...,0.159,8.714
105,regions_app,/content/MONOGRAPH_CH3_V5_6/extracted/regions_...,23051,True,rows/skip,43,41,8.333,3.27.1.:rows:609 | 3.27.2.:rows:609 | 3.28.1.:...,1.020,7.312
582,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80116,True,rows,9,9,8.260,М_Г+С:rows:8974 | Ж_Г+С:rows:9009 | М+Ж_Г:rows...,0.180,8.079
577,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78948,True,rows/skip,10,9,8.237,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.301,7.936
556,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80265,True,long_fallback/rows,9,9,8.209,М_Г+С:rows:8993 | Ж_Г+С:rows:9016 | М+Ж_Г:rows...,0.177,8.032
553,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78948,True,rows/skip,10,9,8.209,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.172,8.037
560,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80186,True,long_fallback/rows,9,9,8.093,М_Г+С:rows:8983 | Ж_Г+С:rows:9014 | М+Ж_Г:rows...,0.297,7.796
578,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78946,True,rows/skip,10,9,8.090,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.162,7.927
585,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78182,True,rows,9,9,8.034,М_Г+С:rows:8764 | Ж_Г+С:rows:8796 | М+Ж_Г:rows...,0.161,7.872
573,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78948,True,rows/skip,10,9,7.992,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.148,7.844
555,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78948,True,rows/skip,10,9,7.940,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.261,7.680
580,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80265,True,long_fallback/rows,9,9,7.791,М_Г+С:rows:8986 | Ж_Г+С:rows:9020 | М+Ж_Г:rows...,0.164,7.627
575,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,78948,True,long_fallback/rows/skip,10,9,7.776,М_Г+С:rows:8772 | Ж_Г+С:rows:8772 | М+Ж_Г:rows...,0.165,7.611
950,living,/content/MONOGRAPH_CH3_V5_6/extracted/living/0...,553,True,long_fallback/rows/skip,17,7,7.701,2017:rows:81 | 2018:rows:81 | 2019:rows:81 | 2...,1.436,6.265
1618,social_position,/content/MONOGRAPH_CH3_V5_6/extracted/social_p...,0,False,rows,14,0,7.317,Раздел 7:rows:0 | Раздел 8:rows:0 | Раздел 9:r...,0.130,7.186
962,living,/content/MONOGRAPH_CH3_V5_6/extracted/living/0...,43688,True,rows/skip,16,8,7.203,2017:rows:5533 | 2018:rows:5447 | 2019:rows:55...,0.167,7.036
581,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80124,True,rows,9,9,7.132,М_Г+С:rows:8977 | Ж_Г+С:rows:9012 | М+Ж_Г:rows...,0.166,6.965
557,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80302,True,rows,9,9,7.064,М_Г+С:rows:8993 | Ж_Г+С:rows:9021 | М+Ж_Г:rows...,0.161,6.902
559,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,80198,True,long_fallback/rows,9,9,7.058,М_Г+С:rows:8979 | Ж_Г+С:rows:9016 | М+Ж_Г:rows...,0.169,6.889

In [4]:
# 2A. АУДИТ КОМПЛЕКТНОСТИ ДАННЫХ — ОБЯЗАТЕЛЬНАЯ КОНТРОЛЬНАЯ ТОЧКА V5.6
# После этой ячейки пользователь оценивает комплектность. Моделирование ещё НЕ запускается.
_STAGE2A_T0=timing_start("02A_data_completeness_audit")

# 1) Комплектность по источникам — используем CLEAN, чтобы точное межисточниковое дублирование не скрывало факт загрузки.
panel_src=PANEL_CLEAN.groupby("source").agg(
    panel_rows=("value","size"),panel_regions=("region","nunique"),
    panel_indicators=("indicator_id","nunique"),panel_years=("year","nunique")
).reset_index()

parse_base=TABLE_INDEX[TABLE_INDEX["mode"].ne("duplicate_file")].copy() if not TABLE_INDEX.empty else pd.DataFrame()
if not parse_base.empty:
    # Классифицируем результат файла: нерегиональная таблица != ошибка парсера.
    def _parse_status(r):
        note=str(r.get("note",""))
        mode=str(r.get("mode",""))
        if bool(r.get("ok",False)):return "parsed"
        if mode=="error" or re.search(r"(XLRDError|ParserError|UnicodeDecodeError|ValueError|AttributeError)",note):return "parser_error"
        if mode in {"rows","columns","long","rows/skip","columns/skip","long/skip"} and re.search(r":(?:rows|columns|long):0",note):
            return "regional_unparsed"
        if "no_regions" in note or mode=="skip":return "nonregional_or_out_of_scope"
        if mode=="duplicate_file":return "duplicate_file"
        return "unclassified_unparsed"
    parse_base["parse_status"]=parse_base.apply(_parse_status,axis=1)
    parse_src=parse_base.groupby("source").agg(
        files_attempted=("file","nunique"),files_with_data=("ok","sum"),
        sheets_seen=("sheets","sum"),sheets_parsed=("parsed_sheets","sum"),
        parsed_rows=("parsed_rows","sum"),median_seconds=("seconds","median"),
        p95_seconds=("seconds",lambda s:s.quantile(.95))
    ).reset_index()
    parse_src["file_parse_rate"]=parse_src["files_with_data"]/parse_src["files_attempted"].replace(0,np.nan)
    parse_src["sheet_parse_rate"]=parse_src["sheets_parsed"]/parse_src["sheets_seen"].replace(0,np.nan)
else:
    parse_src=pd.DataFrame(columns=["source","files_attempted","files_with_data","sheets_seen","sheets_parsed",
                                    "parsed_rows","median_seconds","p95_seconds","file_parse_rate","sheet_parse_rate"])
    parse_base["parse_status"]=[]

SOURCE_COMPLETENESS=SOURCE_AUDIT.merge(parse_src,on="source",how="left").merge(panel_src,on="source",how="left")
for c in ["files_attempted","files_with_data","sheets_seen","sheets_parsed","parsed_rows",
          "panel_rows","panel_regions","panel_indicators","panel_years"]:
    if c in SOURCE_COMPLETENESS:SOURCE_COMPLETENESS[c]=SOURCE_COMPLETENESS[c].fillna(0).astype(int)

# 2) Источник × год + список недостающих регионов.
SOURCE_YEAR=PANEL_CLEAN.groupby(["source","year"]).agg(
    rows=("value","size"),regions=("region","nunique"),indicators=("indicator_id","nunique")
).reset_index()
sr_rows=[]
for (s,y),g in PANEL_CLEAN.groupby(["source","year"]):
    have=set(g["region"])
    miss=[r for r in REGIONS if r not in have]
    sr_rows.append({"source":s,"year":int(y),"regions":len(have),"missing_regions_n":len(miss),
                    "missing_regions":"; ".join(miss)})
SOURCE_YEAR_COVERAGE=pd.DataFrame(sr_rows).sort_values(["source","year"]) if sr_rows else pd.DataFrame()

# 3) Регион × год всей аналитической панели.
REGION_YEAR=PANEL.groupby(["region","year"]).agg(
    indicators=("indicator_id","nunique"),sources=("source","nunique"),observations=("value","size")
).reset_index()
RY_MATRIX=REGION_YEAR.pivot(index="region",columns="year",values="indicators").reindex(index=REGIONS,columns=ANALYSIS_YEARS)

# 4) Комплектность содержательных блоков — cov уже имеет строго одну строку на indicator_id.
BLOCK_COMPLETENESS=cov.groupby("block").agg(
    indicators=("indicator_id","nunique"),research_grade=("research_grade","sum"),
    indicators_80plus=("regions_80plus","sum"),indicators_7y=("full_7y","sum"),
    median_regions=("regions","median"),median_years=("years","median"),
    max_regions=("regions","max"),max_years=("years","max")
).reset_index().sort_values(["research_grade","indicators"],ascending=False)

# 5) Предшоковое и постшоковое покрытие каждого аналитического показателя.
pre_cov=PANEL[PANEL["year"].isin(PRE_YEARS)].groupby("indicator_id").agg(
    pre_regions=("region","nunique"),pre_years=("year","nunique"),pre_obs=("value","size"))
post_cov=PANEL[PANEL["year"].isin(POST_YEARS)].groupby("indicator_id").agg(
    post_regions=("region","nunique"),post_years=("year","nunique"),post_obs=("value","size"))
INDICATOR_COMPLETENESS=cov.merge(pre_cov,left_on="indicator_id",right_index=True,how="left").merge(
    post_cov,left_on="indicator_id",right_index=True,how="left")
for c in ["pre_regions","pre_years","pre_obs","post_regions","post_years","post_obs"]:
    INDICATOR_COMPLETENESS[c]=INDICATOR_COMPLETENESS[c].fillna(0).astype(int)
INDICATOR_COMPLETENESS["usable_trajectory"]=(
    INDICATOR_COMPLETENESS["post_years"].ge(len(POST_YEARS)) &
    INDICATOR_COMPLETENESS["post_regions"].ge(70) &
    INDICATOR_COMPLETENESS["pre_years"].ge(2) &
    INDICATOR_COMPLETENESS["pre_regions"].ge(70))
INDICATOR_COMPLETENESS["usable_predictor"]=(
    INDICATOR_COMPLETENESS["pre_years"].ge(2) &
    INDICATOR_COMPLETENESS["pre_regions"].ge(55))

# 6) Аудит неразобранных файлов: разделяем критические ошибки исследовательского окна,
# исторические/внешние ошибки и штатно пропущенные нерегиональные материалы.
PARSER_FAILURES=parse_base[parse_base["parse_status"].isin(["parser_error","regional_unparsed","unclassified_unparsed"])].copy()
IGNORED_NONREGIONAL=parse_base[parse_base["parse_status"].eq("nonregional_or_out_of_scope")].copy()

def _years_from_row(r):
    txt=" ".join(str(r.get(c,"")) for c in ["file","note","source"])
    return sorted({int(x) for x in re.findall(r"(?<!\d)(20\d{2})(?!\d)",txt)})

if len(PARSER_FAILURES):
    _fy=PARSER_FAILURES.apply(_years_from_row,axis=1)
    _critical=_fy.map(lambda ys: (not ys) or bool(set(ys)&set(ANALYSIS_YEARS)))
    CRITICAL_FAILURES=PARSER_FAILURES[_critical].copy()
    HISTORICAL_FAILURES=PARSER_FAILURES[~_critical].copy()
else:
    CRITICAL_FAILURES=PARSER_FAILURES.copy()
    HISTORICAL_FAILURES=PARSER_FAILURES.copy()
UNPARSED_FILES=CRITICAL_FAILURES.copy()

# 7) Контрольные критерии.
CORE_BLOCKS={"demography","income","labour","industry"}
block_grade=BLOCK_COMPLETENESS.set_index("block")["research_grade"].to_dict()
primary_row=SOURCE_COMPLETENESS[SOURCE_COMPLETENESS["source"].eq("regions_app")]
primary_regions=int(primary_row["panel_regions"].iloc[0]) if len(primary_row) else 0
primary_years=int(primary_row["panel_years"].iloc[0]) if len(primary_row) else 0
primary_rows=int(primary_row["panel_rows"].iloc[0]) if len(primary_row) else 0

GATE=[]
def add_gate(check,required,status,detail):
    GATE.append({"check":check,"required":required,"status":status,"detail":detail})

add_gate("official_primary_source",True,
         "ok" if (len(primary_row) and bool(primary_row["ok"].iloc[0])) else "fail",
         "Основной официальный архив Росстата")
add_gate("panel_regions",True,"ok" if PANEL["region"].nunique()>=80 else "fail",
         f"{PANEL['region'].nunique()} регионов")
add_gate("panel_years_2017_2023",True,
         "ok" if set(ANALYSIS_YEARS).issubset(set(PANEL["year"].unique())) else "fail",
         "годы="+",".join(map(str,sorted(PANEL["year"].unique()))))
add_gate("primary_longitudinal_coverage",True,
         "ok" if primary_regions>=80 and primary_years==len(ANALYSIS_YEARS) else "fail",
         f"regions_app: rows={primary_rows}; regions={primary_regions}; years={primary_years}")
for b in sorted(CORE_BLOCKS):
    n=int(block_grade.get(b,0))
    add_gate(f"core_block_{b}",True,"ok" if n>=2 else ("warning" if n>=1 else "fail"),
             f"полных уникальных рядов 80+ регионов × 7 лет: {n}")

# ВНДН оценивается по всем доступным годовым выпускам, а не только 2023/2024.
vndn_rows=SOURCE_COMPLETENESS[SOURCE_COMPLETENESS["source"].astype(str).str.startswith("vndn_")]
vndn_loaded=int((vndn_rows["panel_rows"]>0).sum()) if len(vndn_rows) else 0
add_gate("vndn_historical_coverage",False,
         "ok" if vndn_loaded>=4 else ("warning" if vndn_loaded>=2 else "warning"),
         f"выпусков ВНДН с региональными данными: {vndn_loaded} из 7 (2018–2024)")

for s in ["natural_movement","migration","living","social_position","demographic_yearbook","workforce_compendium","labour_compendium","sme_compendium","demography"]:
    rr=SOURCE_COMPLETENESS[SOURCE_COMPLETENESS["source"].eq(s)]
    if rr.empty:add_gate(f"source_{s}",False,"warning","источник отсутствует в аудите")
    else:
        pr=int(rr["panel_rows"].iloc[0]);rg=int(rr["panel_regions"].iloc[0]);yr=int(rr["panel_years"].iloc[0])
        st="ok" if pr>0 and rg>=70 else "warning"
        add_gate(f"source_{s}",False,st,f"panel_rows={pr}; regions={rg}; years={yr}")

critical_failures=len(CRITICAL_FAILURES)
add_gate("parser_failures_target_window",False,"ok" if critical_failures==0 else "warning",
         f"критических ошибок 2017–2023/неопределённого года: {critical_failures}; исторических/внешних: {len(HISTORICAL_FAILURES)}; нерегиональных пропущено штатно: {len(IGNORED_NONREGIONAL)}")
add_gate("technical_titles_removed",False,"ok" if len(TECHNICAL_AUDIT)==0 else "warning",
         f"технических заголовков исключено из CLEAN: {len(TECHNICAL_AUDIT)}")
add_gate("exact_duplicate_series_removed_from_model",False,"ok" if len(DUP_SERIES)==0 else "warning",
         f"строк аудита дублей: {len(DUP_SERIES)}; в PANEL оставлен один представитель каждой точной серии")
collision_bad=int(((META_COLLISIONS.get("block_variants",pd.Series(dtype=int))>1) |
                   (META_COLLISIONS.get("source_variants",pd.Series(dtype=int))>1)).sum()) if not META_COLLISIONS.empty else 0
add_gate("indicator_id_collisions",False,"ok" if collision_bad==0 else "warning",
         f"indicator_id с конфликтом блока/источника: {collision_bad}")

DATA_GATE=pd.DataFrame(GATE)
DATA_RECOMMENDED_READY=not ((DATA_GATE["required"]) & (DATA_GATE["status"].eq("fail"))).any()

# 8) Экспорт контрольного комплекта ДО моделирования.
DATA_AUDIT_XLSX=RESULTS/"CHAPTER3_DATA_AUDIT_V5_6.xlsx"
with pd.ExcelWriter(DATA_AUDIT_XLSX,engine="xlsxwriter") as w:
    RUN_TIMINGS=timing_frame()
    sheets={
        "RUN_TIMINGS":RUN_TIMINGS,"DATA_GATE":DATA_GATE,"SOURCE_AUDIT":SOURCE_AUDIT,"SOURCE_COMPLETENESS":SOURCE_COMPLETENESS,
        "DISCOVERY_AUDIT":DISCOVERY_AUDIT,"DOWNLOAD_INDEX":DOWNLOAD_INDEX,"PARSE_AUDIT":TABLE_INDEX,
        "SOURCE_CATALOG":SOURCE_CATALOG,
        "PARSER_FAILURES":PARSER_FAILURES,"CRITICAL_FAILURES":CRITICAL_FAILURES,
        "HISTORICAL_FAILURES":HISTORICAL_FAILURES,"IGNORED_NONREGIONAL":IGNORED_NONREGIONAL,
        "SOURCE_YEAR":SOURCE_YEAR,"SOURCE_YEAR_COVERAGE":SOURCE_YEAR_COVERAGE,
        "REGION_YEAR":REGION_YEAR,"REGION_YEAR_MATRIX":RY_MATRIX.reset_index(),
        "BLOCK_COMPLETENESS":BLOCK_COMPLETENESS,"INDICATOR_COMPLETENESS":INDICATOR_COMPLETENESS,
        "SEMANTIC_AUDIT":SEMANTIC_AUDIT,"TECHNICAL_TITLES":TECHNICAL_AUDIT,
        "INDICATOR_ID_AUDIT":META_COLLISIONS,"DUPLICATE_SERIES":DUP_SERIES,
    }
    for name,df in sheets.items():df.to_excel(w,sheet_name=name[:31],index=False)

# V5.6: тяжёлый DATA_STAGE ZIP намеренно не создаётся.
timing_end("02A_data_completeness_audit",_STAGE2A_T0,detail=f"gate_ready={DATA_RECOMMENDED_READY}; critical_failures={len(CRITICAL_FAILURES)}")
RUN_TIMINGS=timing_frame(); RUN_TIMINGS.to_csv(PROCESSED/"run_timings.csv",index=False)
try:
    with pd.ExcelWriter(DATA_AUDIT_XLSX,engine="openpyxl",mode="a",if_sheet_exists="replace") as _tw:
        RUN_TIMINGS.to_excel(_tw,sheet_name="RUN_TIMINGS",index=False)
except Exception as _e:
    print("Предупреждение: не удалось обновить лист RUN_TIMINGS:",_e)
print("\n=== КОНТРОЛЬНАЯ ТОЧКА ДАННЫХ V5.6 ===")
display(DATA_GATE)
print("\nКомплектность источников:");display(SOURCE_COMPLETENESS)
print("\nКомплектность содержательных блоков:");display(BLOCK_COMPLETENESS)
print("\nКритические ошибки парсера 2017–2023 / неопределённого года:");display(CRITICAL_FAILURES.head(50))
print("\nРЕКОМЕНДАЦИЯ АВТОМАТИЧЕСКОГО GATE:",
      "МОЖНО РАССМАТРИВАТЬ ПРОДОЛЖЕНИЕ" if DATA_RECOMMENDED_READY else "НЕ ПРОДОЛЖАТЬ ДО ИСПРАВЛЕНИЯ ОБЯЗАТЕЛЬНЫХ ПУНКТОВ")
print("Окончательное решение принимает исследователь.")
print("Контрольный Excel:",DATA_AUDIT_XLSX)
print("\nТайминги этапов данных:"); display(timing_frame())

pipeline_done("data_gate",f"DATA_GATE={DATA_RECOMMENDED_READY}; регионы={PANEL.region.nunique()}")

▶ 02A_data_completeness_audit
✓ 02A_data_completeness_audit: 5.7 с | gate_ready=True; critical_failures=174

=== КОНТРОЛЬНАЯ ТОЧКА ДАННЫХ V5.6 ===

,check,required,status,detail
0,official_primary_source,True,ok,Основной официальный архив Росстата
1,panel_regions,True,ok,85 регионов
2,panel_years_2017_2023,True,ok,"годы=2017,2018,2019,2020,2021,2022,2023"
3,primary_longitudinal_coverage,True,ok,regions_app: rows=238027; regions=85; years=7
4,core_block_demography,True,ok,полных уникальных рядов 80+ регионов × 7 лет: 34
5,core_block_income,True,ok,полных уникальных рядов 80+ регионов × 7 лет: 18
6,core_block_industry,True,ok,полных уникальных рядов 80+ регионов × 7 лет: 46
7,core_block_labour,True,ok,полных уникальных рядов 80+ регионов × 7 лет: 24
8,vndn_historical_coverage,False,ok,выпусков ВНДН с региональными данными: 5 из 7 ...
9,source_natural_movement,False,ok,panel_rows=40002; regions=85; years=7
10,source_migration,False,ok,panel_rows=140800; regions=85; years=7
11,source_living,False,ok,panel_rows=72058; regions=85; years=7
12,source_social_position,False,ok,panel_rows=169821; regions=85; years=7
13,source_demographic_yearbook,False,ok,panel_rows=36787; regions=85; years=7
14,source_workforce_compendium,False,ok,panel_rows=42766; regions=80; years=7
15,source_labour_compendium,False,ok,panel_rows=62044; regions=85; years=7
16,source_sme_compendium,False,ok,panel_rows=55303; regions=85; years=7
17,source_demography,False,ok,panel_rows=24268; regions=84; years=7
18,parser_failures_target_window,False,warning,критических ошибок 2017–2023/неопределённого г...
19,technical_titles_removed,False,warning,технических заголовков исключено из CLEAN: 77
20,exact_duplicate_series_removed_from_model,False,warning,строк аудита дублей: 236; в PANEL оставлен оди...
21,indicator_id_collisions,False,ok,indicator_id с конфликтом блока/источника: 0

Комплектность источников:

,source,role,expected_data_year,ok,pages_scanned,downloaded_files,valid_tables,raw_mb,discovery_sec,download_sec,...,sheets_parsed,parsed_rows,median_seconds,p95_seconds,file_parse_rate,sheet_parse_rate,panel_rows,panel_regions,panel_indicators,panel_years
0,regions_app,primary,NaN,True,0,1,22,8.86,0.00,4.12,...,447,248929,1.7630,6.78695,0.909091,0.925466,238027,85,450,7
1,vndn_2018,survey,2017.0,False,3,0,0,0.00,8.72,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0
2,vndn_2019,survey,2018.0,False,3,0,0,0.00,5.47,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0
3,vndn_2020,survey,2019.0,True,11,12,12,0.24,10.45,9.30,...,4,6000,0.2320,0.27940,1.000000,1.000000,6000,75,80,3
4,vndn_2021,survey,2020.0,True,11,12,12,0.27,9.51,8.23,...,4,6675,0.2355,0.29150,1.000000,1.000000,6675,75,89,2
5,vndn_2022,survey,2021.0,True,11,12,12,0.25,10.25,8.49,...,4,6450,0.2355,0.28470,1.000000,1.000000,6450,75,86,2
6,vndn_2023,survey,2022.0,True,12,18,18,0.42,6.48,12.22,...,4,6450,0.2325,0.27080,1.000000,1.000000,6450,75,86,2
7,vndn_2024,survey,2023.0,True,12,18,18,0.38,7.24,11.90,...,4,6450,0.2370,0.29165,1.000000,1.000000,6450,75,86,2
8,natural_movement,specialized,NaN,True,1,16,32,4.09,1.37,24.21,...,99,49647,0.8885,1.38055,0.218750,0.172174,40002,85,286,7
9,migration,specialized,NaN,True,1,16,402,13.87,1.39,23.47,...,269,177386,0.0620,0.49695,0.134328,0.235552,140800,85,676,7
10,living,specialized,NaN,True,1,118,228,42.50,2.60,191.95,...,68,87385,0.0970,0.66935,0.105263,0.133072,72058,85,549,7
11,social_position,compendium,NaN,True,1,23,55,41.49,2.21,62.93,...,277,224744,0.3440,1.40940,0.781818,0.780282,169821,85,1106,7
12,demographic_yearbook,compendium,NaN,True,1,17,439,28.88,1.56,35.11,...,46,47306,0.0140,0.46350,0.025057,0.055090,36787,85,200,7
13,demography,supplementary,NaN,True,1,62,66,16.99,2.07,89.63,...,256,1757425,0.1720,8.23000,0.409091,0.644836,24268,84,318,7
14,workforce_compendium,compendium,NaN,True,1,16,36,15.17,1.55,29.21,...,116,70694,0.2345,0.82775,0.666667,0.449612,42766,80,373,7
15,labour_compendium,compendium,NaN,True,1,17,56,28.50,1.20,53.57,...,217,94969,0.2555,1.56850,0.642857,0.172496,62044,85,448,7
16,sme_compendium,compendium,NaN,True,1,20,135,20.20,1.65,36.32,...,270,58860,0.1800,0.53900,0.688889,0.503731,55303,85,218,7
17,kouzh_2018,survey,2018.0,True,8,60,60,1.41,5.83,38.48,...,60,39560,0.0660,0.15100,0.964912,0.952381,37162,80,524,1
18,kouzh_2020,survey,2020.0,True,8,36,36,0.81,4.28,23.80,...,16,11374,0.0595,0.11440,0.888889,0.888889,10870,75,151,1
19,kouzh_2022,survey,2022.0,True,9,36,36,0.86,6.59,23.64,...,16,12016,0.0675,0.11575,0.888889,0.888889,11424,75,154,1
20,kdu_2017,survey,2017.0,False,2,0,0,0.00,4.08,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0
21,kdu_2019,survey,2019.0,False,2,0,0,0.00,3.54,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0
22,kdu_2021,survey,2021.0,False,2,0,0,0.00,3.51,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0
23,kdu_2023,survey,2023.0,False,2,0,0,0.00,3.54,0.00,...,0,0,NaN,NaN,NaN,NaN,0,0,0,0

Комплектность содержательных блоков:

,block,indicators,research_grade,indicators_80plus,indicators_7y,median_regions,median_years,max_regions,max_years
4,other,1731,252,1370,291,84.0,2.0,85,7
2,industry,197,46,166,53,85.0,4.0,85,7
0,demography,996,34,937,35,84.0,2.0,85,7
3,labour,508,24,438,30,80.0,1.0,85,7
1,income,546,18,308,18,85.0,1.0,85,7
5,social_support,618,7,371,9,85.0,1.0,85,7

Критические ошибки парсера 2017–2023 / неопределённого года:

,source,file,parsed_rows,ok,mode,sheets,parsed_sheets,seconds,note,read_seconds,parse_seconds,parse_status
115,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,4,0,0.751,2.1:rows:0 | 2.2:rows:0 | 2.3:rows:0 | 2.4:rows:0,0.013,0.738,regional_unparsed
116,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,2,0,0.425,3.1:rows:0 | 3.2:rows:0,0.010,0.415,regional_unparsed
118,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,3,0,0.605,5.1:rows:0 | 5.2:rows:0 | 5.3:rows:0,0.012,0.593,regional_unparsed
122,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,4,0,0.719,2.1:rows:0 | 2.2:rows:0 | 2.3:rows:0 | 2.4:rows:0,0.013,0.706,regional_unparsed
123,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,2,0,0.434,3.1:rows:0 | 3.2:rows:0,0.011,0.422,regional_unparsed
125,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,3,0,0.591,5.1:rows:0 | 5.2:rows:0 | 5.3:rows:0,0.013,0.578,regional_unparsed
129,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,4,0,0.728,2.1:rows:0 | 2.2:rows:0 | 2.3:rows:0 | 2.4:rows:0,0.013,0.715,regional_unparsed
130,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,2,0,0.395,3.1:rows:0 | 3.2:rows:0,0.009,0.386,regional_unparsed
131,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,5,0,1.092,4.1:rows:0 | 4.2:rows:0 | 4.3:rows:0 | 4.4:row...,0.023,1.069,regional_unparsed
132,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,3,0,0.590,5.1:rows:0 | 5.2:rows:0 | 5.3:rows:0,0.012,0.578,regional_unparsed
133,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,6,0,1.818,6.1:rows:0 | 6.2:rows:0 | 6.3:rows:0 | 6.4:row...,0.028,1.790,regional_unparsed
134,demographic_yearbook,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows/skip,7,0,1.214,7.1:rows:0 | 7.2:rows:0 | 7.3:rows:0 | 7.4:ski...,0.041,1.173,regional_unparsed
594,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows/skip,10,0,1.139,прил.5:skip:no_regions(max=0) | прил.9:skip:no...,0.474,0.665,regional_unparsed
609,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows/skip,4,0,0.589,Содержание:skip:no_regions(max=0) | Сложное:ro...,0.019,0.569,regional_unparsed
610,demography,/content/MONOGRAPH_CH3_V5_6/extracted/demograp...,0,False,rows,1,0,0.241,Смерт. по возр.:rows:0,0.010,0.231,regional_unparsed
747,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,3,0,0.519,T_1.1.:rows:0 | Т_1.2.:rows:0 | Т_1.3.:rows:0,0.019,0.500,regional_unparsed
748,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,9,0,1.445,Т_1.5.:rows:0 | Т_1.6.:rows:0 | Т_1.7.:rows:0 ...,0.073,1.372,regional_unparsed
749,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,12,0,1.939,Т_1.17.:rows:0 | Т_1.18.:rows:0 | Т_1.19.:rows...,0.090,1.849,regional_unparsed
750,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,7,0,0.799,Т_2.1.:rows:0 | T_2.2.:rows:0 | Т_2.3.:rows:0 ...,0.041,0.757,regional_unparsed
751,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,3,0,0.249,Т_3.1.:rows:0 | Т_3.2.:rows:0 | Т_3.3.:rows:0,0.009,0.240,regional_unparsed
752,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,2,0,0.211,Т_5.1.:rows:0 | Т_5.2.:rows:0,0.007,0.204,regional_unparsed
753,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,1,0,0.108,Т_5.3.:rows:0,0.004,0.104,regional_unparsed
754,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,2,0,0.395,Т_5.4.:rows:0 | Т_5.5.:rows:0,0.012,0.384,regional_unparsed
755,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,8,0,1.440,Т_6.1.:rows:0 | Т_6.2.:rows:0 | Т_6.3.:rows:0 ...,0.032,1.407,regional_unparsed
756,labour_compendium,/content/MONOGRAPH_CH3_V5_6/extracted/labour_c...,0,False,rows,2,0,0.130,T_7.1.:rows:0 | Т_7.2.:rows:0,0.006,0.124,regional_unparsed
1110,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.113,t3_2:rows:0,0.004,0.109,regional_unparsed
1111,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.085,t3_3:rows:0,0.004,0.082,regional_unparsed
1112,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.210,t3_5:rows:0,0.004,0.206,regional_unparsed
1113,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.203,t3_6:rows:0,0.005,0.198,regional_unparsed
1114,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.130,t3_4:rows:0,0.004,0.125,regional_unparsed
1115,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.082,Tab1-1:rows:0,0.004,0.078,regional_unparsed
1116,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.103,Tab1-2:rows:0,0.003,0.100,regional_unparsed
1117,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.280,1-3 Всего:rows:0 | 1-3 Город:rows:0 | 1-3 Село...,0.007,0.273,regional_unparsed
1118,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.128,Tab1-4:rows:0,0.004,0.124,regional_unparsed
1121,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.217,Tab1-7:rows:0,0.006,0.211,regional_unparsed
1122,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.138,Tab1-8:rows:0,0.005,0.133,regional_unparsed
1123,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.063,Tab1-9:rows:0,0.004,0.059,regional_unparsed
1124,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.183,1-10 Всего:rows:0 | 1-10 Город:rows:0 | 1-10 С...,0.006,0.178,regional_unparsed
1126,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.061,Табл 1-14:rows:0,0.003,0.058,regional_unparsed
1133,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.535,прибыло:rows:0 | выбыло:rows:0 | миграция:rows:0,0.014,0.522,regional_unparsed
1136,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.637,прибыло:rows:0 | выбыло:rows:0 | миграция:rows:0,0.008,0.629,regional_unparsed
1140,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.664,2_14приб:rows:0 | 2_14выб:rows:0 | 2_14мигр:ro...,0.011,0.654,regional_unparsed
1143,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.686,2_17приб:rows:0 | 2_17выб:rows:0 | 2_17мигр:ro...,0.010,0.676,regional_unparsed
1147,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,3,0,0.497,2_21приб:rows:0 | 2_21выб:rows:0 | 2_21мигр:ro...,0.011,0.486,regional_unparsed
1196,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.131,Tab 3_2:rows:0,0.005,0.126,regional_unparsed
1197,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.095,Tab 3_3:rows:0,0.004,0.091,regional_unparsed
1198,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.212,Tab 3_5:rows:0,0.005,0.206,regional_unparsed
1199,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.185,Tab 3_6:rows:0,0.004,0.181,regional_unparsed
1200,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.127,Tab1-1:rows:0,0.004,0.123,regional_unparsed
1201,migration,/content/MONOGRAPH_CH3_V5_6/extracted/migratio...,0,False,rows,1,0,0.109,Tab1-2:rows:0,0.004,0.104,regional_unparsed

РЕКОМЕНДАЦИЯ АВТОМАТИЧЕСКОГО GATE: МОЖНО РАССМАТРИВАТЬ ПРОДОЛЖЕНИЕ
Окончательное решение принимает исследователь.
Контрольный Excel: /content/MONOGRAPH_CH3_V5_6/results/CHAPTER3_DATA_AUDIT_V5_6.xlsx

Тайминги этапов данных:

,stage,seconds,elapsed,detail
0,02_full_table_parser,1212.612,20 мин 13 с,"raw=2,853,784; clean=973,357; model=876,243; i..."
1,01_sources_download_extract,801.719,13 мин 22 с,"sources=24, ok=18, valid_tables=1675"
2,00_environment,23.388,23.4 с,/content/MONOGRAPH_CH3_V5_6
3,02A_data_completeness_audit,5.682,5.7 с,gate_ready=True; critical_failures=174

In [5]:
# 2B. РЕШЕНИЕ ИССЛЕДОВАТЕЛЯ ПОСЛЕ ПРОВЕРКИ КОМПЛЕКТНОСТИ V5.6
# Логика источниковой базы V5.4 уже прошла ручную приемку. При новом запуске моделирование
# продолжается только если обязательный DATA_GATE снова не содержит FAIL.
USER_APPROVED_DATA_STAGE=True  # V5.6: автоматическое продолжение при успешном DATA_GATE
CONTINUE_RESEARCH=bool(DATA_RECOMMENDED_READY)

print("Автоматическая рекомендация DATA_GATE:",
      "можно продолжать" if DATA_RECOMMENDED_READY else "есть обязательные FAIL")
print("V5.6 FULL: ручной стоп отключён; решение принимает обязательный DATA_GATE.")
print("CONTINUE_RESEARCH =",CONTINUE_RESEARCH)

Автоматическая рекомендация DATA_GATE: можно продолжать
V5.6 FULL: ручной стоп отключён; решение принимает обязательный DATA_GATE.
CONTINUE_RESEARCH = True

In [6]:
# 3. Постшоковые траектории устойчивости -> типология только при доказанной воспроизводимости
if not globals().get("CONTINUE_RESEARCH",False):
    print("Блок пропущен: CONTINUE_RESEARCH=False. Это штатная остановка после аудита данных.")
else:
    _STAGE3_T0=timing_start("03_postshock_trajectory_space")
    OUTCOME_BLOCKS=["demography","income","labour","industry"]
    PREDICTOR_BLOCKS=["demography","income","labour","industry","social_support"]
    TARGET_BLOCKS=OUTCOME_BLOCKS  # совместимость функций блока 3
    ry=PANEL[PANEL.year.isin(ANALYSIS_YEARS)].groupby(["indicator_id","region"]).year.nunique().reset_index(name="ny")
    usable=ry[ry.ny>=5].groupby("indicator_id").region.nunique().rename("usable_regions")

    # V5.6 FIX: полный coverage сохраняется для объясняющей модели.
    # Раньше COV сразу урезался до outcome-блоков, поэтому social_support
    # физически исчезал еще ДО whitelist блока 4.
    COV_ALL=cov.copy()
    COV_ALL["usable_regions"]=COV_ALL.indicator_id.map(usable).fillna(0).astype(int)
    COV_ALL["sem"]=COV_ALL.indicator.astype(str).map(semantic_key)

    # Для траекторий используем только outcome-блоки.
    COV_TRAJECTORY=COV_ALL[COV_ALL.block.isin(TARGET_BLOCKS)].copy()
    COV=COV_TRAJECTORY  # совместимость оставшейся логики блока 3

    TRAJECTORY_PRIORITY={
     "demography":["естественн прирост","миграционн прирост","ожидаем продолжительност жизни","суммарн коэффициент рождаем","общ коэффициент смертност","возрастн состав","демографическ нагруз"],
     "income":["реальн денежн доход","реальн начисленн заработн плат","реальн размер назначенн пенс","границ бедност","прожиточн минимум","среднедушев денежн доход","потребительск расход"],
     "labour":["уровен безработиц","уровен занятост","уровен участи состав рабоч сил","среднегодов численност занят","численност безработн"],
     "industry":["индекс физическ объем валов региональн продукт","индекс производств","индекс физическ объем инвестиц","промышленн производств","инвестиц основн капитал","оборот розничн торговл"],
     "social_support":["числ семей получавш субсид","среднемесячн размер субсид","численност граждан пользующ социальн поддерж","мер социальн поддерж","социальн поддерж"]
    }
    TRAJECTORY_CODES={
     "demography":[r"(^|\|)\s*1\.14\.",r"(^|\|)\s*1\.20\.",r"(^|\|)\s*1\.16\.1\.",r"(^|\|)\s*1\.15\."],
     "income":[r"(^|\|)\s*3\.1\.1\.",r"(^|\|)\s*3\.1\.2\.",r"(^|\|)\s*3\.1\.3\.",r"(^|\|)\s*3\.12\."],
     "labour":[r"(^|\|)\s*2\.10\.1\.",r"(^|\|)\s*2\.5\.",r"(^|\|)\s*2\.2\.",r"(^|\|)\s*2\.3\."],
     "industry":[r"(^|\|)\s*8\.3\.",r"(^|\|)\s*10\.3\.",r"(^|\|)\s*12\.3\.",r"(^|\|)\s*12\.5\."],
     "social_support":[r"(^|\|)\s*3\.28\.1\.",r"(^|\|)\s*3\.29\.1\.",r"(^|\|)\s*19\.3\."]
    }
    NOMINAL_BAD=["в текущих ценах","миллионов рублей","тысяч рублей","рублей на душу","общая сумма начисленных субсидий","объем средств"]
    RELATIVE_GOOD=["процент","коэффициент","индекс","реальн","на 1000","на 10 000","удельный вес","уровень"]

    def trajectory_score(row):
        raw=str(row.indicator); q=norm(raw); pri=TRAJECTORY_PRIORITY.get(str(row.block),[])
        code_hits=[400-25*rank for rank,pat in enumerate(TRAJECTORY_CODES.get(str(row.block),[])) if re.search(pat,raw,re.I)]
        sem_hits=[100-8*rank for rank,k in enumerate(pri) if phrase_hit(q,k)]
        score=max(code_hits or [0])+max(sem_hits or [0])
        if has_any(q,RELATIVE_GOOD): score+=18
        if has_any(q,NOMINAL_BAD) and not has_any(q,["реальн","индекс","процент"]): score-=45
        score+=min(float(row.usable_regions),85)/20+min(float(row.years),7)
        return score
    COV["trajectory_score"]=COV.apply(trajectory_score,axis=1)

    def choose_indicators(z,per_block=4):
        for mr,my in [(65,6),(55,6),(45,5),(35,5)]:
            q=z[(z.usable_regions>=mr)&(z.years>=my)].sort_values(["block","trajectory_score","usable_regions","coverage"],ascending=[True,False,False,False])
            out=[]
            for bl in TARGET_BLOCKS:
                seen=set()
                for _,r in q[q.block==bl].iterrows():
                    if r.trajectory_score<15: continue
                    sk=r["sem"]
                    if sk in seen: continue
                    seen.add(sk); out.append(r)
                    if sum(str(x["block"])==bl for x in out)>=per_block: break
            s=pd.DataFrame(out,columns=z.columns).drop_duplicates("indicator_id")
            core={"demography","income","labour","industry"}
            if len(s)>=12 and core.issubset(set(s.block)) and (s.groupby("block").size().reindex(list(core)).fillna(0)>=3).all():
                return s.reset_index(drop=True),mr,my
        return pd.DataFrame(columns=z.columns),None,None

    SELECTED,SEL_MIN_REG,SEL_MIN_YEARS=choose_indicators(COV)
    if SELECTED.empty: raise RuntimeError("Недостаточное покрытие для построения пространства траекторий.")
    SELECTED=SELECTED.drop_duplicates("indicator_id").reset_index(drop=True)

    # V5.6: направление outcome задается ТОЛЬКО по содержательному показателю.
    # Общие заголовки разделов («Занятость и безработица») не используются,
    # чтобы уровень занятости/участия в рабочей силе не инвертировался ошибочно.
    DIRECTION_RULES=[
        ("demography", r"(^|\|)\s*1\.14\.", +1, "естественный прирост"),
        ("demography", r"(^|\|)\s*1\.20\.", +1, "миграционный прирост"),
        ("demography", r"(^|\|)\s*1\.16\.1\.", +1, "ожидаемая продолжительность жизни"),
        ("demography", r"(^|\|)\s*1\.15\.", +1, "суммарная рождаемость"),
        ("demography", r"коэффициент.*смертност|смертност.*на 1000", -1, "смертность"),
        ("income", r"(^|\|)\s*3\.1\.1\.", +1, "реальные доходы"),
        ("income", r"(^|\|)\s*3\.1\.2\.", +1, "реальная заработная плата"),
        ("income", r"(^|\|)\s*3\.1\.3\.", +1, "реальные пенсии"),
        ("income", r"(^|\|)\s*3\.12\.", -1, "бедность"),
        ("labour", r"(^|\|)\s*2\.10\.1\.", -1, "уровень безработицы"),
        ("labour", r"(^|\|)\s*2\.5\.", +1, "уровень занятости"),
        ("labour", r"(^|\|)\s*2\.2\.", +1, "участие в рабочей силе"),
        ("labour", r"(^|\|)\s*2\.3\.", +1, "среднегодовая численность занятых"),
        ("industry", r"(^|\|)\s*8\.3\.", +1, "физический объем ВРП"),
        ("industry", r"(^|\|)\s*10\.3\.", +1, "физический объем инвестиций"),
        ("industry", r"(^|\|)\s*12\.3\.", +1, "промышленное производство"),
        ("industry", r"(^|\|)\s*12\.5\.", +1, "обрабатывающие производства"),
    ]

    def trajectory_direction(block,title):
        raw=str(title)
        for bl,pat,direction,reason in DIRECTION_RULES:
            if str(block)==bl and re.search(pat,raw,re.I):
                return int(direction), reason
        # Без молчаливого угадывания: неизвестный outcome должен быть рассмотрен вручную.
        raise ValueError(f"Не задано направление outcome: block={block}; indicator={title}")

    _dir=[trajectory_direction(b,t) for b,t in zip(SELECTED["block"],SELECTED["indicator"])]
    SELECTED["direction"]=[x[0] for x in _dir]
    SELECTED["direction_reason"]=[x[1] for x in _dir]
    DIRECTION_AUDIT=SELECTED[["indicator_id","indicator","block","direction","direction_reason"]].copy()
    META=SELECTED.set_index("indicator_id")[["indicator","block","direction"]].to_dict("index")
    regs=sorted(set(REGIONS)&set(PANEL.region.unique()))

    def build_deviation_scheme(scale_mode):
        dev_long=[]; metric_rows=[]; used=[]
        for iid in pbar(SELECTED["indicator_id"].tolist(),desc=f"3A/6 НОРМИРОВАНИЕ {scale_mode}",unit="показ.",leave=True):
            q=PANEL[(PANEL.indicator_id==iid)&PANEL.year.isin(ANALYSIS_YEARS)].pivot_table(index="region",columns="year",values="value",aggfunc="median").reindex(index=regs,columns=ANALYSIS_YEARS)
            good=(q.notna().sum(axis=1)>=5)&(q[PRE_YEARS].notna().sum(axis=1)>=2)&(q[POST_YEARS].notna().sum(axis=1)>=2)
            q=q.loc[good].copy()
            if len(q)<30: continue
            q[PRE_YEARS]=q[PRE_YEARS].apply(lambda r:r.interpolate(limit_direction="both"),axis=1)
            q[POST_YEARS]=q[POST_YEARS].apply(lambda r:r.interpolate(limit_direction="both"),axis=1)
            pre=q[PRE_YEARS]; center=pre.median(axis=1)
            if scale_mode=="region_robust":
                mad=pre.sub(center,axis=0).abs().median(axis=1)*1.4826
                std=pre.std(axis=1)
                scale=pd.concat([mad,std],axis=1).max(axis=1)
                floor=np.maximum(np.abs(center)*.03,1e-9)
                scale=pd.Series(np.maximum(scale.fillna(0).to_numpy(),floor.to_numpy()),index=q.index)
                dev=q.sub(center,axis=0).div(scale,axis=0)
            else:
                resid=pre.sub(center,axis=0).to_numpy(float).ravel(); resid=resid[np.isfinite(resid)]
                medr=float(np.nanmedian(resid)) if len(resid) else 0.0
                gmad=float(np.nanmedian(np.abs(resid-medr))*1.4826) if len(resid) else 0.0
                gstd=float(np.nanstd(resid)) if len(resid) else 0.0
                level=float(np.nanmedian(np.abs(center.to_numpy(float)))) if len(center) else 0.0
                sc=max(gmad,gstd,level*.01,1e-9)
                dev=q.sub(center,axis=0)/sc
            dev=dev.clip(-8,8)
            indicator=str(META[iid]["indicator"]); block=str(META[iid]["block"])
            direction=int(META[iid].get("direction",1))
            dev=dev*direction
            used.append(iid)
            for reg in dev.index:
                post=dev.loc[reg,POST_YEARS].to_numpy(dtype=float); finite=np.isfinite(post)
                if finite.sum()<2: continue
                inside=np.where(np.abs(post)<=.75)[0]
                metric_rows.append({"scale_mode":scale_mode,"region":str(reg),"indicator_id":str(iid),"indicator":indicator,"block":block,
                                    "shock_2020":float(post[0]),"max_abs_deviation":float(np.nanmax(np.abs(post))),
                                    "recovery_lag_years":float(inside[0]) if len(inside) else np.nan,
                                    "late_level":float(np.nanmean(post[-2:])),
                                    "post_slope":float(np.polyfit(np.arange(len(post))[finite],post[finite],1)[0]) if finite.sum()>1 else np.nan,
                                    "post_volatility":float(np.nanstd(post))})
                dev_long.extend({"scale_mode":scale_mode,"region":str(reg),"year":int(y0),"indicator_id":str(iid),"block":block,"deviation":float(v)} for y0,v in zip(POST_YEARS,post))
        return pd.DataFrame(dev_long),pd.DataFrame(metric_rows),used

    DEV_POOLED,METRICS_POOLED,used_pooled=build_deviation_scheme("pooled_robust")
    DEV_REGION,METRICS_REGION,used_region=build_deviation_scheme("region_robust")
    used=set(used_pooled)&set(used_region)
    SELECTED=SELECTED[SELECTED.indicator_id.isin(used)].drop_duplicates("indicator_id").reset_index(drop=True)
    if len(SELECTED)<12: raise RuntimeError(f"После нормирования осталось только {len(SELECTED)} показателей.")

    def block_year_matrix(dev,chosen_ids=None,drop_blocks=None):
        z=dev.copy()
        if chosen_ids is not None: z=z[z.indicator_id.isin(set(map(str,chosen_ids)))]
        if drop_blocks: z=z[~z.block.isin(set(drop_blocks))]
        a=z.groupby(["region","block","year"],as_index=False).deviation.median()
        w=a.assign(col=a.block+"__"+a.year.astype(str)).pivot(index="region",columns="col",values="deviation")
        expected=[f"{b}__{y0}" for b in TARGET_BLOCKS if not drop_blocks or b not in drop_blocks for y0 in POST_YEARS]
        w=w.reindex(columns=expected)
        w=w.loc[w.notna().mean(axis=1)>=.75]
        return w.apply(lambda c:c.fillna(c.median()),axis=0).fillna(0)

    def indicator_year_matrix(dev):
        z=dev.assign(col=dev.indicator_id.astype(str)+"__"+dev.year.astype(str))
        w=z.pivot_table(index="region",columns="col",values="deviation",aggfunc="median")
        w=w.loc[w.notna().mean(axis=1)>=.70]
        return w.apply(lambda c:c.fillna(c.median()),axis=0).fillna(0)

    def block_metric_matrix(metrics):
        cols=["shock_2020","late_level","post_slope","post_volatility"]
        a=metrics.groupby(["region","block"],as_index=False)[cols].median()
        parts=[]
        for st in cols:
            w=a.pivot(index="region",columns="block",values=st); w.columns=[f"{b}__{st}" for b in w.columns]; parts.append(w)
        z=pd.concat(parts,axis=1); z=z.loc[z.notna().mean(axis=1)>=.75]
        return z.apply(lambda c:c.fillna(c.median()),axis=0).fillna(0)

    TRAJ_PRIMARY=block_year_matrix(DEV_POOLED)
    TRAJ_REGION=block_year_matrix(DEV_REGION)
    TRAJ_INDICATOR=indicator_year_matrix(DEV_POOLED)
    TRAJ_METRICS=block_metric_matrix(METRICS_POOLED)
    if len(TRAJ_PRIMARY)<40: raise RuntimeError(f"В основном пространстве осталось только {len(TRAJ_PRIMARY)} регионов.")

    def embed_matrix(M,seed=SEED,variance=.90):
        X=StandardScaler().fit_transform(M)
        ncomp=max(2,min(20,X.shape[0]-1,X.shape[1]))
        p=PCA(n_components=ncomp,random_state=seed); E0=p.fit_transform(X)
        n90=max(2,min(E0.shape[1],int(np.searchsorted(np.cumsum(p.explained_variance_ratio_),variance)+1)))
        return E0[:,:n90],E0,p

    def cluster_fixed(M,k,seed=SEED):
        E,_,_=embed_matrix(M,seed); lab=KMeans(n_clusters=k,n_init=100,random_state=seed).fit_predict(E)
        return lab,E

    def evaluate_rep(name,M):
        rows=[]
        E,_,_=embed_matrix(M)
        for k in range(2,min(5,len(M)-1)):
            lab=KMeans(n_clusters=k,n_init=100,random_state=SEED).fit_predict(E); sz=pd.Series(lab).value_counts()
            if sz.min()<8: continue
            rows.append({"representation":name,"k":k,"silhouette":silhouette_score(E,lab),"min_cluster":int(sz.min()),"max_cluster":int(sz.max()),"regions":len(M),"features":M.shape[1]})
        return rows

    REPRESENTATION_ROWS=[]
    for name,M in [("block_year_pooled",TRAJ_PRIMARY),("block_year_region",TRAJ_REGION),("block_metrics_pooled",TRAJ_METRICS),("indicator_year_pooled",TRAJ_INDICATOR)]:
        REPRESENTATION_ROWS.extend(evaluate_rep(name,M))
    REPRESENTATION_AUDIT=pd.DataFrame(REPRESENTATION_ROWS)
    prim=REPRESENTATION_AUDIT[REPRESENTATION_AUDIT.representation=="block_year_pooled"].sort_values("silhouette",ascending=False)
    if prim.empty: raise RuntimeError("Основное блочное представление не дало допустимого разбиения.")
    BEST_K=int(prim.iloc[0].k)
    PRIMARY_SIL=float(prim.iloc[0].silhouette)
    base_labels,E=cluster_fixed(TRAJ_PRIMARY,BEST_K,SEED)
    primary_regions=TRAJ_PRIMARY.index.astype(str).tolist()

    # Альтернативная кластеризация и чувствительность к нормированию.
    try:
        alt=AgglomerativeClustering(n_clusters=BEST_K,linkage="ward").fit_predict(E); ALT_ARI=adjusted_rand_score(base_labels,alt)
    except Exception: ALT_ARI=np.nan; alt=None
    common=TRAJ_PRIMARY.index.intersection(TRAJ_REGION.index)
    norm_ari=np.nan; norm_labels=None
    if len(common)>=40:
        lr,_=cluster_fixed(TRAJ_REGION.loc[common],BEST_K,SEED+77)
        lp,_=cluster_fixed(TRAJ_PRIMARY.loc[common],BEST_K,SEED)
        norm_ari=adjusted_rand_score(lp,lr); norm_labels=lr

    stab=[]; partitions=[]; continuous_stability=[]
    partitions.append(("primary",base_labels.copy()))
    for seed in pbar(range(50),desc="3B/6 УСТОЙЧИВОСТЬ ПО SEED",unit="повт.",leave=True):
        z,_=cluster_fixed(TRAJ_PRIMARY,BEST_K,1000+seed); stab.append({"mode":"seed","rep":seed,"ARI":adjusted_rand_score(base_labels,z)}); partitions.append((f"seed_{seed}",z))

    rng=np.random.default_rng(SEED)
    ids_by_block={b:SELECTED[SELECTED.block==b].indicator_id.astype(str).tolist() for b in TARGET_BLOCKS}
    for r in pbar(range(BOOT_N),desc="3C/6 СТРАТИФИЦИРОВАННЫЕ ПОДВЫБОРКИ",unit="повт.",leave=True):
        take=[]
        for bl,ids in ids_by_block.items():
            if not ids: continue
            n=max(1,min(len(ids),int(np.ceil(.75*len(ids)))))
            take.extend(rng.choice(np.array(ids,dtype=object),size=n,replace=False).tolist())
        M=block_year_matrix(DEV_POOLED,take).reindex(primary_regions).dropna(how="all")
        if len(M)!=len(primary_regions): continue
        z,Esub=cluster_fixed(M,BEST_K,SEED+r); ari=adjusted_rand_score(base_labels,z)
        stab.append({"mode":"indicator_stratified","rep":r,"ARI":ari}); partitions.append((f"indsub_{r}",z))
        try:
            rho=float(spearmanr(pdist(E[:,:2]),pdist(Esub[:,:2])).statistic)
        except Exception:
            rho=np.nan
        continuous_stability.append({"mode":"indicator_stratified","rep":r,"distance_rho":rho})

    loo=[]
    for iid in pbar(SELECTED.indicator_id.astype(str).tolist(),desc="3D/6 LEAVE-ONE-INDICATOR",unit="показ.",leave=True):
        take=[x for x in SELECTED.indicator_id.astype(str).tolist() if x!=iid]
        M=block_year_matrix(DEV_POOLED,take).reindex(primary_regions)
        if M.isna().all(axis=1).any(): continue
        z,Esub=cluster_fixed(M.fillna(M.median()).fillna(0),BEST_K,SEED+31); ari=adjusted_rand_score(base_labels,z)
        loo.append({"mode":"leave_one_indicator","rep":iid,"ARI":ari}); partitions.append((f"loo_{iid}",z))
        try:
            rho=float(spearmanr(pdist(E[:,:2]),pdist(Esub[:,:2])).statistic)
        except Exception:
            rho=np.nan
        continuous_stability.append({"mode":"leave_one_indicator","rep":iid,"distance_rho":rho})

    lob=[]
    for bl in pbar(TARGET_BLOCKS,desc="3E/6 LEAVE-ONE-BLOCK",unit="блок",leave=True):
        M=block_year_matrix(DEV_POOLED,drop_blocks=[bl]).reindex(primary_regions)
        if M.isna().all(axis=1).any(): continue
        z,Esub=cluster_fixed(M.fillna(M.median()).fillna(0),BEST_K,SEED+47); ari=adjusted_rand_score(base_labels,z)
        lob.append({"mode":"leave_one_block","rep":bl,"ARI":ari})
        try:
            rho=float(spearmanr(pdist(E[:,:2]),pdist(Esub[:,:2])).statistic)
        except Exception:
            rho=np.nan
        continuous_stability.append({"mode":"leave_one_block","rep":bl,"distance_rho":rho})
    CLUSTER_STABILITY=pd.concat([pd.DataFrame(stab),pd.DataFrame(loo),pd.DataFrame(lob)],ignore_index=True)

    # Consensus/co-association matrix по возмущениям, не зависящая от нумерации меток.
    n=len(primary_regions); co=np.zeros((n,n),float)
    for _,lab in partitions: co+=(lab[:,None]==lab[None,:]).astype(float)
    co/=max(len(partitions),1); dist=1-co; np.fill_diagonal(dist,0)
    try:
        cons=AgglomerativeClustering(n_clusters=BEST_K,metric="precomputed",linkage="average").fit_predict(dist)
    except TypeError:
        cons=AgglomerativeClustering(n_clusters=BEST_K,affinity="precomputed",linkage="average").fit_predict(dist)
    CONSENSUS_ARI=float(adjusted_rand_score(base_labels,cons)); CONSENSUS_SIL=float(silhouette_score(E,cons))
    same=(cons[:,None]==cons[None,:]); tri=np.triu(np.ones_like(same,dtype=bool),1)
    within=float(np.nanmean(co[tri & same])) if np.any(tri & same) else np.nan
    between=float(np.nanmean(co[tri & ~same])) if np.any(tri & ~same) else np.nan
    CONSENSUS_GAP=within-between if pd.notna(within) and pd.notna(between) else np.nan
    CONSENSUS_MATRIX=pd.DataFrame(co,index=primary_regions,columns=primary_regions).reset_index(names="region")

    indicator_med=float(CLUSTER_STABILITY.loc[CLUSTER_STABILITY["mode"].eq("indicator_stratified"),"ARI"].median())
    seed_med=float(CLUSTER_STABILITY.loc[CLUSTER_STABILITY["mode"].eq("seed"),"ARI"].median())
    loo_med=float(CLUSTER_STABILITY.loc[CLUSTER_STABILITY["mode"].eq("leave_one_indicator"),"ARI"].median())
    lob_med=float(CLUSTER_STABILITY.loc[CLUSTER_STABILITY["mode"].eq("leave_one_block"),"ARI"].median())

    # Устойчивость непрерывной геометрии при другой нормировке.
    norm_distance_rho=np.nan
    if len(common)>=40:
        try:
            _,Epool=cluster_fixed(TRAJ_PRIMARY.loc[common],BEST_K,SEED)
            _,Ereg=cluster_fixed(TRAJ_REGION.loc[common],BEST_K,SEED+77)
            norm_distance_rho=float(spearmanr(pdist(Epool[:,:2]),pdist(Ereg[:,:2])).statistic)
        except Exception:
            norm_distance_rho=np.nan

    CONTINUUM_STABILITY=pd.DataFrame(continuous_stability)
    ind_geom=float(CONTINUUM_STABILITY.loc[CONTINUUM_STABILITY["mode"].eq("indicator_stratified"),"distance_rho"].median()) if len(CONTINUUM_STABILITY) else np.nan
    loo_geom=float(CONTINUUM_STABILITY.loc[CONTINUUM_STABILITY["mode"].eq("leave_one_indicator"),"distance_rho"].median()) if len(CONTINUUM_STABILITY) else np.nan
    lob_geom=float(CONTINUUM_STABILITY.loc[CONTINUUM_STABILITY["mode"].eq("leave_one_block"),"distance_rho"].median()) if len(CONTINUUM_STABILITY) else np.nan

    TYPOLOGY_ACCEPTED=bool(
        PRIMARY_SIL>=TYPOLOGY_MIN_SILHOUETTE and
        indicator_med>=TYPOLOGY_MIN_INDICATOR_ARI and
        pd.notna(norm_ari) and norm_ari>=TYPOLOGY_MIN_NORMALIZATION_ARI and
        CONSENSUS_ARI>=TYPOLOGY_MIN_CONSENSUS_ARI and
        pd.notna(CONSENSUS_GAP) and CONSENSUS_GAP>=TYPOLOGY_MIN_CONSENSUS_GAP
    )

    CONTINUUM_ACCEPTED=bool(
        pd.notna(norm_distance_rho) and norm_distance_rho>=CONTINUUM_MIN_NORM_DISTANCE_RHO and
        pd.notna(ind_geom) and ind_geom>=CONTINUUM_MIN_INDICATOR_DISTANCE_RHO and
        pd.notna(loo_geom) and loo_geom>=CONTINUUM_MIN_LOO_DISTANCE_RHO and
        pd.notna(lob_geom) and lob_geom>=CONTINUUM_MIN_LOB_DISTANCE_RHO
    )

    # V5.6: кластеризация остаётся диагностикой. Даже если конкретный прогон
    # формально прошёл кластерный gate, основной научный результат строится
    # как непрерывное/многомерное пространство, поскольку это устойчивее к
    # составу показателей и не вводит искусственный индекс.
    if CONTINUUM_ACCEPTED:
        ANALYSIS_MODE="multidimensional_continuous_space"
    else:
        ANALYSIS_MODE="multidimensional_trajectory_profiles"

    final_labels=cons if TYPOLOGY_ACCEPTED else base_labels
    CLUSTERS=pd.DataFrame({"region":primary_regions,"cluster":final_labels.astype(int)+1})
    CLUSTERS["type"]="Тип "+CLUSTERS.cluster.astype(str)
    CLUSTERS["typology_accepted"]=TYPOLOGY_ACCEPTED

    # Непрерывное пространство и нагрузки PCA.
    _,E0,PCA_MODEL=embed_matrix(TRAJ_PRIMARY)
    pca_scores=E0[:,:2].copy()

    # Знак PC1 делаем интерпретируемым: положительное направление связано
    # с более благоприятным поздним уровнем outcome-блоков (после direction harmonisation).
    late_cols=[f"{b}__2023" for b in OUTCOME_BLOCKS if f"{b}__2023" in TRAJ_PRIMARY.columns]
    if late_cols:
        anchor=TRAJ_PRIMARY[late_cols].mean(axis=1).to_numpy(float)
        try:
            rr=float(spearmanr(pca_scores[:,0],anchor).statistic)
        except Exception:
            rr=np.nan
        if pd.notna(rr) and rr<0:
            pca_scores[:,0]*=-1
            PCA_MODEL.components_[0,:]*=-1

    PCA_COORD=pd.DataFrame(pca_scores,index=TRAJ_PRIMARY.index.astype(str),columns=["PC1","PC2"]).reset_index(names="region").merge(CLUSTERS,on="region")
    PCA_VARIANCE=pd.DataFrame({
        "component":np.arange(1,len(PCA_MODEL.explained_variance_ratio_)+1),
        "explained_variance":PCA_MODEL.explained_variance_ratio_,
        "cumulative":np.cumsum(PCA_MODEL.explained_variance_ratio_)
    })
    load_rows=[]
    for ci in range(min(2,PCA_MODEL.components_.shape[0])):
        for feature,val in zip(TRAJ_PRIMARY.columns,PCA_MODEL.components_[ci]):
            load_rows.append({"component":f"PC{ci+1}","feature":feature,"loading":float(val)})
    PCA_LOADINGS=pd.DataFrame(load_rows)
    CONTINUOUS_TARGETS=PCA_COORD[["region","PC1","PC2"]].copy()

    # Блочные непрерывные оси: fallback, если общей воспроизводимой геометрии нет.
    block_target=pd.DataFrame({"region":TRAJ_PRIMARY.index.astype(str)})
    block_load=[]
    block_var=[]
    for bl in OUTCOME_BLOCKS:
        cols=[f"{bl}__{y0}" for y0 in POST_YEARS if f"{bl}__{y0}" in TRAJ_PRIMARY.columns]
        if len(cols)<3:
            continue
        M=TRAJ_PRIMARY[cols].copy()
        Z=StandardScaler().fit_transform(M)
        pp=PCA(n_components=1,random_state=SEED)
        score=pp.fit_transform(Z).ravel()
        # Положительный знак = более благоприятный поздний outcome.
        anchor=M[cols[-1]].to_numpy(float)
        try:
            rr=float(spearmanr(score,anchor).statistic)
        except Exception:
            rr=np.nan
        if pd.notna(rr) and rr<0:
            score*=-1
            pp.components_[0,:]*=-1
        block_target[f"{bl}_axis"]=score
        block_var.append({"block":bl,"explained_variance":float(pp.explained_variance_ratio_[0])})
        for f,v in zip(cols,pp.components_[0]):
            block_load.append({"block":bl,"feature":f,"loading":float(v)})
    BLOCK_TARGETS=block_target
    BLOCK_PCA_VARIANCE=pd.DataFrame(block_var)
    BLOCK_PCA_LOADINGS=pd.DataFrame(block_load)

    METRICS=METRICS_POOLED[METRICS_POOLED.region.isin(primary_regions)].copy(); DEV_LONG=DEV_POOLED[DEV_POOLED.region.isin(primary_regions)].copy()
    PM=METRICS.merge(CLUSTERS,on="region",how="inner")
    PROFILES=PM.groupby(["cluster","type","block"],as_index=False).agg(n_regions=("region","nunique"),shock_2020=("shock_2020","median"),max_abs_deviation=("max_abs_deviation","median"),recovery_lag_years=("recovery_lag_years","median"),late_level=("late_level","median"),post_slope=("post_slope","median"),post_volatility=("post_volatility","median"))
    PLOT_TRAJECTORIES=DEV_LONG.merge(CLUSTERS,on="region").groupby(["block","type","year"],as_index=False).deviation.median()
    TYPOLOGY_DIAGNOSTICS=pd.DataFrame([
        {"metric":"analysis_mode","value":ANALYSIS_MODE},
        {"metric":"primary_silhouette","value":PRIMARY_SIL},
        {"metric":"seed_median_ARI","value":seed_med},
        {"metric":"indicator_stratified_median_ARI","value":indicator_med},
        {"metric":"leave_one_indicator_median_ARI","value":loo_med},
        {"metric":"leave_one_block_median_ARI","value":lob_med},
        {"metric":"normalization_ARI","value":norm_ari},
        {"metric":"alternative_hierarchical_ARI","value":ALT_ARI},
        {"metric":"consensus_ARI","value":CONSENSUS_ARI},
        {"metric":"consensus_silhouette","value":CONSENSUS_SIL},
        {"metric":"consensus_within","value":within},
        {"metric":"consensus_between","value":between},
        {"metric":"consensus_gap","value":CONSENSUS_GAP},
        {"metric":"typology_accepted","value":TYPOLOGY_ACCEPTED},
        {"metric":"continuum_norm_distance_rho","value":norm_distance_rho},
        {"metric":"continuum_indicator_median_distance_rho","value":ind_geom},
        {"metric":"continuum_loo_indicator_median_distance_rho","value":loo_geom},
        {"metric":"continuum_leave_block_median_distance_rho","value":lob_geom},
        {"metric":"continuum_accepted","value":CONTINUUM_ACCEPTED},
    ])

    TRAJ_PRIMARY.to_parquet(PROCESSED/"trajectory_block_year_primary.parquet")
    METRICS.to_parquet(PROCESSED/"trajectory_metrics.parquet",index=False)
    CLUSTERS.to_csv(PROCESSED/"regional_types_exploratory.csv",index=False)
    CONTINUOUS_TARGETS.to_csv(PROCESSED/"continuous_trajectory_targets.csv",index=False)
    BLOCK_TARGETS.to_csv(PROCESSED/"block_trajectory_targets.csv",index=False)
    CONTINUUM_STABILITY.to_csv(PROCESSED/"continuous_geometry_stability.csv",index=False)
    SELECTED.to_csv(PROCESSED/"selected_trajectory_indicators.csv",index=False)

    plt.figure(figsize=(8.5,6.2))
    if TYPOLOGY_ACCEPTED:
        for t,g in PCA_COORD.groupby("type"): plt.scatter(g.PC1,g.PC2,label=t,s=48,alpha=.82)
        plt.legend(frameon=False)
    else:
        plt.scatter(PCA_COORD.PC1,PCA_COORD.PC2,s=48,alpha=.82)
    plt.xlabel("Первая компонента траекторий"); plt.ylabel("Вторая компонента траекторий"); plt.tight_layout()
    for ext in ("png","svg"): plt.savefig(FIG/f"01_trajectory_space.{ext}",dpi=600 if ext=="png" else None,bbox_inches="tight")
    plt.close()

    RU_BLOCK={"demography":"Демографическая динамика","income":"Доходы и уровень жизни","labour":"Рынок труда","industry":"Экономическая и отраслевая динамика","social_support":"Социальная поддержка"}
    if TYPOLOGY_ACCEPTED:
        for bl,g in pbar(list(PLOT_TRAJECTORIES.groupby("block")),desc="3F/6 ГРАФИКИ ТРАЕКТОРИЙ",unit="блок",leave=True):
            plt.figure(figsize=(9,5.4))
            for t,h in g.groupby("type"): plt.plot(h.year,h.deviation,marker="o",label=t)
            plt.axvline(SHOCK_YEAR,color="black",lw=1,ls="--"); plt.axhline(0,color="black",lw=.7); plt.title(RU_BLOCK.get(bl,bl)); plt.xlabel("Год"); plt.ylabel("Медианное стандартизированное отклонение"); plt.legend(frameon=False); plt.tight_layout()
            for ext in ("png","svg"): plt.savefig(FIG/f"trajectory_{bl}.{ext}",dpi=600 if ext=="png" else None,bbox_inches="tight")
            plt.close()

    timing_end("03_postshock_trajectory_space",_STAGE3_T0,detail=f"mode={ANALYSIS_MODE}; regions={len(primary_regions)}; indicators={len(SELECTED)}; k={BEST_K}; silhouette={PRIMARY_SIL:.3f}; indicator_ARI={indicator_med:.3f}")
    print(f"V5.6: mode={ANALYSIS_MODE} | regions={len(primary_regions)} | indicators={len(SELECTED)} | k={BEST_K} | silhouette={PRIMARY_SIL:.3f} | indicator ARI={indicator_med:.3f} | continuum norm rho={norm_distance_rho:.3f} | continuum indicator rho={ind_geom:.3f}")
    display(REPRESENTATION_AUDIT.sort_values(["representation","silhouette"],ascending=[True,False])); display(TYPOLOGY_DIAGNOSTICS); display(SELECTED[["block","indicator","usable_regions","years","trajectory_score"]])

pipeline_done("trajectories",f"траектории: mode={ANALYSIS_MODE}; continuum={CONTINUUM_ACCEPTED}")

▶ 03_postshock_trajectory_space

3A/6 НОРМИРОВАНИЕ pooled_robust:   0%|                            | 0/16 [00:00<?, ?показ./s]

3A/6 НОРМИРОВАНИЕ region_robust:   0%|                            | 0/16 [00:00<?, ?показ./s]

3B/6 УСТОЙЧИВОСТЬ ПО SEED:   0%|                            | 0/50 [00:00<?, ?повт./s]

3C/6 СТРАТИФИЦИРОВАННЫЕ ПОДВЫБОРКИ:   0%|                            | 0/100 [00:00<?, ?повт./s]

3D/6 LEAVE-ONE-INDICATOR:   0%|                            | 0/16 [00:00<?, ?показ./s]

3E/6 LEAVE-ONE-BLOCK:   0%|                            | 0/4 [00:00<?, ?блок/s]

✓ 03_postshock_trajectory_space: 32.7 с | mode=multidimensional_continuous_space; regions=85; indicators=16; k=2; silhouette=0.112; indicator_ARI=0.297
V5.6: mode=multidimensional_continuous_space | regions=85 | indicators=16 | k=2 | silhouette=0.112 | indicator ARI=0.297 | continuum norm rho=0.662 | continuum indicator rho=0.653

,representation,k,silhouette,min_cluster,max_cluster,regions,features
5,block_metrics_pooled,2,0.149356,35,50,85,16
6,block_metrics_pooled,3,0.140463,16,40,85,16
0,block_year_pooled,2,0.112142,37,48,85,16
1,block_year_pooled,3,0.100190,19,38,85,16
3,block_year_region,3,0.123920,23,33,85,16
2,block_year_region,2,0.122989,33,52,85,16
4,block_year_region,4,0.118860,8,33,85,16
7,indicator_year_pooled,2,0.140558,31,54,85,64
8,indicator_year_pooled,3,0.070485,11,39,85,64

,metric,value
0,analysis_mode,multidimensional_continuous_space
1,primary_silhouette,0.112142
2,seed_median_ARI,1.0
3,indicator_stratified_median_ARI,0.297419
4,leave_one_indicator_median_ARI,0.203409
5,leave_one_block_median_ARI,0.580387
6,normalization_ARI,0.509148
7,alternative_hierarchical_ARI,-0.010055
8,consensus_ARI,1.0
9,consensus_silhouette,0.112142
10,consensus_within,0.733743
11,consensus_between,0.286751
12,consensus_gap,0.446992
13,typology_accepted,False
14,continuum_norm_distance_rho,0.661696
15,continuum_indicator_median_distance_rho,0.653451
16,continuum_loo_indicator_median_distance_rho,0.947764
17,continuum_leave_block_median_distance_rho,0.776799
18,continuum_accepted,True

,block,indicator,usable_regions,years,trajectory_score
0,demography,1.14. КОЭФФИЦИЕНТЫ ЕСТЕСТВЕННОГО ПРИРОСТА НАСЕ...,85,7,529.25
1,demography,1.20. КОЭФФИЦИЕНТЫ МИГРАЦИОННОГО ПРИРОСТА на 1...,85,7,496.25
2,demography,ОЖИДАЕМАЯ ПРОДОЛЖИТЕЛЬНОСТЬ ЖИЗНИ ПРИ РОЖДЕНИИ...,85,7,445.25
3,demography,1.15. СУММАРНЫЙ КОЭФФИЦИЕНТ РОЖДАЕМОСТИ | (чис...,85,7,430.25
4,income,3.1. РЕАЛЬНЫЕ ДЕНЕЖНЫЕ ДОХОДЫ | 3.1.1. Реальны...,85,7,529.25
5,income,3.1. РЕАЛЬНЫЕ ДЕНЕЖНЫЕ ДОХОДЫ | 3.1.2. Реальна...,85,7,504.25
6,income,3.1. РЕАЛЬНЫЕ ДЕНЕЖНЫЕ ДОХОДЫ | 3.1.3. Реальны...,85,7,479.25
7,income,3.12. ЧИСЛЕННОСТЬ НАСЕЛЕНИЯ С ДЕНЕЖНЫМИ ДОХОДА...,85,7,430.25
8,labour,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.10.1. Уровень безр...,85,7,529.25
9,labour,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.5. УРОВЕНЬ ЗАНЯТОС...,85,7,504.25
10,labour,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.2. УРОВЕНЬ УЧАСТИЯ...,85,7,479.25
11,labour,ЗАНЯТОСТЬ И БЕЗРАБОТИЦА | 2.3. СРЕДНЕГОДОВАЯ Ч...,85,7,412.25
12,industry,8.3. ИНДЕКС ФИЗИЧЕСКОГО ОБЪЕМА ВАЛОВОГО РЕГИОН...,84,7,529.20
13,industry,10.3. ИНДЕКС ФИЗИЧЕСКОГО ОБЪЕМА ИНВЕСТИЦИЙ В О...,84,7,488.20
14,industry,12.3. ИНДЕКСЫ ПРОМЫШЛЕННОГО ПРОИЗВОДСТВА | 12....,85,7,471.25
15,industry,12.5. ИНДЕКСЫ ПРОИЗВОДСТВА по виду экономическ...,85,7,446.25

In [7]:
# 4. Предшоковые факторы -> семантически строгая антициркулярная модель и проверки устойчивости
if not globals().get("CONTINUE_RESEARCH",False):
    print("Блок пропущен: CONTINUE_RESEARCH=False.")
else:
    _STAGE4_T0=timing_start("04_explanatory_models_and_robustness")
    STRICT_ANTICIRCULAR=True
    # Только research-grade ряды из ПОЛНОГО coverage.
    # COV_TRAJECTORY содержит только outcome, поэтому для факторов используем COV_ALL.
    _PRED_COV=COV_ALL if "COV_ALL" in globals() else cov.copy()
    if "usable_regions" not in _PRED_COV.columns:
        _PRED_COV=_PRED_COV.copy()
        _PRED_COV["usable_regions"]=_PRED_COV.indicator_id.map(usable).fillna(0).astype(int)
    PRED=_PRED_COV[
        (_PRED_COV["research_grade"].eq(True) if "research_grade" in _PRED_COV.columns else pd.Series(False,index=_PRED_COV.index))
        &(_PRED_COV.usable_regions>=35)
        &(_PRED_COV.years>=3)
    ].copy()
    preobs=PANEL[PANEL.year.isin(PRE_YEARS)].groupby("indicator_id").agg(pre_regions=("region","nunique"),pre_years=("year","nunique"),pre_obs=("value","size"))
    PRED=PRED.merge(preobs,left_on="indicator_id",right_index=True,how="left"); PRED=PRED[(PRED.pre_regions>=35)&(PRED.pre_years>=2)].copy()
    selected_sem=set(SELECTED.indicator.astype(str).map(semantic_key)); PRED["sem"]=PRED.indicator.astype(str).map(semantic_key)
    if STRICT_ANTICIRCULAR:
        PRED=PRED[(~PRED.indicator_id.isin(set(SELECTED.indicator_id)))&(~PRED["sem"].isin(selected_sem))].copy()

    PREDICTOR_PRIORITY={
      "demography":["удельный вес городского населения","население старше трудоспособного возраста","население в трудоспособном возрасте","коэффициенты демографической нагрузки","смертность населения в трудоспособном возрасте","соотношение мужчин и женщин"],
      "income":["среднедушевые денежные доходы","медианный среднедушевой денежный доход","среднемесячная номинальная начисленная заработная плата","потребительские расходы в среднем на душу","численность занятых, приходящихся на одного пенсионера","удельный вес расходов домашних хозяйств на оплату жилищно-коммунальных услуг"],
      "labour":["уровень зарегистрированной безработицы","потребность в работниках","нагрузка незанятого населения","изменение среднегодовой численности занятых","безработицы населения в возрасте 15-29 лет","иностранных граждан"],
      "industry":["валовой региональный продукт на душу населения","инвестиции в основной капитал на душу населения","удельный вес индивидуальных предпринимателей","ввод в действие жилых домов","структура оборота розничной торговли","индексы производства продукции сельского хозяйства"],
      "social_support":["среднемесячный размер социальной поддержки","среднемесячный размер субсидий на семью","объем средств, предусмотренных на предоставление гражданам социальной поддержки","число семей, получавших субсидии","расходы консолидированных бюджетов субъектов российской федерации на реализацию мер социальной поддержки","численность граждан, пользующихся социальной поддержкой","общая сумма начисленных субсидий"]
    }
    SOCIAL_FORBIDDEN=["лук","лимон","сапог","ботин","костюм","говядин","свинин","куры","молоко","масло","хлеб","товары, шт","покупательная способность"]
    SOCIAL_SUPPORT_CODES=[
        r"(^|\\|)\\s*3\\.28\\.[123]\\.",
        r"(^|\\|)\\s*3\\.29\\.[123]\\.",
        r"(^|\\|)\\s*19\\.3\\."
    ]

    def predictor_score(r):
        q=norm(r.indicator); pats=PREDICTOR_PRIORITY.get(str(r.block),[]); hits=[]
        for rank,p in enumerate(pats):
            if norm(p) in q:
                hits.append(150-15*rank)

        # Для социальной поддержки используем также устойчивые к формулировкам
        # коды таблиц основного сборника Росстата: 3.28.*, 3.29.*, 19.3.
        if str(r.block)=="social_support":
            for rank,pat in enumerate(SOCIAL_SUPPORT_CODES):
                if re.search(pat,str(r.indicator),re.I):
                    hits.append(180-10*rank)

        if not hits:
            return -999
        sc=max(hits)+min(float(r.pre_regions),85)/10+min(float(r.pre_years),3)*3
        if str(r.block)=="social_support" and has_any(q,SOCIAL_FORBIDDEN): return -999
        # Предпочитаем относительные/душевые структурные характеристики; абсолютный масштаб допустим только при отсутствии лучшего ряда.
        if has_any(q,["в процентах","на 1000","на душу","удельный вес","коэффициент","уровень"]): sc+=12
        if has_any(q,["миллионов рублей","тысяч человек","на конец года; человек"]) and not has_any(q,["на 1000","на душу","в процентах"]): sc-=12
        return sc

    # Явная проверка: блок социальной поддержки должен присутствовать
    # уже до scoring. Это отделяет проблему данных от проблемы whitelist.
    SOCIAL_SUPPORT_CANDIDATES=PRED[PRED.block.eq("social_support")].copy()
    if len(SOCIAL_SUPPORT_CANDIDATES)==0:
        raise RuntimeError(
            "В полном research-grade coverage отсутствуют кандидаты social_support. "
            "Это уже проблема данных/классификации, а не whitelist."
        )

    PRED["predictor_score"]=PRED.apply(predictor_score,axis=1)
    SOCIAL_SUPPORT_CANDIDATES=PRED[PRED.block.eq("social_support")][
        ["indicator_id","indicator","source","predictor_score","pre_regions","pre_years","research_grade"]
    ].sort_values(["predictor_score","pre_regions"],ascending=[False,False]).reset_index(drop=True)

    print("\nКандидаты блока social_support перед окончательным отбором:")
    display(SOCIAL_SUPPORT_CANDIDATES.head(20))

    if int((SOCIAL_SUPPORT_CANDIDATES.predictor_score>0).sum())<3:
        raise RuntimeError(
            "Данные social_support найдены, но whitelist/code-selector пропустил менее 3 показателей. "
            "Смотрите SOCIAL_SUPPORT_CANDIDATES."
        )

    pred_ids=[]; pred_meta={}; selected_rows=[]
    for bl in PREDICTOR_BLOCKS:
        g=PRED[(PRED.block==bl)&(PRED.predictor_score>0)].sort_values(["predictor_score","pre_regions","coverage"],ascending=[False,False,False])
        seen=set()
        for _,r in g.iterrows():
            sk=semantic_key(r.indicator)
            if sk in seen: continue
            seen.add(sk); pred_ids.append(r.indicator_id); pred_meta[r.indicator_id]=(bl,r.indicator); selected_rows.append(r)
            limit=3 if bl=="social_support" else 4
            if sum(pred_meta[x][0]==bl for x in pred_ids)>=limit: break
    PREDICTOR_SELECTION=pd.DataFrame(selected_rows).drop_duplicates("indicator_id") if selected_rows else pd.DataFrame()
    required_pred_counts={"demography":3,"income":3,"labour":3,"industry":3,"social_support":3}
    counts=pd.Series([pred_meta[x][0] for x in pred_ids],dtype="object").value_counts()
    bad={b:int(counts.get(b,0)) for b,nmin in required_pred_counts.items() if int(counts.get(b,0))<nmin}
    PREDICTOR_BLOCK_AUDIT=pd.DataFrame([
        {"block":b,"selected":int(counts.get(b,0)),"required_min":nmin,
         "status":"ok" if int(counts.get(b,0))>=nmin else "fail"}
        for b,nmin in required_pred_counts.items()
    ])
    if bad:
        display(PRED[PRED.block.isin(required_pred_counts)].sort_values(
            ["block","predictor_score"],ascending=[True,False]
        )[["block","indicator","predictor_score","pre_regions","pre_years","research_grade"]].head(120))
        raise RuntimeError(f"После содержательного whitelist недостаточно факторов по блокам: {bad}")

    pred_code={iid:f"p{j:03d}" for j,iid in enumerate(pred_ids,1)}
    STAT_RU={"mean":"уровень","slope":"тренд"}
    def short_title(s,n=72):
        x=re.sub(r"\s+"," ",str(s)).strip(); parts=[p.strip() for p in x.split("|") if p.strip()]
        parts=[p for p in parts if "социально-экономические показатели" not in norm(p) and "федеральный округ" not in norm(p) and "раздел " not in norm(p)]
        x=parts[0] if parts else x
        return x if len(x)<=n else x[:n-1]+"…"

    def needs_log(title):
        q=norm(title)
        return has_any(q,["рублей","тысяч человек","миллионов рублей","человек"]) and not has_any(q,["процент","на 1000","на 10 000","на душу","коэффициент","индекс","удельный вес","уровень"])

    # V5.6: одинаково тестируем общие компоненты и четыре содержательных оси.
    MODEL_TARGETS=(CONTINUOUS_TARGETS[["region","PC1","PC2"]]
                   .merge(BLOCK_TARGETS,on="region",how="inner"))

    def build_predictors(years,show_progress=False,label="ПРЕДИКТОРЫ"):
        rows=[]; _regs=MODEL_TARGETS.region.tolist(); _iter=pbar(_regs,desc=label,unit="рег.",leave=True) if show_progress else _regs
        for reg in _iter:
            rr={"region":reg}
            for iid in pred_ids:
                bl,title=pred_meta[iid]
                vals=PANEL[(PANEL.region==reg)&(PANEL.indicator_id==iid)&PANEL.year.isin(years)].groupby("year").value.median().reindex(years).to_numpy(float)
                if needs_log(title):
                    vals=np.where(vals>=0,np.log1p(vals),np.nan)
                code=pred_code[iid]; finite=np.isfinite(vals)
                rr[f"{bl}__{code}__mean"]=np.nanmean(vals) if finite.any() else np.nan
                rr[f"{bl}__{code}__slope"]=np.polyfit(np.arange(len(vals))[finite],vals[finite],1)[0] if finite.sum()>=2 else np.nan
            rows.append(rr)
        return pd.DataFrame(rows).merge(MODEL_TARGETS,on="region",how="inner").merge(CLUSTERS[["region","cluster","type"]],on="region",how="left")

    FEATURE_META=[]
    for iid,(bl,title) in pred_meta.items():
        for st in ["mean","slope"]:
            FEATURE_META.append({"feature":f"{bl}__{pred_code[iid]}__{st}","indicator_id":iid,"block":bl,"stat":st,"indicator":title,"transform":"log1p" if needs_log(title) else "raw","label":short_title(title)+" — "+STAT_RU[st]})
    FEATURE_META=pd.DataFrame(FEATURE_META)

    XDF=build_predictors(PRE_YEARS,show_progress=True,label="4A/7 ПРЕДШОКОВЫЕ ПРИЗНАКИ")
    feature_cols=[c for c in XDF if "__" in c and XDF[c].notna().mean()>=.55 and XDF[c].nunique(dropna=True)>1]
    # Корреляционный отсев проводится ВНУТРИ блоков. Межблочную корреляцию не используем
    # как повод удалить целый теоретически заданный механизм (особенно social_support).
    keep=[]
    for bl in PREDICTOR_BLOCKS:
        cols=[c for c in feature_cols if c.startswith(bl+"__")]
        if not cols:
            continue
        completeness={c:float(XDF[c].notna().mean()) for c in cols}
        ordered=sorted(cols,key=lambda c:(-completeness[c],c))
        corr=XDF[ordered].corr(method="spearman",min_periods=20).abs()
        kept_bl=[]
        for c in ordered:
            if not any(pd.notna(corr.loc[c,k]) and corr.loc[c,k]>.85 for k in kept_bl):
                kept_bl.append(c)
        keep.extend(kept_bl)
    feature_cols=keep
    if len(feature_cols)<10:
        raise RuntimeError("После контроля пропусков/внутриблочных корреляций осталось слишком мало предикторов.")
    X=XDF[feature_cols]
    blocks={bl:[c for c in feature_cols if c.startswith(bl+"__")] for bl in PREDICTOR_BLOCKS}
    missing_model_blocks=[b for b in PREDICTOR_BLOCKS if len(blocks.get(b,[]))==0]
    if missing_model_blocks:
        raise RuntimeError(f"После подготовки признаков исчезли обязательные блоки: {missing_model_blocks}")

    def cb_cls(seed=SEED,iters=600): return CatBoostClassifier(iterations=iters,depth=5,learning_rate=.04,loss_function="MultiClass",auto_class_weights="Balanced",random_seed=seed,verbose=False,allow_writing_files=False)
    def cb_reg(seed=SEED,iters=600): return CatBoostRegressor(iterations=iters,depth=5,learning_rate=.04,loss_function="RMSE",random_seed=seed,verbose=False,allow_writing_files=False)

    # ------------------------------------------------------------------
    # V5.6. Этап 1: одинаковая первичная валидация всех непрерывных целей.
    # ------------------------------------------------------------------
    TARGETS=["PC1","PC2"]+[f"{b}_axis" for b in OUTCOME_BLOCKS if f"{b}_axis" in XDF.columns]
    TARGET_LABELS={
        "PC1":"Общая компонента PC1",
        "PC2":"Общая компонента PC2",
        "demography_axis":"Демографическая траектория",
        "income_axis":"Траектория доходов",
        "labour_axis":"Траектория рынка труда",
        "industry_axis":"Экономическая траектория",
    }
    CV_ROWS=[]; LOYO_ROWS=[]; BOOT_ROWS=[]; NEG_ROWS=[]
    PERM_ROWS=[]; SHAP_ROWS=[]; LINEAR_ROWS=[]; ABL_ROWS=[]
    PREDICTIONS=XDF[["region"]].copy()

    def _fit_predict_pair(Xtr,Xte,ytr,seed):
        im=SimpleImputer(strategy="median",keep_empty_features=True)
        a=im.fit_transform(Xtr); b=im.transform(Xte)
        sc=StandardScaler(); ar=sc.fit_transform(a); br=sc.transform(b)
        rg=Ridge(alpha=1.0).fit(ar,ytr)
        cb=cb_reg(seed,iters=450); cb.fit(a,ytr)
        return rg.predict(br),cb.predict(b)

    for ti,target in enumerate(TARGETS,1):
        y=XDF[target].to_numpy(float)
        splits=list(RepeatedKFold(
            n_splits=5,n_repeats=REPEATED_CV_REPEATS,random_state=SEED
        ).split(X,y))
        pred_sum=np.zeros(len(y),float); pred_n=np.zeros(len(y),int)
        for f,(tr,te) in enumerate(pbar(
            splits,desc=f"6A CV {ti}/{len(TARGETS)} {target}",unit="fold",leave=False
        )):
            pl,pc=_fit_predict_pair(X.iloc[tr],X.iloc[te],y[tr],SEED+100*ti+f)
            pred_sum[te]+=pc; pred_n[te]+=1
            for name,p in [("Ridge",pl),("CatBoost",pc)]:
                CV_ROWS.append({
                    "target":target,"fold":f,"model":name,
                    "r2":r2_score(y[te],p),"mae":mean_absolute_error(y[te],p),
                    "n_test":len(te)
                })
        PREDICTIONS[target]=y
        PREDICTIONS[target+"_catboost_pred"]=pred_sum/np.maximum(pred_n,1)

        # LOYO: каждый предшоковый год исключается из построения факторов.
        for held in PRE_YEARS:
            years=[yy for yy in PRE_YEARS if yy!=held]
            D=build_predictors(years)
            cols=[c for c in feature_cols if c in D.columns and D[c].notna().mean()>=.50 and D[c].nunique(dropna=True)>1]
            yy=D[target].to_numpy(float)
            vals=[]
            for tr,te in KFold(5,shuffle=True,random_state=SEED+held+10*ti).split(D[cols],yy):
                im=SimpleImputer(strategy="median",keep_empty_features=True)
                a=im.fit_transform(D.iloc[tr][cols]); b=im.transform(D.iloc[te][cols])
                m=cb_reg(SEED+held+10*ti,iters=350); m.fit(a,yy[tr])
                vals.append(r2_score(yy[te],m.predict(b)))
            LOYO_ROWS.append({
                "target":target,"held_year":held,"r2":float(np.mean(vals)),"features":len(cols)
            })

    CV_METRICS=pd.DataFrame(CV_ROWS)
    TEMPORAL=pd.DataFrame(LOYO_ROWS)

    # Первичный screening: только положительные и лучше линейного baseline цели
    # проходят к дорогим robustness-проверкам.
    screen_rows=[]
    for target in TARGETS:
        cbv=CV_METRICS[(CV_METRICS.target==target)&(CV_METRICS.model=="CatBoost")].r2.astype(float)
        rgv=CV_METRICS[(CV_METRICS.target==target)&(CV_METRICS.model=="Ridge")].r2.astype(float)
        ly=TEMPORAL[TEMPORAL.target.eq(target)].r2.astype(float)
        row={
            "target":target,
            "label":TARGET_LABELS.get(target,target),
            "cv_r2_mean":float(cbv.mean()),
            "cv_r2_median":float(cbv.median()),
            "cv_positive_share":float((cbv>0).mean()),
            "ridge_r2_mean":float(rgv.mean()),
            "catboost_minus_ridge":float(cbv.mean()-rgv.mean()),
            "loyo_r2_median":float(ly.median()),
            "loyo_positive_share":float((ly>0).mean()),
        }
        row["screen_pass"]=bool(
            row["cv_r2_mean"]>0 and
            row["cv_r2_median"]>0 and
            row["catboost_minus_ridge"]>0 and
            row["loyo_positive_share"]>=2/3
        )
        screen_rows.append(row)
    TARGET_SCREEN=pd.DataFrame(screen_rows)
    SCREENED_TARGETS=TARGET_SCREEN.loc[TARGET_SCREEN.screen_pass,"target"].tolist()

    # ------------------------------------------------------------------
    # V5.6. Этап 2: robustness только для прошедших screening целей.
    # ------------------------------------------------------------------
    def cv_reg_score(cols,yv,seed_shift=0,iters=300):
        vals=[]
        for tr,te in KFold(5,shuffle=True,random_state=SEED+seed_shift).split(X[cols],yv):
            im=SimpleImputer(strategy="median",keep_empty_features=True)
            a=im.fit_transform(X.iloc[tr][cols]); b=im.transform(X.iloc[te][cols])
            m=cb_reg(SEED+seed_shift,iters=iters); m.fit(a,yv[tr])
            vals.append(r2_score(yv[te],m.predict(b)))
        return float(np.mean(vals))

    for ti,target in enumerate(SCREENED_TARGETS,1):
        y=XDF[target].to_numpy(float)
        rng=np.random.default_rng(SEED+5000+ti)

        # Bootstrap регионов с OOB оценкой.
        for r in pbar(range(BOOT_N),desc=f"6B BOOT {ti}/{len(SCREENED_TARGETS)} {target}",unit="rep",leave=False):
            idx=rng.integers(0,len(y),len(y))
            oob=np.setdiff1d(np.arange(len(y)),np.unique(idx))
            if len(oob)<12:
                continue
            im=SimpleImputer(strategy="median",keep_empty_features=True)
            a=im.fit_transform(X.iloc[idx]); b=im.transform(X.iloc[oob])
            m=cb_reg(SEED+7000+r+100*ti,iters=350); m.fit(a,y[idx])
            BOOT_ROWS.append({
                "target":target,"rep":r,"n_oob":len(oob),
                "score":r2_score(y[oob],m.predict(b)),"metric":"r2"
            })

        # Negative control: permutation target, +1 correction применяется ниже.
        for r in pbar(range(NEGATIVE_N_FINAL),desc=f"6C NEG {ti}/{len(SCREENED_TARGETS)} {target}",unit="perm",leave=False):
            yp=rng.permutation(y)
            NEG_ROWS.append({
                "target":target,"rep":r,
                "score":cv_reg_score(feature_cols,yp,seed_shift=10000+1000*ti+r,iters=220),
                "metric":"r2"
            })

    BOOTSTRAP=pd.DataFrame(BOOT_ROWS,columns=["target","rep","n_oob","score","metric"])
    NEGATIVE_CONTROL=pd.DataFrame(NEG_ROWS,columns=["target","rep","score","metric"])

    # Строгий научный gate по каждой цели.
    validation=[]
    for _,sr in TARGET_SCREEN.iterrows():
        target=sr.target
        b=BOOTSTRAP[BOOTSTRAP.target.eq(target)].score.astype(float)
        n=NEGATIVE_CONTROL[NEGATIVE_CONTROL.target.eq(target)].score.astype(float)
        real=float(sr.cv_r2_mean)
        neg_p=float((1+(n>=real).sum())/(1+len(n))) if len(n) else np.nan
        bmed=float(b.median()) if len(b) else np.nan
        bpos=float((b>0).mean()) if len(b) else np.nan
        validated=bool(
            sr.screen_pass and
            pd.notna(bmed) and bmed>0 and
            pd.notna(bpos) and bpos>=.60 and
            pd.notna(neg_p) and neg_p<.05
        )
        validation.append({
            **sr.to_dict(),
            "bootstrap_n":int(len(b)),
            "bootstrap_r2_median":bmed,
            "bootstrap_positive_share":bpos,
            "negative_n":int(len(n)),
            "negative_p":neg_p,
            "validated":validated,
        })
    TARGET_VALIDATION=pd.DataFrame(validation)
    VALIDATED_TARGETS=TARGET_VALIDATION.loc[TARGET_VALIDATION.validated,"target"].tolist()
    NEGATIVE_P_BY_TARGET=TARGET_VALIDATION[["target","negative_p"]].copy()
    pipeline_done("model_validation",f"валидация целей: кандидатов={len(SCREENED_TARGETS)}; прошли={len(VALIDATED_TARGETS)}")

    # ------------------------------------------------------------------
    # V5.6. Этап 3: интерпретация только валидированных целей.
    # ------------------------------------------------------------------
    IMP=SimpleImputer(strategy="median",keep_empty_features=True)
    XI=IMP.fit_transform(X)
    for ti,target in enumerate(VALIDATED_TARGETS,1):
        y=XDF[target].to_numpy(float)

        # Полная линейная модель и SHAP.
        sc=StandardScaler(); XIS=sc.fit_transform(XI)
        rg=Ridge(alpha=1.0).fit(XIS,y)
        LINEAR_ROWS.extend({
            "target":target,"class":"regression","feature":f,"coefficient":float(v)
        } for f,v in zip(feature_cols,rg.coef_))

        cb=cb_reg(SEED+20000+ti,iters=600); cb.fit(XI,y)
        sv=cb.get_feature_importance(Pool(XI,label=y),type="ShapValues")
        sa=np.mean(np.abs(sv[:,:-1]),axis=0)
        SHAP_ROWS.extend({
            "target":target,"feature":f,"mean_abs_shap":float(v)
        } for f,v in zip(feature_cols,sa))

        # Permutation importance в честном 5-fold.
        cv=list(KFold(5,shuffle=True,random_state=SEED+30000+ti).split(X,y))
        for f,(tr,te) in enumerate(pbar(cv,desc=f"6D PERM {target}",unit="fold",leave=False)):
            im=SimpleImputer(strategy="median",keep_empty_features=True)
            a=im.fit_transform(X.iloc[tr]); b=im.transform(X.iloc[te])
            m=cb_reg(SEED+31000+f+100*ti,iters=450); m.fit(a,y[tr])
            base=r2_score(y[te],m.predict(b))
            rng=np.random.default_rng(SEED+32000+f+100*ti)
            for j,c in enumerate(feature_cols):
                ds=[]
                for _ in range(12):
                    bp=b.copy(); bp[:,j]=rng.permutation(bp[:,j])
                    ds.append(base-r2_score(y[te],m.predict(bp)))
                PERM_ROWS.append({
                    "target":target,"fold":f,"feature":c,
                    "importance":float(np.mean(ds)),"sd":float(np.std(ds))
                })

        # Абляция пяти теоретических блоков.
        full=cv_reg_score(feature_cols,y,seed_shift=40000+ti,iters=400)
        ABL_ROWS.append({
            "target":target,"removed_block":"none","available":True,
            "features":len(feature_cols),"score":full,"metric":"r2","delta":0.0
        })
        for bl in PREDICTOR_BLOCKS:
            rem=blocks.get(bl,[])
            use=[c for c in feature_cols if c not in rem]
            scv=cv_reg_score(use,y,seed_shift=41000+100*ti+PREDICTOR_BLOCKS.index(bl),iters=400) if rem else np.nan
            ABL_ROWS.append({
                "target":target,"removed_block":bl,"available":bool(rem),
                "features":len(use),"score":scv,"metric":"r2",
                "delta":full-scv if pd.notna(scv) else np.nan
            })

    PERMUTATION=pd.DataFrame(PERM_ROWS,columns=["target","fold","feature","importance","sd"])
    if len(PERMUTATION):
        PERMUTATION=(PERMUTATION.groupby(["target","feature"])
                     .agg(importance=("importance","mean"),sd=("sd","mean")).reset_index())
    SHAP=pd.DataFrame(SHAP_ROWS,columns=["target","feature","mean_abs_shap"])
    LINEAR_COEF=pd.DataFrame(LINEAR_ROWS,columns=["target","class","feature","coefficient"])
    ABLATION=pd.DataFrame(ABL_ROWS,columns=["target","removed_block","available","features","score","metric","delta"])

    if len(PERMUTATION):
        PERMUTATION=PERMUTATION.merge(FEATURE_META,on="feature",how="left")
    if len(SHAP):
        SHAP=SHAP.merge(FEATURE_META,on="feature",how="left")
    if len(LINEAR_COEF):
        LINEAR_COEF=LINEAR_COEF.merge(FEATURE_META,on="feature",how="left")

    pipeline_done("interpretability",f"валидированных целей={len(VALIDATED_TARGETS)}")

    # Совместимые итоговые показатели без ложного требования «положительной PC1».
    if VALIDATED_TARGETS:
        _best=(TARGET_VALIDATION[TARGET_VALIDATION.validated]
               .sort_values("cv_r2_mean",ascending=False).iloc[0])
    else:
        _best=TARGET_VALIDATION.sort_values("cv_r2_mean",ascending=False).iloc[0]
    PRIMARY_MODEL_TARGET=str(_best.target)
    MODEL_PRIMARY_SCORE=float(_best.cv_r2_mean)
    MODEL_BASELINE_SCORE=float(_best.ridge_r2_mean)
    NEGATIVE_P=float(_best.negative_p) if pd.notna(_best.negative_p) else np.nan

    XDF.to_parquet(PROCESSED/"predictors.parquet",index=False)
    PREDICTIONS.to_csv(PROCESSED/"model_predictions.csv",index=False)
    FEATURE_META.to_csv(PROCESSED/"feature_dictionary.csv",index=False)
    PREDICTOR_SELECTION.to_csv(PROCESSED/"selected_predictors.csv",index=False)
    TARGET_SCREEN.to_csv(PROCESSED/"target_screen.csv",index=False)
    TARGET_VALIDATION.to_csv(PROCESSED/"target_validation.csv",index=False)

    # Публикационные графики — только подтвержденные интерпретационные цели.
    RU_BLOCK_SHORT={"demography":"Демография","income":"Доходы","labour":"Рынок труда","industry":"Экономическая структура","social_support":"Социальная поддержка"}
    for target in VALIDATED_TARGETS:
        safe=re.sub(r"[^A-Za-z0-9_]+","_",target)
        if len(SHAP):
            q=SHAP[SHAP.target.eq(target)].nlargest(18,"mean_abs_shap").sort_values("mean_abs_shap")
            if len(q):
                plt.figure(figsize=(11,7.2)); plt.barh(q.label,q.mean_abs_shap)
                plt.xlabel("Среднее абсолютное значение SHAP"); plt.ylabel(""); plt.tight_layout()
                for ext in ("png","svg"):
                    plt.savefig(FIG/f"shap_{safe}.{ext}",dpi=600 if ext=="png" else None,bbox_inches="tight")
                plt.close()
        if len(ABLATION):
            q=ABLATION[(ABLATION.target.eq(target))&(ABLATION.removed_block!="none")&ABLATION.available].copy()
            q["label"]=q.removed_block.map(RU_BLOCK_SHORT); q=q.sort_values("delta")
            if len(q):
                plt.figure(figsize=(8.5,5.2)); plt.barh(q.label,q.delta); plt.axvline(0,color="black",lw=.8)
                plt.xlabel("Снижение R² после исключения блока"); plt.tight_layout()
                for ext in ("png","svg"):
                    plt.savefig(FIG/f"ablation_{safe}.{ext}",dpi=600 if ext=="png" else None,bbox_inches="tight")
                plt.close()

    timing_end(
        "04_explanatory_models_and_robustness",_STAGE4_T0,
        detail=f"targets={len(TARGETS)}; screened={len(SCREENED_TARGETS)}; validated={len(VALIDATED_TARGETS)}; features={len(feature_cols)}"
    )
    print("\nПЕРВИЧНЫЙ SCREENING ЦЕЛЕЙ:"); display(TARGET_SCREEN)
    print("\nСТРОГАЯ ВАЛИДАЦИЯ ЦЕЛЕЙ:"); display(TARGET_VALIDATION)
    if VALIDATED_TARGETS:
        print("Для SHAP/permutation/абляций допущены:",", ".join(VALIDATED_TARGETS))
    else:
        print("Ни одна цель не прошла строгий gate; факторная интерпретация не выполнялась.")

▶ 04_explanatory_models_and_robustness

Кандидаты блока social_support перед окончательным отбором:

,indicator_id,indicator,source,predictor_score,pre_regions,pre_years,research_grade
0,regions_app_179832ef51218e57,3.29. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СОЦИАЛЬНОЙ ПОДД...,regions_app,179.5,85,3,True
1,regions_app_2c64b704beedeaca,3.28. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СУБСИДИЙ НА ОПЛ...,regions_app,164.5,85,3,True
2,regions_app_771890f566f008f5,3.29. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СОЦИАЛЬНОЙ ПОДД...,regions_app,137.5,85,3,True
3,regions_app_8aceecc13b316fdc,3.28. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СУБСИДИЙ НА ОПЛ...,regions_app,134.5,85,3,True
4,regions_app_c7615575e41de887,19.3. РАСХОДЫ КОНСОЛИДИРОВАННЫХ БЮДЖЕТОВ СУБЪЕ...,regions_app,107.5,85,3,True
5,regions_app_e00e92562176de09,3.29. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СОЦИАЛЬНОЙ ПОДД...,regions_app,92.5,85,3,True
6,regions_app_f1f82ccbbf545ff9,3.28. ПРЕДОСТАВЛЕНИЕ ГРАЖДАНАМ СУБСИДИЙ НА ОПЛ...,regions_app,77.5,85,3,True

4A/7 ПРЕДШОКОВЫЕ ПРИЗНАКИ:   0%|                            | 0/85 [00:00<?, ?рег./s]

6A CV 1/6 PC1:   0%|                            | 0/25 [00:00<?, ?fold/s]

6A CV 2/6 PC2:   0%|                            | 0/25 [00:00<?, ?fold/s]

6A CV 3/6 demography_axis:   0%|                            | 0/25 [00:00<?, ?fold/s]

6A CV 4/6 income_axis:   0%|                            | 0/25 [00:00<?, ?fold/s]

6A CV 5/6 labour_axis:   0%|                            | 0/25 [00:00<?, ?fold/s]

6A CV 6/6 industry_axis:   0%|                            | 0/25 [00:00<?, ?fold/s]

6B BOOT 1/1 demography_axis:   0%|                            | 0/100 [00:00<?, ?rep/s]

6C NEG 1/1 demography_axis:   0%|                            | 0/100 [00:00<?, ?perm/s]

6D PERM demography_axis:   0%|                            | 0/5 [00:00<?, ?fold/s]

✓ 04_explanatory_models_and_robustness: 1 ч 20 мин 31 с | targets=6; screened=1; validated=1; features=31

ПЕРВИЧНЫЙ SCREENING ЦЕЛЕЙ:

,target,label,cv_r2_mean,cv_r2_median,cv_positive_share,ridge_r2_mean,catboost_minus_ridge,loyo_r2_median,loyo_positive_share,screen_pass
0,PC1,Общая компонента PC1,-0.088031,-0.067834,0.40,-0.356671,0.268640,-0.095686,0.000000,False
1,PC2,Общая компонента PC2,0.100501,0.099694,0.56,-0.864633,0.965134,-0.022196,0.333333,False
2,demography_axis,Демографическая траектория,0.037059,0.029244,0.60,-1.299822,1.336881,0.083795,0.666667,True
3,income_axis,Траектория доходов,-0.304197,-0.248335,0.08,-2.020976,1.716779,-0.115257,0.000000,False
4,labour_axis,Траектория рынка труда,-0.027183,-0.005505,0.44,-0.272504,0.245321,-0.042716,0.000000,False
5,industry_axis,Экономическая траектория,-0.159823,-0.115563,0.24,-0.873363,0.713540,-0.164107,0.000000,False

СТРОГАЯ ВАЛИДАЦИЯ ЦЕЛЕЙ:

,target,label,cv_r2_mean,cv_r2_median,cv_positive_share,ridge_r2_mean,catboost_minus_ridge,loyo_r2_median,loyo_positive_share,screen_pass,bootstrap_n,bootstrap_r2_median,bootstrap_positive_share,negative_n,negative_p,validated
0,PC1,Общая компонента PC1,-0.088031,-0.067834,0.40,-0.356671,0.268640,-0.095686,0.000000,False,0,NaN,NaN,0,NaN,False
1,PC2,Общая компонента PC2,0.100501,0.099694,0.56,-0.864633,0.965134,-0.022196,0.333333,False,0,NaN,NaN,0,NaN,False
2,demography_axis,Демографическая траектория,0.037059,0.029244,0.60,-1.299822,1.336881,0.083795,0.666667,True,100,0.064062,0.65,100,0.009901,True
3,income_axis,Траектория доходов,-0.304197,-0.248335,0.08,-2.020976,1.716779,-0.115257,0.000000,False,0,NaN,NaN,0,NaN,False
4,labour_axis,Траектория рынка труда,-0.027183,-0.005505,0.44,-0.272504,0.245321,-0.042716,0.000000,False,0,NaN,NaN,0,NaN,False
5,industry_axis,Экономическая траектория,-0.159823,-0.115563,0.24,-0.873363,0.713540,-0.164107,0.000000,False,0,NaN,NaN,0,NaN,False

Для SHAP/permutation/абляций допущены: demography_axis

In [8]:
# 5. Финальная научная приемка V5.6 и основной компактный Excel
if not globals().get("CONTINUE_RESEARCH",False):
    print("Блок пропущен: CONTINUE_RESEARCH=False.")
else:
    _STAGE5_T0=timing_start("05_final_audit_and_exports")

    required_outcome={"demography","income","labour","industry"}
    source_ok_map={}
    if isinstance(SOURCE_AUDIT,pd.DataFrame) and {"source","ok"}.issubset(SOURCE_AUDIT.columns):
        source_ok_map={str(s): str(v).strip().lower() in {"true","1","yes","ok"} for s,v in zip(SOURCE_AUDIT["source"],SOURCE_AUDIT["ok"])}
    available_outcome=set(SELECTED.block.astype(str))
    predictor_blocks=set(PREDICTOR_SELECTION.block.astype(str))
    anti_direct=int(len(set(SELECTED.indicator_id)&set(PREDICTOR_SELECTION.indicator_id)))
    anti_sem=int(len(set(SELECTED.indicator.astype(str).map(semantic_key))&
                     set(PREDICTOR_SELECTION.indicator.astype(str).map(semantic_key))))

    block_axis_ok=bool(
        len(BLOCK_PCA_VARIANCE)>=4 and
        required_outcome.issubset(set(BLOCK_PCA_VARIANCE.block.astype(str))) and
        (BLOCK_PCA_VARIANCE.explained_variance.astype(float)>=.35).all()
    )
    TRAJECTORY_RESULT_ACCEPTED=bool(CONTINUUM_ACCEPTED or block_axis_ok)
    MODEL_HYPOTHESIS_SUPPORTED=bool(len(VALIDATED_TARGETS)>0)

    AUDIT_ROWS=[
      {"stage":"data_stage_gate","required":True,"status":"ok" if DATA_RECOMMENDED_READY else "fail",
       "detail":"обязательная приемка комплектности до моделирования"},
      {"stage":"primary_official_archive","required":True,"status":"ok" if source_ok_map.get("regions_app",False) else "fail",
       "detail":"основной официальный архив Росстата"},
      {"stage":"canonical_panel","required":True,"status":"ok" if PANEL.region.nunique()>=80 else "fail",
       "detail":f"regions={PANEL.region.nunique()}; indicators={PANEL.indicator_id.nunique()}"},
      {"stage":"outcome_blocks","required":True,"status":"ok" if required_outcome.issubset(available_outcome) else "fail",
       "detail":", ".join(sorted(available_outcome))},
      {"stage":"trajectory_direction","required":True,"status":"ok" if "direction_reason" in SELECTED.columns and SELECTED.direction.notna().all() else "fail",
       "detail":"направление outcome задано по конкретному показателю"},
      {"stage":"discrete_typology_tested","required":True,"status":"ok",
       "detail":f"typology_accepted={TYPOLOGY_ACCEPTED}; silhouette={PRIMARY_SIL:.3f}; результат может быть отрицательным"},
      {"stage":"continuous_geometry","required":True,"status":"ok" if TRAJECTORY_RESULT_ACCEPTED else "fail",
       "detail":f"continuum={CONTINUUM_ACCEPTED}; block_axes_ok={block_axis_ok}; norm_rho={norm_distance_rho:.3f}; indicator_rho={ind_geom:.3f}"},
      {"stage":"anti_circular_predictors","required":True,"status":"ok" if anti_direct==0 and anti_sem==0 else "fail",
       "detail":f"direct_overlap={anti_direct}; semantic_overlap={anti_sem}"},
      {"stage":"predictor_blocks","required":True,"status":"ok" if set(PREDICTOR_BLOCKS).issubset(predictor_blocks) else "fail",
       "detail":"available: "+", ".join(sorted(predictor_blocks))},
      {"stage":"target_screening","required":True,"status":"ok" if len(TARGET_SCREEN)==len(TARGETS) else "fail",
       "detail":f"tested={len(TARGET_SCREEN)}/{len(TARGETS)}"},
      {"stage":"target_validation","required":True,"status":"ok" if len(TARGET_VALIDATION)==len(TARGETS) else "fail",
       "detail":f"validated={len(VALIDATED_TARGETS)}; targets={', '.join(VALIDATED_TARGETS) if VALIDATED_TARGETS else 'none'}"},
      {"stage":"model_hypothesis","required":False,"status":"ok" if MODEL_HYPOTHESIS_SUPPORTED else "negative_result",
       "detail":"положительный факторный сигнал есть" if MODEL_HYPOTHESIS_SUPPORTED else "ни одна цель не прошла строгий gate; это допустимый научный результат"},
      {"stage":"interpretability_guard","required":True,"status":"ok" if (
          (not VALIDATED_TARGETS and len(SHAP)==0 and len(PERMUTATION)==0 and len(ABLATION)==0) or
          (VALIDATED_TARGETS and set(SHAP.target.unique())==set(VALIDATED_TARGETS) and
           set(PERMUTATION.target.unique())==set(VALIDATED_TARGETS) and
           set(ABLATION.target.unique())==set(VALIDATED_TARGETS))
       ) else "fail",
       "detail":"SHAP/permutation/абляции только для валидированных целей"},
    ]
    EXPERIMENT_AUDIT=pd.DataFrame(AUDIT_ROWS)
    RESEARCH_ACCEPTED=not ((EXPERIMENT_AUDIT.required)&(EXPERIMENT_AUDIT.status=="fail")).any()

    # Научная сводка отделяет успешность эксперимента от поддержки конкретных гипотез.
    SCIENTIFIC_SUMMARY=pd.DataFrame([
        {"metric":"experiment_complete","value":RESEARCH_ACCEPTED},
        {"metric":"discrete_typology_supported","value":TYPOLOGY_ACCEPTED},
        {"metric":"continuous_geometry_supported","value":CONTINUUM_ACCEPTED},
        {"metric":"block_axes_supported","value":block_axis_ok},
        {"metric":"analysis_mode","value":ANALYSIS_MODE},
        {"metric":"tested_model_targets","value":len(TARGETS)},
        {"metric":"validated_model_targets","value":len(VALIDATED_TARGETS)},
        {"metric":"validated_target_names","value":", ".join(VALIDATED_TARGETS) if VALIDATED_TARGETS else "none"},
        {"metric":"model_hypothesis_supported","value":MODEL_HYPOTHESIS_SUPPORTED},
    ])

    xlsx=RESULTS/"CHAPTER3_ANALYSIS_V5_6.xlsx"
    with pd.ExcelWriter(xlsx,engine="xlsxwriter") as w:
        RUN_TIMINGS=timing_frame()
        sheets={
          "SCIENTIFIC_SUMMARY":SCIENTIFIC_SUMMARY,
          "EXPERIMENT_AUDIT":EXPERIMENT_AUDIT,
          "RUN_TIMINGS":RUN_TIMINGS,
          "DATA_GATE":DATA_GATE,
          "SOURCE_AUDIT":SOURCE_AUDIT,
          "SOURCE_COMPLETENESS":SOURCE_COMPLETENESS,
          "PARSE_AUDIT":TABLE_INDEX,
          "BLOCK_COMPLETENESS":BLOCK_COMPLETENESS,
          "INDICATOR_COVERAGE":INDICATOR_COMPLETENESS,
          "SELECTED_TRAJECTORIES":SELECTED,
          "DIRECTION_AUDIT":DIRECTION_AUDIT,
          "TYPOLOGY_DIAGNOSTICS":TYPOLOGY_DIAGNOSTICS,
          "CLUSTER_STABILITY":CLUSTER_STABILITY,
          "CONTINUUM_STABILITY":CONTINUUM_STABILITY,
          "PCA_COORD":PCA_COORD,
          "PCA_VARIANCE":PCA_VARIANCE,
          "PCA_LOADINGS":PCA_LOADINGS,
          "BLOCK_TARGETS":BLOCK_TARGETS,
          "BLOCK_PCA_VARIANCE":BLOCK_PCA_VARIANCE,
          "BLOCK_PCA_LOADINGS":BLOCK_PCA_LOADINGS,
          "PREDICTOR_SELECTION":PREDICTOR_SELECTION,
          "PREDICTOR_BLOCK_AUDIT":PREDICTOR_BLOCK_AUDIT,
          "SOCIAL_SUPPORT_CAND":SOCIAL_SUPPORT_CANDIDATES,
          "FEATURE_DICTIONARY":FEATURE_META,
          "TARGET_SCREEN":TARGET_SCREEN,
          "TARGET_VALIDATION":TARGET_VALIDATION,
          "CV_METRICS":CV_METRICS,
          "TEMPORAL_LOYO":TEMPORAL,
          "BOOTSTRAP":BOOTSTRAP,
          "NEGATIVE_CONTROL":NEGATIVE_CONTROL,
          "SHAP_VALIDATED":SHAP,
          "PERM_VALIDATED":PERMUTATION,
          "ABLATION_VALIDATED":ABLATION,
          "LINEAR_VALIDATED":LINEAR_COEF,
        }
        for name,df in sheets.items():
            if isinstance(df,pd.DataFrame):
                df.to_excel(w,sheet_name=name[:31],index=False)

    # Отдельный короткий аудит.
    EXPERIMENT_AUDIT.to_excel(RESULTS/"EXPERIMENT_AUDIT_V5_6.xlsx",index=False)

    # Редактируемые данные рисунков: никаких тяжелых таблиц.
    FIGURE_BOOK=RESULTS/"FIGURES_EDITABLE_V5_6.xlsx"
    with pd.ExcelWriter(FIGURE_BOOK,engine="xlsxwriter") as fw:
        wb=fw.book
        PCA_COORD.to_excel(fw,sheet_name="PCA_SPACE",index=False)
        ws=fw.sheets["PCA_SPACE"]
        if len(PCA_COORD):
            ch=wb.add_chart({"type":"scatter","subtype":"straight_with_markers"})
            ch.add_series({"name":"Регионы","categories":["PCA_SPACE",1,1,len(PCA_COORD),1],
                           "values":["PCA_SPACE",1,2,len(PCA_COORD),2]})
            ch.set_x_axis({"name":"PC1"}); ch.set_y_axis({"name":"PC2"}); ch.set_legend({"none":True})
            ws.insert_chart("H2",ch,{"x_scale":1.3,"y_scale":1.3})

        TARGET_VALIDATION.to_excel(fw,sheet_name="TARGET_VALIDATION",index=False)
        BLOCK_PCA_VARIANCE.to_excel(fw,sheet_name="BLOCK_VARIANCE",index=False)
        for target in VALIDATED_TARGETS:
            safe=re.sub(r"[^A-Za-z0-9_]+","_",target)[:20]
            if len(SHAP):
                q=SHAP[SHAP.target.eq(target)].sort_values("mean_abs_shap",ascending=False).head(25)
                q.to_excel(fw,sheet_name=("SHAP_"+safe)[:31],index=False)
            if len(ABLATION):
                q=ABLATION[ABLATION.target.eq(target)].copy()
                q.to_excel(fw,sheet_name=("ABL_"+safe)[:31],index=False)

    timing_end("05_final_audit_and_exports",_STAGE5_T0,
               detail=f"accepted={RESEARCH_ACCEPTED}; validated_targets={len(VALIDATED_TARGETS)}")
    print("\nИТОГОВЫЙ НАУЧНЫЙ АУДИТ V5.6"); display(EXPERIMENT_AUDIT)
    print("\nСВОДКА"); display(SCIENTIFIC_SUMMARY)

▶ 05_final_audit_and_exports
✓ 05_final_audit_and_exports: 1.7 с | accepted=True; validated_targets=1

ИТОГОВЫЙ НАУЧНЫЙ АУДИТ V5.6

,stage,required,status,detail
0,data_stage_gate,True,ok,обязательная приемка комплектности до моделиро...
1,primary_official_archive,True,ok,основной официальный архив Росстата
2,canonical_panel,True,ok,regions=85; indicators=4596
3,outcome_blocks,True,ok,"demography, income, industry, labour"
4,trajectory_direction,True,ok,направление outcome задано по конкретному пока...
5,discrete_typology_tested,True,ok,typology_accepted=False; silhouette=0.112; рез...
6,continuous_geometry,True,ok,continuum=True; block_axes_ok=True; norm_rho=0...
7,anti_circular_predictors,True,ok,direct_overlap=0; semantic_overlap=0
8,predictor_blocks,True,ok,"available: demography, income, industry, labou..."
9,target_screening,True,ok,tested=6/6
10,target_validation,True,ok,validated=1; targets=demography_axis
11,model_hypothesis,False,ok,положительный факторный сигнал есть
12,interpretability_guard,True,ok,SHAP/permutation/абляции только для валидирова...

СВОДКА

                          metric                              value
0            experiment_complete                               True
1    discrete_typology_supported                              False
2  continuous_geometry_supported                               True
3           block_axes_supported                               True
4                  analysis_mode  multidimensional_continuous_space
5           tested_model_targets                                  6
6        validated_model_targets                                  1
7         validated_target_names                    demography_axis
8     model_hypothesis_supported                               True

In [9]:
# 6. Таблицы для статьи + компактный пакет воспроизводимости V5.6
if not globals().get("CONTINUE_RESEARCH",False):
    print("Блок пропущен.")
else:
    _STAGE6_T0=timing_start("06_article_and_reproducibility_outputs")

    # Сводки для статьи.
    cv_summary=(CV_METRICS.groupby(["target","model"])
                .agg(r2_mean=("r2","mean"),r2_median=("r2","median"),
                     r2_positive_share=("r2",lambda s:float((s>0).mean())),
                     mae_mean=("mae","mean"),folds=("fold","count"))
                .reset_index())
    loyo_summary=(TEMPORAL.groupby("target")
                  .agg(r2_median=("r2","median"),
                       positive_share=("r2",lambda s:float((s>0).mean())),
                       held_years=("held_year","nunique")).reset_index())
    if len(BOOTSTRAP):
        boot_summary=(BOOTSTRAP.groupby("target")
                      .agg(n=("score","count"),median=("score","median"),mean=("score","mean"),
                           q025=("score",lambda s:float(s.quantile(.025))),
                           q975=("score",lambda s:float(s.quantile(.975))),
                           positive_share=("score",lambda s:float((s>0).mean())))
                      .reset_index())
    else:
        boot_summary=pd.DataFrame(columns=["target","n","median","mean","q025","q975","positive_share"])

    article_xlsx=RESULTS/"ARTICLE_TABLES_V5_6.xlsx"
    with pd.ExcelWriter(article_xlsx,engine="xlsxwriter") as w:
        tables={
            "SCIENTIFIC_SUMMARY":SCIENTIFIC_SUMMARY,
            "TARGET_VALIDATION":TARGET_VALIDATION,
            "OUTCOME_INDICATORS":SELECTED,
            "DIRECTION_AUDIT":DIRECTION_AUDIT,
            "REGION_PCA":PCA_COORD,
            "REGION_BLOCK_AXES":BLOCK_TARGETS,
            "PCA_VARIANCE":PCA_VARIANCE,
            "PCA_LOADINGS":PCA_LOADINGS,
            "BLOCK_PCA_VARIANCE":BLOCK_PCA_VARIANCE,
            "BLOCK_PCA_LOADINGS":BLOCK_PCA_LOADINGS,
            "PREDICTORS":PREDICTOR_SELECTION,
            "PREDICTOR_BLOCK_AUDIT":PREDICTOR_BLOCK_AUDIT,
            "FEATURE_DICTIONARY":FEATURE_META,
            "CV_SUMMARY":cv_summary,
            "LOYO_SUMMARY":loyo_summary,
            "BOOTSTRAP_SUMMARY":boot_summary,
            "NEGATIVE_P":NEGATIVE_P_BY_TARGET,
            "SHAP_VALIDATED":SHAP,
            "PERM_VALIDATED":PERMUTATION,
            "ABLATION_VALIDATED":ABLATION,
            "EXPERIMENT_AUDIT":EXPERIMENT_AUDIT,
            "DATA_GATE":DATA_GATE,
        }
        for n,df in tables.items():
            if isinstance(df,pd.DataFrame):
                df.to_excel(w,sheet_name=n[:31],index=False)

    # Компактные CSV для повторного анализа результатов.
    research_data=RESULTS/"research_data"
    research_data.mkdir(exist_ok=True)
    small_tables={
        "scientific_summary.csv":SCIENTIFIC_SUMMARY,
        "experiment_audit.csv":EXPERIMENT_AUDIT,
        "target_validation.csv":TARGET_VALIDATION,
        "selected_outcomes.csv":SELECTED,
        "selected_predictors.csv":PREDICTOR_SELECTION,
        "feature_dictionary.csv":FEATURE_META,
        "regional_pca.csv":PCA_COORD,
        "regional_block_axes.csv":BLOCK_TARGETS,
        "pca_variance.csv":PCA_VARIANCE,
        "block_pca_variance.csv":BLOCK_PCA_VARIANCE,
        "cv_summary.csv":cv_summary,
        "loyo_summary.csv":loyo_summary,
        "bootstrap_summary.csv":boot_summary,
        "negative_p.csv":NEGATIVE_P_BY_TARGET,
        "shap_validated.csv":SHAP,
        "permutation_validated.csv":PERMUTATION,
        "ablation_validated.csv":ABLATION,
        "source_audit.csv":SOURCE_AUDIT,
        "source_completeness.csv":SOURCE_COMPLETENESS,
        "source_catalog.csv":SOURCE_CATALOG,
        "data_gate.csv":DATA_GATE,
    }
    for name,df in small_tables.items():
        if isinstance(df,pd.DataFrame):
            df.to_csv(research_data/name,index=False)

    # Конфигурация и зависимости — для воспроизводства нового запуска с нуля.
    config={
        "version":"V5.6",
        "seed":SEED,
        "pre_years":PRE_YEARS,
        "post_years":POST_YEARS,
        "shock_year":SHOCK_YEAR,
        "bootstrap_n":BOOT_N,
        "repeated_cv_repeats":REPEATED_CV_REPEATS,
        "negative_control_n":NEGATIVE_N_FINAL,
        "outcome_blocks":OUTCOME_BLOCKS,
        "predictor_blocks":PREDICTOR_BLOCKS,
        "validated_targets":VALIDATED_TARGETS,
        "analysis_mode":ANALYSIS_MODE,
        "typology_accepted":bool(TYPOLOGY_ACCEPTED),
        "continuum_accepted":bool(CONTINUUM_ACCEPTED),
        "research_accepted":bool(RESEARCH_ACCEPTED),
    }
    (RESULTS/"run_config_v5_6.json").write_text(json.dumps(config,ensure_ascii=False,indent=2),encoding="utf-8")
    requirements=[
        "pandas>=2.2","numpy","requests","beautifulsoup4","lxml","openpyxl","xlrd",
        "xlsxwriter","pyarrow","python-calamine","tqdm","scikit-learn","catboost",
        "matplotlib","joblib","scipy"
    ]
    (RESULTS/"requirements_v5_6.txt").write_text("\n".join(requirements)+"\n",encoding="utf-8")

    readme=f"""V5.6 REPRODUCIBILITY PACKAGE

Основной воспроизводимый объект — ноутбук MONOGRAPH_CH3_REGIONAL_RESILIENCE_ML_v5_6_FINAL.ipynb.
Он сам загружает доступные официальные источники Росстата, парсит их и повторяет эксперимент с нуля.

В этот компактный пакет намеренно НЕ включены:
- сырые скачанные архивы Росстата;
- распакованные XLS/XLSX;
- panel_raw/panel_clean/panel_long parquet;
- полный кэш загрузчика.

Причина: эти файлы воспроизводятся самим ноутбуком и делают архив избыточно большим.

Научный результат:
- дискретная типология: {TYPOLOGY_ACCEPTED};
- непрерывная геометрия: {CONTINUUM_ACCEPTED};
- валидированные модельные цели: {', '.join(VALIDATED_TARGETS) if VALIDATED_TARGETS else 'нет'};
- итог эксперимента: {'принят' if RESEARCH_ACCEPTED else 'требует проверки'}.

Для статьи используйте ARTICLE_TABLES_V5_6.xlsx и FIGURES_EDITABLE_V5_6.xlsx.
"""
    (RESULTS/"README_REPRODUCIBILITY_V5_6.txt").write_text(readme,encoding="utf-8")

    # SHA256 только для компактных результатов.
    compact_files=[
        RESULTS/"CHAPTER3_ANALYSIS_V5_6.xlsx",
        RESULTS/"ARTICLE_TABLES_V5_6.xlsx",
        RESULTS/"EXPERIMENT_AUDIT_V5_6.xlsx",
        RESULTS/"FIGURES_EDITABLE_V5_6.xlsx",
        RESULTS/"run_config_v5_6.json",
        RESULTS/"requirements_v5_6.txt",
        RESULTS/"README_REPRODUCIBILITY_V5_6.txt",
    ]+[p for p in research_data.glob("*.csv")]+[p for p in FIG.glob("*") if p.is_file()]
    compact_files=[p for p in compact_files if p.exists()]

    manifest=[]
    for p in compact_files:
        h=hashlib.sha256()
        with open(p,"rb") as f:
            for chunk in iter(lambda:f.read(1024*1024),b""):
                h.update(chunk)
        manifest.append({
            "file":str(p.relative_to(RESULTS)),
            "bytes":p.stat().st_size,
            "sha256":h.hexdigest()
        })
    MANIFEST=pd.DataFrame(manifest)
    MANIFEST.to_csv(RESULTS/"manifest_sha256_v5_6.csv",index=False)

    repro_zip=Path("/content/MONOGRAPH_CH3_V5_6_REPRODUCIBILITY.zip")
    repro_zip.unlink(missing_ok=True)
    with zipfile.ZipFile(repro_zip,"w",zipfile.ZIP_DEFLATED) as z:
        pack=compact_files+[RESULTS/"manifest_sha256_v5_6.csv"]
        for p in pbar(pack,desc="8/8 КОМПАКТНЫЙ REPRO ZIP",unit="файл",leave=True):
            if p.exists():
                z.write(p,arcname=str(p.relative_to(RESULTS)))

    timing_end("06_article_and_reproducibility_outputs",_STAGE6_T0,
               detail=f"zip={repro_zip.stat().st_size/1024**2:.1f} MB; validated={len(VALIDATED_TARGETS)}")
    RUN_TIMINGS=timing_frame()
    RUN_TIMINGS.to_csv(RESULTS/"RUN_TIMINGS_V5_6.csv",index=False)

    pipeline_done("exports",f"итоговые файлы готовы; zip={repro_zip.stat().st_size/1024**2:.1f} MB")
    pipeline_close()

    print("\n=== V5.6 ЗАВЕРШЕН ===")
    display(SCIENTIFIC_SUMMARY)
    display(TARGET_VALIDATION)
    print("Основной анализ:",RESULTS/"CHAPTER3_ANALYSIS_V5_6.xlsx")
    print("Таблицы для статьи:",article_xlsx)
    print("Редактируемые рисунки:",RESULTS/"FIGURES_EDITABLE_V5_6.xlsx")
    print("Научный аудит:",RESULTS/"EXPERIMENT_AUDIT_V5_6.xlsx")
    print("Компактный пакет воспроизводимости:",repro_zip)

▶ 06_article_and_reproducibility_outputs

8/8 КОМПАКТНЫЙ REPRO ZIP:   0%|                            | 0/35 [00:00<?, ?файл/s]

✓ 06_article_and_reproducibility_outputs: 0.3 с | zip=2.0 MB; validated=1

=== V5.6 ЗАВЕРШЕН ===

                          metric                              value
0            experiment_complete                               True
1    discrete_typology_supported                              False
2  continuous_geometry_supported                               True
3           block_axes_supported                               True
4                  analysis_mode  multidimensional_continuous_space
5           tested_model_targets                                  6
6        validated_model_targets                                  1
7         validated_target_names                    demography_axis
8     model_hypothesis_supported                               True

,target,label,cv_r2_mean,cv_r2_median,cv_positive_share,ridge_r2_mean,catboost_minus_ridge,loyo_r2_median,loyo_positive_share,screen_pass,bootstrap_n,bootstrap_r2_median,bootstrap_positive_share,negative_n,negative_p,validated
0,PC1,Общая компонента PC1,-0.088031,-0.067834,0.40,-0.356671,0.268640,-0.095686,0.000000,False,0,NaN,NaN,0,NaN,False
1,PC2,Общая компонента PC2,0.100501,0.099694,0.56,-0.864633,0.965134,-0.022196,0.333333,False,0,NaN,NaN,0,NaN,False
2,demography_axis,Демографическая траектория,0.037059,0.029244,0.60,-1.299822,1.336881,0.083795,0.666667,True,100,0.064062,0.65,100,0.009901,True
3,income_axis,Траектория доходов,-0.304197,-0.248335,0.08,-2.020976,1.716779,-0.115257,0.000000,False,0,NaN,NaN,0,NaN,False
4,labour_axis,Траектория рынка труда,-0.027183,-0.005505,0.44,-0.272504,0.245321,-0.042716,0.000000,False,0,NaN,NaN,0,NaN,False
5,industry_axis,Экономическая траектория,-0.159823,-0.115563,0.24,-0.873363,0.713540,-0.164107,0.000000,False,0,NaN,NaN,0,NaN,False

Основной анализ: /content/MONOGRAPH_CH3_V5_6/results/CHAPTER3_ANALYSIS_V5_6.xlsx
Таблицы для статьи: /content/MONOGRAPH_CH3_V5_6/results/ARTICLE_TABLES_V5_6.xlsx
Редактируемые рисунки: /content/MONOGRAPH_CH3_V5_6/results/FIGURES_EDITABLE_V5_6.xlsx
Научный аудит: /content/MONOGRAPH_CH3_V5_6/results/EXPERIMENT_AUDIT_V5_6.xlsx
Компактный пакет воспроизводимости: /content/MONOGRAPH_CH3_V5_6_REPRODUCIBILITY.zip